version: "3"
services:
  good_service:
    image: registry.cn-guangzhou.aliyuncs.com/mufe/good_service:latest
    env_file:
      - ../../../.env
    environment:
      - SERVICE_80_NAME=good_service
      - SERVICE_TAGS=mufe_service
      - PORT=80
    ports:
      - "80"
    networks:
     - micro


networks:
  micro:
    external:
      name: mufe_service_micro




