version: "3"
services:
  pay_service:
    image: registry.cn-guangzhou.aliyuncs.com/mufe/pay_service:latest
    env_file:
      - ../../.env
    environment:
      - SERVICE_80_NAME=pay_service
      - PORT=80
      - SERVICE_TAGS=mufe_service
    ports:
      - "80"
    networks:
     - micro


networks:
  micro:
    external:
      name: mufe_service_micro




