version: "3"
services:
  admin_course_api:
    image: registry.cn-guangzhou.aliyuncs.com/mufe/admin_course_api:latest
    env_file:
      - ../../.env
    environment:
      - SERVICE_80_NAME=admin_course_api
      - SERVICE_TAGS=mufe_service
      - PORT=80
    ports:
      - "80"
    networks:
     - micro


networks:
  micro:
    external:
      name: mufe_service_micro




