// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coach.proto

package app

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InstitutionRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Status               int64    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Uid                  int64    `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstitutionRequest) Reset()         { *m = InstitutionRequest{} }
func (m *InstitutionRequest) String() string { return proto.CompactTextString(m) }
func (*InstitutionRequest) ProtoMessage()    {}
func (*InstitutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{0}
}

func (m *InstitutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionRequest.Unmarshal(m, b)
}
func (m *InstitutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionRequest.Marshal(b, m, deterministic)
}
func (m *InstitutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionRequest.Merge(m, src)
}
func (m *InstitutionRequest) XXX_Size() int {
	return xxx_messageInfo_InstitutionRequest.Size(m)
}
func (m *InstitutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionRequest proto.InternalMessageInfo

func (m *InstitutionRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *InstitutionRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *InstitutionRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *InstitutionRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InstitutionRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *InstitutionRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type InstitutionData struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstitutionData) Reset()         { *m = InstitutionData{} }
func (m *InstitutionData) String() string { return proto.CompactTextString(m) }
func (*InstitutionData) ProtoMessage()    {}
func (*InstitutionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{1}
}

func (m *InstitutionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionData.Unmarshal(m, b)
}
func (m *InstitutionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionData.Marshal(b, m, deterministic)
}
func (m *InstitutionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionData.Merge(m, src)
}
func (m *InstitutionData) XXX_Size() int {
	return xxx_messageInfo_InstitutionData.Size(m)
}
func (m *InstitutionData) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionData.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionData proto.InternalMessageInfo

func (m *InstitutionData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InstitutionData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InstitutionData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstitutionData) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *InstitutionData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type InstitutionResponse struct {
	List                 []*InstitutionData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InstitutionResponse) Reset()         { *m = InstitutionResponse{} }
func (m *InstitutionResponse) String() string { return proto.CompactTextString(m) }
func (*InstitutionResponse) ProtoMessage()    {}
func (*InstitutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{2}
}

func (m *InstitutionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionResponse.Unmarshal(m, b)
}
func (m *InstitutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionResponse.Marshal(b, m, deterministic)
}
func (m *InstitutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionResponse.Merge(m, src)
}
func (m *InstitutionResponse) XXX_Size() int {
	return xxx_messageInfo_InstitutionResponse.Size(m)
}
func (m *InstitutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionResponse proto.InternalMessageInfo

func (m *InstitutionResponse) GetList() []*InstitutionData {
	if m != nil {
		return m.List
	}
	return nil
}

type EditInstitutionRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Prefix               string   `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Icon                 string   `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Del                  bool     `protobuf:"varint,6,opt,name=del,proto3" json:"del,omitempty"`
	Create               int64    `protobuf:"varint,7,opt,name=create,proto3" json:"create,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditInstitutionRequest) Reset()         { *m = EditInstitutionRequest{} }
func (m *EditInstitutionRequest) String() string { return proto.CompactTextString(m) }
func (*EditInstitutionRequest) ProtoMessage()    {}
func (*EditInstitutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{3}
}

func (m *EditInstitutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditInstitutionRequest.Unmarshal(m, b)
}
func (m *EditInstitutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditInstitutionRequest.Marshal(b, m, deterministic)
}
func (m *EditInstitutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditInstitutionRequest.Merge(m, src)
}
func (m *EditInstitutionRequest) XXX_Size() int {
	return xxx_messageInfo_EditInstitutionRequest.Size(m)
}
func (m *EditInstitutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditInstitutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditInstitutionRequest proto.InternalMessageInfo

func (m *EditInstitutionRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditInstitutionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditInstitutionRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EditInstitutionRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *EditInstitutionRequest) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *EditInstitutionRequest) GetDel() bool {
	if m != nil {
		return m.Del
	}
	return false
}

func (m *EditInstitutionRequest) GetCreate() int64 {
	if m != nil {
		return m.Create
	}
	return 0
}

type EditInstitutionResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditInstitutionResponse) Reset()         { *m = EditInstitutionResponse{} }
func (m *EditInstitutionResponse) String() string { return proto.CompactTextString(m) }
func (*EditInstitutionResponse) ProtoMessage()    {}
func (*EditInstitutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{4}
}

func (m *EditInstitutionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditInstitutionResponse.Unmarshal(m, b)
}
func (m *EditInstitutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditInstitutionResponse.Marshal(b, m, deterministic)
}
func (m *EditInstitutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditInstitutionResponse.Merge(m, src)
}
func (m *EditInstitutionResponse) XXX_Size() int {
	return xxx_messageInfo_EditInstitutionResponse.Size(m)
}
func (m *EditInstitutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditInstitutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditInstitutionResponse proto.InternalMessageInfo

func (m *EditInstitutionResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type InstitutionSchoolRequest struct {
	Iid                  int64    `protobuf:"varint,1,opt,name=iid,proto3" json:"iid,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Status               int64    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstitutionSchoolRequest) Reset()         { *m = InstitutionSchoolRequest{} }
func (m *InstitutionSchoolRequest) String() string { return proto.CompactTextString(m) }
func (*InstitutionSchoolRequest) ProtoMessage()    {}
func (*InstitutionSchoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{5}
}

func (m *InstitutionSchoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionSchoolRequest.Unmarshal(m, b)
}
func (m *InstitutionSchoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionSchoolRequest.Marshal(b, m, deterministic)
}
func (m *InstitutionSchoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionSchoolRequest.Merge(m, src)
}
func (m *InstitutionSchoolRequest) XXX_Size() int {
	return xxx_messageInfo_InstitutionSchoolRequest.Size(m)
}
func (m *InstitutionSchoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionSchoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionSchoolRequest proto.InternalMessageInfo

func (m *InstitutionSchoolRequest) GetIid() int64 {
	if m != nil {
		return m.Iid
	}
	return 0
}

func (m *InstitutionSchoolRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InstitutionSchoolRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *InstitutionSchoolRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *InstitutionSchoolRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type InstitutionSchool struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string               `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Icon                 string               `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Start                int64                `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64                `protobuf:"varint,6,opt,name=end,proto3" json:"end,omitempty"`
	Address              string               `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Course               []*InstitutionCourse `protobuf:"bytes,8,rep,name=course,proto3" json:"course,omitempty"`
	IsSelect             bool                 `protobuf:"varint,9,opt,name=isSelect,proto3" json:"isSelect,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InstitutionSchool) Reset()         { *m = InstitutionSchool{} }
func (m *InstitutionSchool) String() string { return proto.CompactTextString(m) }
func (*InstitutionSchool) ProtoMessage()    {}
func (*InstitutionSchool) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{6}
}

func (m *InstitutionSchool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionSchool.Unmarshal(m, b)
}
func (m *InstitutionSchool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionSchool.Marshal(b, m, deterministic)
}
func (m *InstitutionSchool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionSchool.Merge(m, src)
}
func (m *InstitutionSchool) XXX_Size() int {
	return xxx_messageInfo_InstitutionSchool.Size(m)
}
func (m *InstitutionSchool) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionSchool.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionSchool proto.InternalMessageInfo

func (m *InstitutionSchool) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InstitutionSchool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstitutionSchool) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *InstitutionSchool) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *InstitutionSchool) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *InstitutionSchool) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *InstitutionSchool) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InstitutionSchool) GetCourse() []*InstitutionCourse {
	if m != nil {
		return m.Course
	}
	return nil
}

func (m *InstitutionSchool) GetIsSelect() bool {
	if m != nil {
		return m.IsSelect
	}
	return false
}

type InstitutionCourse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Max                  int64    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Price                int64    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Level                string   `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	SchoolId             int64    `protobuf:"varint,6,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	Duration             int64    `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstitutionCourse) Reset()         { *m = InstitutionCourse{} }
func (m *InstitutionCourse) String() string { return proto.CompactTextString(m) }
func (*InstitutionCourse) ProtoMessage()    {}
func (*InstitutionCourse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{7}
}

func (m *InstitutionCourse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionCourse.Unmarshal(m, b)
}
func (m *InstitutionCourse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionCourse.Marshal(b, m, deterministic)
}
func (m *InstitutionCourse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionCourse.Merge(m, src)
}
func (m *InstitutionCourse) XXX_Size() int {
	return xxx_messageInfo_InstitutionCourse.Size(m)
}
func (m *InstitutionCourse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionCourse.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionCourse proto.InternalMessageInfo

func (m *InstitutionCourse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InstitutionCourse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstitutionCourse) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *InstitutionCourse) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *InstitutionCourse) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *InstitutionCourse) GetSchoolId() int64 {
	if m != nil {
		return m.SchoolId
	}
	return 0
}

func (m *InstitutionCourse) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type InstitutionSchoolResponse struct {
	List                 []*InstitutionSchool `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InstitutionSchoolResponse) Reset()         { *m = InstitutionSchoolResponse{} }
func (m *InstitutionSchoolResponse) String() string { return proto.CompactTextString(m) }
func (*InstitutionSchoolResponse) ProtoMessage()    {}
func (*InstitutionSchoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{8}
}

func (m *InstitutionSchoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionSchoolResponse.Unmarshal(m, b)
}
func (m *InstitutionSchoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionSchoolResponse.Marshal(b, m, deterministic)
}
func (m *InstitutionSchoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionSchoolResponse.Merge(m, src)
}
func (m *InstitutionSchoolResponse) XXX_Size() int {
	return xxx_messageInfo_InstitutionSchoolResponse.Size(m)
}
func (m *InstitutionSchoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionSchoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionSchoolResponse proto.InternalMessageInfo

func (m *InstitutionSchoolResponse) GetList() []*InstitutionSchool {
	if m != nil {
		return m.List
	}
	return nil
}

type EditInstitutionSchoolRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Prefix               string   `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Icon                 string   `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Del                  bool     `protobuf:"varint,6,opt,name=del,proto3" json:"del,omitempty"`
	Create               int64    `protobuf:"varint,7,opt,name=create,proto3" json:"create,omitempty"`
	Start                int64    `protobuf:"varint,8,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,9,opt,name=end,proto3" json:"end,omitempty"`
	Phone                string   `protobuf:"bytes,10,opt,name=phone,proto3" json:"phone,omitempty"`
	Course               []int64  `protobuf:"varint,11,rep,packed,name=course,proto3" json:"course,omitempty"`
	ParentId             int64    `protobuf:"varint,12,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditInstitutionSchoolRequest) Reset()         { *m = EditInstitutionSchoolRequest{} }
func (m *EditInstitutionSchoolRequest) String() string { return proto.CompactTextString(m) }
func (*EditInstitutionSchoolRequest) ProtoMessage()    {}
func (*EditInstitutionSchoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{9}
}

func (m *EditInstitutionSchoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditInstitutionSchoolRequest.Unmarshal(m, b)
}
func (m *EditInstitutionSchoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditInstitutionSchoolRequest.Marshal(b, m, deterministic)
}
func (m *EditInstitutionSchoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditInstitutionSchoolRequest.Merge(m, src)
}
func (m *EditInstitutionSchoolRequest) XXX_Size() int {
	return xxx_messageInfo_EditInstitutionSchoolRequest.Size(m)
}
func (m *EditInstitutionSchoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditInstitutionSchoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditInstitutionSchoolRequest proto.InternalMessageInfo

func (m *EditInstitutionSchoolRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditInstitutionSchoolRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditInstitutionSchoolRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EditInstitutionSchoolRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *EditInstitutionSchoolRequest) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *EditInstitutionSchoolRequest) GetDel() bool {
	if m != nil {
		return m.Del
	}
	return false
}

func (m *EditInstitutionSchoolRequest) GetCreate() int64 {
	if m != nil {
		return m.Create
	}
	return 0
}

func (m *EditInstitutionSchoolRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *EditInstitutionSchoolRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *EditInstitutionSchoolRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *EditInstitutionSchoolRequest) GetCourse() []int64 {
	if m != nil {
		return m.Course
	}
	return nil
}

func (m *EditInstitutionSchoolRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type InstitutionCourseRequest struct {
	Iid                  int64    `protobuf:"varint,1,opt,name=iid,proto3" json:"iid,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Status               int64    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	SchoolId             []int64  `protobuf:"varint,6,rep,packed,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstitutionCourseRequest) Reset()         { *m = InstitutionCourseRequest{} }
func (m *InstitutionCourseRequest) String() string { return proto.CompactTextString(m) }
func (*InstitutionCourseRequest) ProtoMessage()    {}
func (*InstitutionCourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{10}
}

func (m *InstitutionCourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionCourseRequest.Unmarshal(m, b)
}
func (m *InstitutionCourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionCourseRequest.Marshal(b, m, deterministic)
}
func (m *InstitutionCourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionCourseRequest.Merge(m, src)
}
func (m *InstitutionCourseRequest) XXX_Size() int {
	return xxx_messageInfo_InstitutionCourseRequest.Size(m)
}
func (m *InstitutionCourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionCourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionCourseRequest proto.InternalMessageInfo

func (m *InstitutionCourseRequest) GetIid() int64 {
	if m != nil {
		return m.Iid
	}
	return 0
}

func (m *InstitutionCourseRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InstitutionCourseRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *InstitutionCourseRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *InstitutionCourseRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *InstitutionCourseRequest) GetSchoolId() []int64 {
	if m != nil {
		return m.SchoolId
	}
	return nil
}

type InstitutionCourseResponse struct {
	List                 []*InstitutionCourse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InstitutionCourseResponse) Reset()         { *m = InstitutionCourseResponse{} }
func (m *InstitutionCourseResponse) String() string { return proto.CompactTextString(m) }
func (*InstitutionCourseResponse) ProtoMessage()    {}
func (*InstitutionCourseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{11}
}

func (m *InstitutionCourseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionCourseResponse.Unmarshal(m, b)
}
func (m *InstitutionCourseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionCourseResponse.Marshal(b, m, deterministic)
}
func (m *InstitutionCourseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionCourseResponse.Merge(m, src)
}
func (m *InstitutionCourseResponse) XXX_Size() int {
	return xxx_messageInfo_InstitutionCourseResponse.Size(m)
}
func (m *InstitutionCourseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionCourseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionCourseResponse proto.InternalMessageInfo

func (m *InstitutionCourseResponse) GetList() []*InstitutionCourse {
	if m != nil {
		return m.List
	}
	return nil
}

type EditInstitutionCourseRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Del                  bool     `protobuf:"varint,3,opt,name=del,proto3" json:"del,omitempty"`
	Create               int64    `protobuf:"varint,4,opt,name=create,proto3" json:"create,omitempty"`
	Max                  int64    `protobuf:"varint,5,opt,name=max,proto3" json:"max,omitempty"`
	Price                int64    `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Level                string   `protobuf:"bytes,7,opt,name=level,proto3" json:"level,omitempty"`
	ParentId             int64    `protobuf:"varint,8,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Duration             int64    `protobuf:"varint,9,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditInstitutionCourseRequest) Reset()         { *m = EditInstitutionCourseRequest{} }
func (m *EditInstitutionCourseRequest) String() string { return proto.CompactTextString(m) }
func (*EditInstitutionCourseRequest) ProtoMessage()    {}
func (*EditInstitutionCourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{12}
}

func (m *EditInstitutionCourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditInstitutionCourseRequest.Unmarshal(m, b)
}
func (m *EditInstitutionCourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditInstitutionCourseRequest.Marshal(b, m, deterministic)
}
func (m *EditInstitutionCourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditInstitutionCourseRequest.Merge(m, src)
}
func (m *EditInstitutionCourseRequest) XXX_Size() int {
	return xxx_messageInfo_EditInstitutionCourseRequest.Size(m)
}
func (m *EditInstitutionCourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditInstitutionCourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditInstitutionCourseRequest proto.InternalMessageInfo

func (m *EditInstitutionCourseRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditInstitutionCourseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditInstitutionCourseRequest) GetDel() bool {
	if m != nil {
		return m.Del
	}
	return false
}

func (m *EditInstitutionCourseRequest) GetCreate() int64 {
	if m != nil {
		return m.Create
	}
	return 0
}

func (m *EditInstitutionCourseRequest) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *EditInstitutionCourseRequest) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *EditInstitutionCourseRequest) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *EditInstitutionCourseRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *EditInstitutionCourseRequest) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type JoinInstitutionCourseRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Quit                 bool     `protobuf:"varint,3,opt,name=quit,proto3" json:"quit,omitempty"`
	Info                 string   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	InstitutionId        int64    `protobuf:"varint,5,opt,name=institutionId,proto3" json:"institutionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinInstitutionCourseRequest) Reset()         { *m = JoinInstitutionCourseRequest{} }
func (m *JoinInstitutionCourseRequest) String() string { return proto.CompactTextString(m) }
func (*JoinInstitutionCourseRequest) ProtoMessage()    {}
func (*JoinInstitutionCourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{13}
}

func (m *JoinInstitutionCourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinInstitutionCourseRequest.Unmarshal(m, b)
}
func (m *JoinInstitutionCourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinInstitutionCourseRequest.Marshal(b, m, deterministic)
}
func (m *JoinInstitutionCourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinInstitutionCourseRequest.Merge(m, src)
}
func (m *JoinInstitutionCourseRequest) XXX_Size() int {
	return xxx_messageInfo_JoinInstitutionCourseRequest.Size(m)
}
func (m *JoinInstitutionCourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinInstitutionCourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinInstitutionCourseRequest proto.InternalMessageInfo

func (m *JoinInstitutionCourseRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JoinInstitutionCourseRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *JoinInstitutionCourseRequest) GetQuit() bool {
	if m != nil {
		return m.Quit
	}
	return false
}

func (m *JoinInstitutionCourseRequest) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *JoinInstitutionCourseRequest) GetInstitutionId() int64 {
	if m != nil {
		return m.InstitutionId
	}
	return 0
}

type CoachListRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Iid                  int64    `protobuf:"varint,4,opt,name=iid,proto3" json:"iid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoachListRequest) Reset()         { *m = CoachListRequest{} }
func (m *CoachListRequest) String() string { return proto.CompactTextString(m) }
func (*CoachListRequest) ProtoMessage()    {}
func (*CoachListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{14}
}

func (m *CoachListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoachListRequest.Unmarshal(m, b)
}
func (m *CoachListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoachListRequest.Marshal(b, m, deterministic)
}
func (m *CoachListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoachListRequest.Merge(m, src)
}
func (m *CoachListRequest) XXX_Size() int {
	return xxx_messageInfo_CoachListRequest.Size(m)
}
func (m *CoachListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoachListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoachListRequest proto.InternalMessageInfo

func (m *CoachListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *CoachListRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CoachListRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CoachListRequest) GetIid() int64 {
	if m != nil {
		return m.Iid
	}
	return 0
}

type CoachData struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	InstitutionId        int64    `protobuf:"varint,3,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoachData) Reset()         { *m = CoachData{} }
func (m *CoachData) String() string { return proto.CompactTextString(m) }
func (*CoachData) ProtoMessage()    {}
func (*CoachData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{15}
}

func (m *CoachData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoachData.Unmarshal(m, b)
}
func (m *CoachData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoachData.Marshal(b, m, deterministic)
}
func (m *CoachData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoachData.Merge(m, src)
}
func (m *CoachData) XXX_Size() int {
	return xxx_messageInfo_CoachData.Size(m)
}
func (m *CoachData) XXX_DiscardUnknown() {
	xxx_messageInfo_CoachData.DiscardUnknown(m)
}

var xxx_messageInfo_CoachData proto.InternalMessageInfo

func (m *CoachData) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CoachData) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *CoachData) GetInstitutionId() int64 {
	if m != nil {
		return m.InstitutionId
	}
	return 0
}

func (m *CoachData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CoachListResponse struct {
	List                 []*CoachData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CoachListResponse) Reset()         { *m = CoachListResponse{} }
func (m *CoachListResponse) String() string { return proto.CompactTextString(m) }
func (*CoachListResponse) ProtoMessage()    {}
func (*CoachListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{16}
}

func (m *CoachListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoachListResponse.Unmarshal(m, b)
}
func (m *CoachListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoachListResponse.Marshal(b, m, deterministic)
}
func (m *CoachListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoachListResponse.Merge(m, src)
}
func (m *CoachListResponse) XXX_Size() int {
	return xxx_messageInfo_CoachListResponse.Size(m)
}
func (m *CoachListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CoachListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CoachListResponse proto.InternalMessageInfo

func (m *CoachListResponse) GetList() []*CoachData {
	if m != nil {
		return m.List
	}
	return nil
}

type InstitutionWorkRequest struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Place                int64    `protobuf:"varint,3,opt,name=place,proto3" json:"place,omitempty"`
	Course               int64    `protobuf:"varint,4,opt,name=course,proto3" json:"course,omitempty"`
	Desc                 string   `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Uid                  int64    `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Del                  bool     `protobuf:"varint,7,opt,name=del,proto3" json:"del,omitempty"`
	Id                   int64    `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstitutionWorkRequest) Reset()         { *m = InstitutionWorkRequest{} }
func (m *InstitutionWorkRequest) String() string { return proto.CompactTextString(m) }
func (*InstitutionWorkRequest) ProtoMessage()    {}
func (*InstitutionWorkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{17}
}

func (m *InstitutionWorkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionWorkRequest.Unmarshal(m, b)
}
func (m *InstitutionWorkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionWorkRequest.Marshal(b, m, deterministic)
}
func (m *InstitutionWorkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionWorkRequest.Merge(m, src)
}
func (m *InstitutionWorkRequest) XXX_Size() int {
	return xxx_messageInfo_InstitutionWorkRequest.Size(m)
}
func (m *InstitutionWorkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionWorkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionWorkRequest proto.InternalMessageInfo

func (m *InstitutionWorkRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *InstitutionWorkRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *InstitutionWorkRequest) GetPlace() int64 {
	if m != nil {
		return m.Place
	}
	return 0
}

func (m *InstitutionWorkRequest) GetCourse() int64 {
	if m != nil {
		return m.Course
	}
	return 0
}

func (m *InstitutionWorkRequest) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *InstitutionWorkRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *InstitutionWorkRequest) GetDel() bool {
	if m != nil {
		return m.Del
	}
	return false
}

func (m *InstitutionWorkRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type InstitutionWorkListRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Place                int64    `protobuf:"varint,3,opt,name=place,proto3" json:"place,omitempty"`
	End                  int64    `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	Id                   []int64  `protobuf:"varint,5,rep,packed,name=id,proto3" json:"id,omitempty"`
	Status               int64    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstitutionWorkListRequest) Reset()         { *m = InstitutionWorkListRequest{} }
func (m *InstitutionWorkListRequest) String() string { return proto.CompactTextString(m) }
func (*InstitutionWorkListRequest) ProtoMessage()    {}
func (*InstitutionWorkListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{18}
}

func (m *InstitutionWorkListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionWorkListRequest.Unmarshal(m, b)
}
func (m *InstitutionWorkListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionWorkListRequest.Marshal(b, m, deterministic)
}
func (m *InstitutionWorkListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionWorkListRequest.Merge(m, src)
}
func (m *InstitutionWorkListRequest) XXX_Size() int {
	return xxx_messageInfo_InstitutionWorkListRequest.Size(m)
}
func (m *InstitutionWorkListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionWorkListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionWorkListRequest proto.InternalMessageInfo

func (m *InstitutionWorkListRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *InstitutionWorkListRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *InstitutionWorkListRequest) GetPlace() int64 {
	if m != nil {
		return m.Place
	}
	return 0
}

func (m *InstitutionWorkListRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *InstitutionWorkListRequest) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *InstitutionWorkListRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type InstitutionWorkData struct {
	Id                   int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int64              `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string             `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Start                int64              `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64              `protobuf:"varint,5,opt,name=end,proto3" json:"end,omitempty"`
	Level                string             `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	Max                  int64              `protobuf:"varint,7,opt,name=max,proto3" json:"max,omitempty"`
	Now                  int64              `protobuf:"varint,8,opt,name=now,proto3" json:"now,omitempty"`
	Price                int64              `protobuf:"varint,9,opt,name=price,proto3" json:"price,omitempty"`
	Reserve              bool               `protobuf:"varint,10,opt,name=reserve,proto3" json:"reserve,omitempty"`
	UserInfo             string             `protobuf:"bytes,11,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	Desc                 string             `protobuf:"bytes,12,opt,name=desc,proto3" json:"desc,omitempty"`
	Duration             int64              `protobuf:"varint,13,opt,name=duration,proto3" json:"duration,omitempty"`
	Place                *InstitutionSchool `protobuf:"bytes,14,opt,name=place,proto3" json:"place,omitempty"`
	CourseId             int64              `protobuf:"varint,15,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InstitutionWorkData) Reset()         { *m = InstitutionWorkData{} }
func (m *InstitutionWorkData) String() string { return proto.CompactTextString(m) }
func (*InstitutionWorkData) ProtoMessage()    {}
func (*InstitutionWorkData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{19}
}

func (m *InstitutionWorkData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionWorkData.Unmarshal(m, b)
}
func (m *InstitutionWorkData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionWorkData.Marshal(b, m, deterministic)
}
func (m *InstitutionWorkData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionWorkData.Merge(m, src)
}
func (m *InstitutionWorkData) XXX_Size() int {
	return xxx_messageInfo_InstitutionWorkData.Size(m)
}
func (m *InstitutionWorkData) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionWorkData.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionWorkData proto.InternalMessageInfo

func (m *InstitutionWorkData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InstitutionWorkData) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *InstitutionWorkData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstitutionWorkData) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *InstitutionWorkData) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *InstitutionWorkData) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *InstitutionWorkData) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *InstitutionWorkData) GetNow() int64 {
	if m != nil {
		return m.Now
	}
	return 0
}

func (m *InstitutionWorkData) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *InstitutionWorkData) GetReserve() bool {
	if m != nil {
		return m.Reserve
	}
	return false
}

func (m *InstitutionWorkData) GetUserInfo() string {
	if m != nil {
		return m.UserInfo
	}
	return ""
}

func (m *InstitutionWorkData) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *InstitutionWorkData) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *InstitutionWorkData) GetPlace() *InstitutionSchool {
	if m != nil {
		return m.Place
	}
	return nil
}

func (m *InstitutionWorkData) GetCourseId() int64 {
	if m != nil {
		return m.CourseId
	}
	return 0
}

type InstitutionWorkListResponse struct {
	List                 []*InstitutionWorkData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *InstitutionWorkListResponse) Reset()         { *m = InstitutionWorkListResponse{} }
func (m *InstitutionWorkListResponse) String() string { return proto.CompactTextString(m) }
func (*InstitutionWorkListResponse) ProtoMessage()    {}
func (*InstitutionWorkListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{20}
}

func (m *InstitutionWorkListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionWorkListResponse.Unmarshal(m, b)
}
func (m *InstitutionWorkListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionWorkListResponse.Marshal(b, m, deterministic)
}
func (m *InstitutionWorkListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionWorkListResponse.Merge(m, src)
}
func (m *InstitutionWorkListResponse) XXX_Size() int {
	return xxx_messageInfo_InstitutionWorkListResponse.Size(m)
}
func (m *InstitutionWorkListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionWorkListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionWorkListResponse proto.InternalMessageInfo

func (m *InstitutionWorkListResponse) GetList() []*InstitutionWorkData {
	if m != nil {
		return m.List
	}
	return nil
}

type InstitutionWorkOrderRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               int64    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Page                 int64    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	QueryStatus          []int64  `protobuf:"varint,6,rep,packed,name=query_status,json=queryStatus,proto3" json:"query_status,omitempty"`
	OrderId              int64    `protobuf:"varint,7,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstitutionWorkOrderRequest) Reset()         { *m = InstitutionWorkOrderRequest{} }
func (m *InstitutionWorkOrderRequest) String() string { return proto.CompactTextString(m) }
func (*InstitutionWorkOrderRequest) ProtoMessage()    {}
func (*InstitutionWorkOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{21}
}

func (m *InstitutionWorkOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionWorkOrderRequest.Unmarshal(m, b)
}
func (m *InstitutionWorkOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionWorkOrderRequest.Marshal(b, m, deterministic)
}
func (m *InstitutionWorkOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionWorkOrderRequest.Merge(m, src)
}
func (m *InstitutionWorkOrderRequest) XXX_Size() int {
	return xxx_messageInfo_InstitutionWorkOrderRequest.Size(m)
}
func (m *InstitutionWorkOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionWorkOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionWorkOrderRequest proto.InternalMessageInfo

func (m *InstitutionWorkOrderRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InstitutionWorkOrderRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *InstitutionWorkOrderRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *InstitutionWorkOrderRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *InstitutionWorkOrderRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *InstitutionWorkOrderRequest) GetQueryStatus() []int64 {
	if m != nil {
		return m.QueryStatus
	}
	return nil
}

func (m *InstitutionWorkOrderRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type InstitutionWorkOrderData struct {
	WorkId               int64    `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	OrderId              int64    `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Uid                  int64    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               int64    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Num                  int64    `protobuf:"varint,5,opt,name=num,proto3" json:"num,omitempty"`
	Id                   int64    `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstitutionWorkOrderData) Reset()         { *m = InstitutionWorkOrderData{} }
func (m *InstitutionWorkOrderData) String() string { return proto.CompactTextString(m) }
func (*InstitutionWorkOrderData) ProtoMessage()    {}
func (*InstitutionWorkOrderData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{22}
}

func (m *InstitutionWorkOrderData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionWorkOrderData.Unmarshal(m, b)
}
func (m *InstitutionWorkOrderData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionWorkOrderData.Marshal(b, m, deterministic)
}
func (m *InstitutionWorkOrderData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionWorkOrderData.Merge(m, src)
}
func (m *InstitutionWorkOrderData) XXX_Size() int {
	return xxx_messageInfo_InstitutionWorkOrderData.Size(m)
}
func (m *InstitutionWorkOrderData) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionWorkOrderData.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionWorkOrderData proto.InternalMessageInfo

func (m *InstitutionWorkOrderData) GetWorkId() int64 {
	if m != nil {
		return m.WorkId
	}
	return 0
}

func (m *InstitutionWorkOrderData) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *InstitutionWorkOrderData) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *InstitutionWorkOrderData) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *InstitutionWorkOrderData) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *InstitutionWorkOrderData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type InstitutionWorkOrderResponse struct {
	List                 []*InstitutionWorkOrderData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *InstitutionWorkOrderResponse) Reset()         { *m = InstitutionWorkOrderResponse{} }
func (m *InstitutionWorkOrderResponse) String() string { return proto.CompactTextString(m) }
func (*InstitutionWorkOrderResponse) ProtoMessage()    {}
func (*InstitutionWorkOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{23}
}

func (m *InstitutionWorkOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstitutionWorkOrderResponse.Unmarshal(m, b)
}
func (m *InstitutionWorkOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstitutionWorkOrderResponse.Marshal(b, m, deterministic)
}
func (m *InstitutionWorkOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstitutionWorkOrderResponse.Merge(m, src)
}
func (m *InstitutionWorkOrderResponse) XXX_Size() int {
	return xxx_messageInfo_InstitutionWorkOrderResponse.Size(m)
}
func (m *InstitutionWorkOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstitutionWorkOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstitutionWorkOrderResponse proto.InternalMessageInfo

func (m *InstitutionWorkOrderResponse) GetList() []*InstitutionWorkOrderData {
	if m != nil {
		return m.List
	}
	return nil
}

type CancelCoachRequest struct {
	List                 []int64  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelCoachRequest) Reset()         { *m = CancelCoachRequest{} }
func (m *CancelCoachRequest) String() string { return proto.CompactTextString(m) }
func (*CancelCoachRequest) ProtoMessage()    {}
func (*CancelCoachRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b48e38ae49e32d8a, []int{24}
}

func (m *CancelCoachRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelCoachRequest.Unmarshal(m, b)
}
func (m *CancelCoachRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelCoachRequest.Marshal(b, m, deterministic)
}
func (m *CancelCoachRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelCoachRequest.Merge(m, src)
}
func (m *CancelCoachRequest) XXX_Size() int {
	return xxx_messageInfo_CancelCoachRequest.Size(m)
}
func (m *CancelCoachRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelCoachRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelCoachRequest proto.InternalMessageInfo

func (m *CancelCoachRequest) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*InstitutionRequest)(nil), "app.InstitutionRequest")
	proto.RegisterType((*InstitutionData)(nil), "app.InstitutionData")
	proto.RegisterType((*InstitutionResponse)(nil), "app.InstitutionResponse")
	proto.RegisterType((*EditInstitutionRequest)(nil), "app.EditInstitutionRequest")
	proto.RegisterType((*EditInstitutionResponse)(nil), "app.EditInstitutionResponse")
	proto.RegisterType((*InstitutionSchoolRequest)(nil), "app.InstitutionSchoolRequest")
	proto.RegisterType((*InstitutionSchool)(nil), "app.InstitutionSchool")
	proto.RegisterType((*InstitutionCourse)(nil), "app.InstitutionCourse")
	proto.RegisterType((*InstitutionSchoolResponse)(nil), "app.InstitutionSchoolResponse")
	proto.RegisterType((*EditInstitutionSchoolRequest)(nil), "app.EditInstitutionSchoolRequest")
	proto.RegisterType((*InstitutionCourseRequest)(nil), "app.InstitutionCourseRequest")
	proto.RegisterType((*InstitutionCourseResponse)(nil), "app.InstitutionCourseResponse")
	proto.RegisterType((*EditInstitutionCourseRequest)(nil), "app.EditInstitutionCourseRequest")
	proto.RegisterType((*JoinInstitutionCourseRequest)(nil), "app.JoinInstitutionCourseRequest")
	proto.RegisterType((*CoachListRequest)(nil), "app.CoachListRequest")
	proto.RegisterType((*CoachData)(nil), "app.CoachData")
	proto.RegisterType((*CoachListResponse)(nil), "app.CoachListResponse")
	proto.RegisterType((*InstitutionWorkRequest)(nil), "app.InstitutionWorkRequest")
	proto.RegisterType((*InstitutionWorkListRequest)(nil), "app.InstitutionWorkListRequest")
	proto.RegisterType((*InstitutionWorkData)(nil), "app.InstitutionWorkData")
	proto.RegisterType((*InstitutionWorkListResponse)(nil), "app.InstitutionWorkListResponse")
	proto.RegisterType((*InstitutionWorkOrderRequest)(nil), "app.InstitutionWorkOrderRequest")
	proto.RegisterType((*InstitutionWorkOrderData)(nil), "app.InstitutionWorkOrderData")
	proto.RegisterType((*InstitutionWorkOrderResponse)(nil), "app.InstitutionWorkOrderResponse")
	proto.RegisterType((*CancelCoachRequest)(nil), "app.CancelCoachRequest")
}

func init() { proto.RegisterFile("coach.proto", fileDescriptor_b48e38ae49e32d8a) }

var fileDescriptor_b48e38ae49e32d8a = []byte{
	// 1322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4d, 0x6f, 0xe4, 0x34,
	0x18, 0x56, 0x92, 0xf9, 0xca, 0x3b, 0xdd, 0x76, 0x36, 0x74, 0xa7, 0xd9, 0x69, 0x77, 0x99, 0x46,
	0x20, 0x15, 0xb4, 0xaa, 0xc4, 0x72, 0x40, 0x82, 0x03, 0x12, 0x05, 0xc1, 0xc0, 0x0a, 0x44, 0x2a,
	0x01, 0x07, 0xa4, 0x2a, 0x24, 0xee, 0x36, 0xec, 0x4c, 0x92, 0xe6, 0xa3, 0xdd, 0x45, 0xfc, 0x02,
	0x0e, 0x9c, 0xb8, 0xc0, 0x9d, 0x1b, 0xe2, 0xc8, 0x8d, 0x3f, 0xc1, 0x5f, 0xe0, 0x07, 0x70, 0xe2,
	0x8e, 0x6c, 0xbf, 0x71, 0xec, 0xc4, 0xd3, 0x1d, 0x2e, 0x88, 0x9b, 0xed, 0xd8, 0xaf, 0x9f, 0xe7,
	0x7d, 0x9f, 0xc7, 0xf6, 0x0c, 0x8c, 0xc3, 0x34, 0x08, 0x2f, 0x8e, 0xb3, 0x3c, 0x2d, 0x53, 0xc7,
	0x0a, 0xb2, 0x6c, 0x06, 0x51, 0x50, 0x06, 0x7c, 0xc0, 0xfb, 0xce, 0x00, 0x67, 0x91, 0x14, 0x65,
	0x5c, 0x56, 0x65, 0x9c, 0x26, 0x3e, 0xb9, 0xac, 0x48, 0x51, 0x3a, 0x0e, 0xf4, 0xb2, 0xe0, 0x31,
	0x71, 0x8d, 0xb9, 0x71, 0x64, 0xf9, 0xac, 0x4d, 0xc7, 0x8a, 0xf8, 0x1b, 0xe2, 0x9a, 0x7c, 0x8c,
	0xb6, 0x9d, 0x29, 0x0c, 0x8a, 0x32, 0x28, 0xab, 0xc2, 0xb5, 0xd8, 0x28, 0xf6, 0x9c, 0x6d, 0x30,
	0xe3, 0xc8, 0xed, 0xb1, 0x31, 0x33, 0x8e, 0xe8, 0xda, 0x30, 0x8d, 0x88, 0xdb, 0x9f, 0x1b, 0x47,
	0xb6, 0xcf, 0xda, 0xce, 0x04, 0xac, 0x2a, 0x8e, 0xdc, 0x01, 0x9b, 0x44, 0x9b, 0xde, 0x35, 0xec,
	0x48, 0x58, 0xde, 0x0d, 0xca, 0x00, 0x03, 0x19, 0x22, 0x90, 0x0b, 0xc3, 0x20, 0x8a, 0x72, 0x52,
	0x14, 0x0c, 0x87, 0xed, 0xd7, 0x5d, 0xba, 0x45, 0x12, 0xac, 0x08, 0x03, 0x62, 0xfb, 0xac, 0x4d,
	0xc7, 0xe2, 0x30, 0x4d, 0x18, 0x10, 0xdb, 0x67, 0x6d, 0x1d, 0x14, 0xef, 0x6d, 0x78, 0x41, 0x49,
	0x42, 0x91, 0xa5, 0x49, 0x41, 0x9c, 0x23, 0xe8, 0x2d, 0xe3, 0xa2, 0x74, 0x8d, 0xb9, 0x75, 0x34,
	0x7e, 0xb8, 0x7b, 0x1c, 0x64, 0xd9, 0x71, 0x0b, 0xa0, 0xcf, 0x66, 0x78, 0xbf, 0x18, 0x30, 0x7d,
	0x2f, 0x8a, 0x4b, 0x4d, 0x2a, 0xdb, 0x0c, 0x6a, 0x9c, 0xa6, 0x84, 0x53, 0x62, 0x65, 0xa9, 0xac,
	0xa6, 0x30, 0xc8, 0x72, 0x72, 0x1e, 0x3f, 0x45, 0x0e, 0xd8, 0x13, 0xcc, 0xfa, 0x12, 0xb3, 0x09,
	0x58, 0x11, 0x59, 0xb2, 0x84, 0x8e, 0x7c, 0xda, 0xa4, 0xab, 0xc3, 0x9c, 0x04, 0x25, 0x71, 0x87,
	0xbc, 0x3c, 0xbc, 0xe7, 0xbd, 0x02, 0x7b, 0x1d, 0xb4, 0xc8, 0xb9, 0x05, 0xd7, 0xfb, 0x16, 0x5c,
	0x69, 0xda, 0x69, 0x78, 0x91, 0xa6, 0xcb, 0x9a, 0xda, 0x04, 0xac, 0x58, 0x4c, 0xa6, 0x4d, 0x5c,
	0x6d, 0xca, 0x64, 0x99, 0x8e, 0x2c, 0x8d, 0x8e, 0x7a, 0x5a, 0x1d, 0xf5, 0x65, 0x1d, 0x79, 0x7f,
	0x19, 0x70, 0xbb, 0xb3, 0xfd, 0x46, 0x29, 0xdd, 0x85, 0x7e, 0x76, 0x91, 0x26, 0xb5, 0x1e, 0x78,
	0x47, 0x2b, 0x88, 0x5d, 0xe8, 0x17, 0x65, 0x90, 0x97, 0xb8, 0x35, 0xef, 0x50, 0x6e, 0x24, 0x11,
	0xea, 0x24, 0x89, 0x22, 0xbd, 0xa1, 0x5a, 0xa4, 0x63, 0x18, 0x84, 0x69, 0x95, 0x17, 0xc4, 0x1d,
	0x31, 0xa5, 0x4c, 0xdb, 0x4a, 0x39, 0x61, 0x5f, 0x7d, 0x9c, 0xe5, 0xcc, 0x60, 0x14, 0x17, 0xa7,
	0x64, 0x49, 0xc2, 0xd2, 0xb5, 0x59, 0xb5, 0x44, 0xdf, 0xfb, 0x55, 0x65, 0xcc, 0x57, 0x6e, 0xc4,
	0x78, 0x02, 0xd6, 0x2a, 0x78, 0x8a, 0xa9, 0xa6, 0x4d, 0x96, 0x83, 0x3c, 0x0e, 0xeb, 0x54, 0xf3,
	0x0e, 0x1d, 0x5d, 0x92, 0x2b, 0xb2, 0x44, 0xed, 0xf0, 0x8e, 0xb3, 0x0f, 0x76, 0xc1, 0xb2, 0x7b,
	0x26, 0x3c, 0x39, 0xe2, 0x03, 0x8b, 0x88, 0x02, 0x8e, 0xaa, 0x3c, 0xa0, 0x80, 0x50, 0x49, 0xa2,
	0xef, 0xbd, 0x0f, 0x77, 0x35, 0x02, 0x41, 0x35, 0xbd, 0xaa, 0x38, 0xa8, 0x93, 0x17, 0x9c, 0xcd,
	0x3d, 0xf4, 0xb3, 0x09, 0x07, 0x2d, 0x55, 0xaa, 0x72, 0xfb, 0x1f, 0x3a, 0xa9, 0x11, 0xcf, 0x48,
	0x23, 0x1e, 0xbb, 0x11, 0x8f, 0x90, 0x23, 0xc8, 0x72, 0x9c, 0x0a, 0xe1, 0x8c, 0xe7, 0x16, 0x8b,
	0xca, 0xcb, 0xbd, 0x0f, 0x76, 0x16, 0xe4, 0x24, 0x29, 0x69, 0x31, 0xb6, 0x78, 0xc2, 0xf9, 0xc0,
	0x22, 0xf2, 0x7e, 0x34, 0x14, 0x4b, 0xa2, 0xb6, 0xfe, 0x2b, 0x4b, 0xb6, 0x85, 0x62, 0xc9, 0x42,
	0x69, 0x89, 0xa1, 0x86, 0xb6, 0x99, 0x18, 0x70, 0x36, 0x17, 0xc3, 0x9f, 0x46, 0x47, 0x0c, 0x2a,
	0xd1, 0x0d, 0x1d, 0x41, 0xcb, 0x68, 0xe9, 0xca, 0xd8, 0x53, 0xca, 0x88, 0xde, 0xe9, 0x6b, 0xbc,
	0x33, 0xd0, 0x7a, 0x67, 0xd8, 0xf2, 0x4e, 0x53, 0xae, 0x91, 0x5a, 0x2e, 0xc5, 0x3b, 0x76, 0xcb,
	0x3b, 0xdf, 0x1b, 0x70, 0xf0, 0x61, 0x1a, 0x27, 0x1b, 0xb3, 0xc4, 0x3b, 0xd3, 0x14, 0x77, 0x26,
	0xe5, 0x7d, 0x59, 0xc5, 0x25, 0x92, 0x64, 0x6d, 0x26, 0xe9, 0xe4, 0x3c, 0x15, 0xa7, 0x5c, 0x72,
	0x9e, 0x3a, 0x2f, 0xc1, 0xad, 0xb8, 0xd9, 0x65, 0x11, 0x21, 0x57, 0x75, 0xd0, 0xfb, 0x12, 0x26,
	0x27, 0xf4, 0xb9, 0xf0, 0x28, 0x2e, 0xca, 0x7f, 0xfb, 0x16, 0xe0, 0x58, 0x2d, 0x19, 0x6b, 0x2c,
	0x1e, 0x01, 0xb4, 0xe9, 0x5d, 0x80, 0xcd, 0xa2, 0xb3, 0x9b, 0x1d, 0xa9, 0x18, 0x0a, 0x15, 0x06,
	0xdb, 0x94, 0x60, 0xbf, 0x0c, 0xdb, 0x12, 0xc2, 0x33, 0xb1, 0x81, 0x8a, 0xbb, 0xfd, 0xde, 0xf0,
	0xde, 0x80, 0xdb, 0x12, 0x0f, 0xd4, 0x9f, 0xa7, 0xe8, 0x6f, 0x9b, 0xe9, 0x4f, 0xe0, 0x41, 0xdd,
	0xfd, 0x66, 0xc0, 0x54, 0xaa, 0xc6, 0xe7, 0x69, 0xfe, 0xa4, 0xce, 0x83, 0xb0, 0xba, 0xa1, 0xb1,
	0xba, 0xa9, 0x5a, 0x7d, 0x19, 0x84, 0xb5, 0xc3, 0x78, 0x47, 0xb2, 0x7a, 0xad, 0x3c, 0x6e, 0x75,
	0x07, 0x7a, 0x11, 0x29, 0xc2, 0xfa, 0xf8, 0xa1, 0xed, 0xee, 0xcb, 0xa8, 0x56, 0xf2, 0xb0, 0x51,
	0x32, 0x67, 0x3c, 0x12, 0x8c, 0x7f, 0x30, 0x60, 0xd6, 0x02, 0x2e, 0x17, 0xb1, 0x9b, 0x6d, 0x41,
	0xc7, 0x94, 0xe9, 0xe8, 0xc1, 0x23, 0xc9, 0x5e, 0x43, 0x92, 0x6f, 0xdf, 0x67, 0xf6, 0xa7, 0xc5,
	0x6e, 0x4e, 0x8b, 0x81, 0x72, 0x81, 0xff, 0x6d, 0x2a, 0x4f, 0x2b, 0x0a, 0x4b, 0xfb, 0xae, 0xd3,
	0x0a, 0xbb, 0xf3, 0x9e, 0x13, 0x98, 0x7b, 0x9a, 0x12, 0xf4, 0x95, 0x12, 0x70, 0x9b, 0x0e, 0x64,
	0x9b, 0xa2, 0xc9, 0x87, 0x8d, 0xc9, 0x27, 0x60, 0x25, 0xe9, 0x35, 0x66, 0x91, 0x36, 0x1b, 0xdb,
	0xdb, 0xb2, 0xed, 0x5d, 0x18, 0xe6, 0xa4, 0x20, 0xf9, 0x15, 0x3f, 0xbf, 0x47, 0x7e, 0xdd, 0xa5,
	0xd6, 0xaf, 0x0a, 0x92, 0x9f, 0x31, 0xe1, 0x8e, 0xd9, 0x6e, 0x23, 0x3a, 0xb0, 0xa0, 0xe2, 0xad,
	0x6b, 0xbb, 0x25, 0xd5, 0x56, 0x3e, 0x0e, 0x6e, 0xa9, 0xc7, 0x81, 0xf3, 0xa0, 0x4e, 0xfe, 0xf6,
	0xdc, 0xb8, 0xe1, 0xba, 0xc4, 0xa2, 0xec, 0x83, 0xcd, 0x35, 0x44, 0x5d, 0xb1, 0xc3, 0x43, 0xf1,
	0x81, 0x45, 0xe4, 0x7d, 0x04, 0xfb, 0x5a, 0x35, 0xa0, 0x15, 0x1e, 0x28, 0x56, 0x70, 0xdb, 0x1b,
	0xd5, 0x65, 0x42, 0x53, 0xfc, 0x6e, 0x74, 0xa2, 0x7d, 0x92, 0x47, 0x24, 0xdf, 0xfc, 0x94, 0x5a,
	0xf7, 0x3b, 0xa1, 0x3e, 0x5b, 0x7a, 0x9a, 0xb3, 0xa5, 0x2f, 0x9d, 0x2d, 0x87, 0xb0, 0x75, 0x59,
	0x91, 0xfc, 0xd9, 0x99, 0x10, 0x19, 0x15, 0xde, 0x98, 0x8d, 0x9d, 0xf2, 0x50, 0x77, 0x61, 0x94,
	0x52, 0x50, 0x34, 0x1b, 0xbc, 0xc4, 0x43, 0xd6, 0x5f, 0x44, 0xde, 0x4f, 0xea, 0x8d, 0x29, 0xf0,
	0x33, 0x25, 0xee, 0xc1, 0xf0, 0x3a, 0xcd, 0x9f, 0x9c, 0x09, 0x06, 0x03, 0xda, 0x5d, 0x44, 0x4a,
	0x40, 0x53, 0x09, 0x58, 0x13, 0xb4, 0x74, 0x04, 0x7b, 0x0a, 0x41, 0xaa, 0xb0, 0x6a, 0x55, 0x6b,
	0x33, 0xa9, 0x56, 0x98, 0xac, 0x81, 0x30, 0xee, 0xa7, 0x70, 0xa0, 0xcf, 0x2d, 0x96, 0xea, 0x35,
	0xa5, 0x54, 0xf7, 0x74, 0xa5, 0x12, 0x64, 0xb0, 0x5e, 0x47, 0xe0, 0x9c, 0x04, 0x49, 0x48, 0x96,
	0xec, 0x74, 0x93, 0xce, 0x71, 0x11, 0xc8, 0xe2, 0x33, 0x1f, 0xfe, 0x31, 0x84, 0x2d, 0x36, 0xe9,
	0x94, 0xe4, 0x57, 0x54, 0xe9, 0x27, 0xb0, 0xfd, 0x98, 0xc8, 0xb7, 0xae, 0xb3, 0xd7, 0xde, 0x11,
	0xe3, 0xcd, 0xdc, 0xee, 0x07, 0x84, 0xfc, 0x08, 0x76, 0x88, 0x7a, 0x77, 0x3b, 0xfb, 0x6c, 0xb2,
	0xfe, 0x27, 0xd2, 0xec, 0x40, 0xff, 0x11, 0xa3, 0x7d, 0x01, 0x77, 0x88, 0xee, 0x59, 0xe8, 0x1c,
	0xea, 0x96, 0x29, 0x4f, 0xc6, 0xe7, 0x44, 0xfe, 0xb8, 0x13, 0x19, 0x9f, 0xdb, 0xda, 0xc8, 0xca,
	0xcd, 0x3c, 0x73, 0xf8, 0x94, 0x55, 0x56, 0x3e, 0x93, 0x78, 0x8f, 0xf1, 0x69, 0x44, 0x93, 0xeb,
	0xdc, 0x5b, 0xe3, 0x5f, 0x8c, 0x70, 0x7f, 0xdd, 0xe7, 0x26, 0x1a, 0xfa, 0x5b, 0x1f, 0x4d, 0xc5,
	0x73, 0x7f, 0xdd, 0x67, 0x8c, 0xf6, 0x16, 0x00, 0xfb, 0x23, 0x80, 0x07, 0xbb, 0xd3, 0x5c, 0x7e,
	0xd2, 0x2d, 0x31, 0x9b, 0xb6, 0x87, 0x45, 0xa2, 0x6c, 0xe6, 0x11, 0xb6, 0xf6, 0x45, 0x9d, 0x04,
	0xe5, 0x28, 0xf3, 0xf5, 0x13, 0x30, 0xde, 0x07, 0xb0, 0xf3, 0xb5, 0xfa, 0xec, 0xc1, 0x94, 0xdf,
	0xf4, 0x18, 0xd2, 0xa6, 0xfc, 0x4d, 0xf6, 0xde, 0xa7, 0x1b, 0xa0, 0xc4, 0xf4, 0x97, 0xb7, 0x76,
	0xed, 0x3b, 0x00, 0x8c, 0x15, 0x73, 0xb5, 0x33, 0x5f, 0xeb, 0xac, 0x9b, 0x62, 0x7c, 0x06, 0x3b,
	0x4d, 0x0c, 0x9e, 0x9f, 0xe7, 0x07, 0x3a, 0xbc, 0x61, 0x86, 0xe0, 0x35, 0x0e, 0x1b, 0x0b, 0xa3,
	0x09, 0xbb, 0xa6, 0xd6, 0x61, 0xfa, 0x6a, 0xc0, 0xfe, 0xda, 0x79, 0xfd, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xcd, 0xb0, 0x86, 0x10, 0xfa, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoachServiceClient is the client API for CoachService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoachServiceClient interface {
	//检查通道连接
	GetInstitution(ctx context.Context, in *InstitutionRequest, opts ...grpc.CallOption) (*InstitutionResponse, error)
	EditInstitution(ctx context.Context, in *EditInstitutionRequest, opts ...grpc.CallOption) (*EditInstitutionResponse, error)
	EditInstitutionSchool(ctx context.Context, in *EditInstitutionSchoolRequest, opts ...grpc.CallOption) (*EditInstitutionResponse, error)
	EditInstitutionCourse(ctx context.Context, in *EditInstitutionCourseRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	SchoolList(ctx context.Context, in *InstitutionSchoolRequest, opts ...grpc.CallOption) (*InstitutionSchoolResponse, error)
	CourseList(ctx context.Context, in *InstitutionCourseRequest, opts ...grpc.CallOption) (*InstitutionCourseResponse, error)
	CoachList(ctx context.Context, in *CoachListRequest, opts ...grpc.CallOption) (*CoachListResponse, error)
	WorkList(ctx context.Context, in *InstitutionWorkListRequest, opts ...grpc.CallOption) (*InstitutionWorkListResponse, error)
	JoinInstitution(ctx context.Context, in *JoinInstitutionCourseRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	AddWork(ctx context.Context, in *InstitutionWorkRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	WorkOrder(ctx context.Context, in *InstitutionWorkOrderRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	WorkOrderList(ctx context.Context, in *InstitutionWorkOrderRequest, opts ...grpc.CallOption) (*InstitutionWorkOrderResponse, error)
	CancelCoach(ctx context.Context, in *CancelCoachRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type coachServiceClient struct {
	cc *grpc.ClientConn
}

func NewCoachServiceClient(cc *grpc.ClientConn) CoachServiceClient {
	return &coachServiceClient{cc}
}

func (c *coachServiceClient) GetInstitution(ctx context.Context, in *InstitutionRequest, opts ...grpc.CallOption) (*InstitutionResponse, error) {
	out := new(InstitutionResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/getInstitution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) EditInstitution(ctx context.Context, in *EditInstitutionRequest, opts ...grpc.CallOption) (*EditInstitutionResponse, error) {
	out := new(EditInstitutionResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/editInstitution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) EditInstitutionSchool(ctx context.Context, in *EditInstitutionSchoolRequest, opts ...grpc.CallOption) (*EditInstitutionResponse, error) {
	out := new(EditInstitutionResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/editInstitutionSchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) EditInstitutionCourse(ctx context.Context, in *EditInstitutionCourseRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/editInstitutionCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) SchoolList(ctx context.Context, in *InstitutionSchoolRequest, opts ...grpc.CallOption) (*InstitutionSchoolResponse, error) {
	out := new(InstitutionSchoolResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/school_list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) CourseList(ctx context.Context, in *InstitutionCourseRequest, opts ...grpc.CallOption) (*InstitutionCourseResponse, error) {
	out := new(InstitutionCourseResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/course_list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) CoachList(ctx context.Context, in *CoachListRequest, opts ...grpc.CallOption) (*CoachListResponse, error) {
	out := new(CoachListResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/coach_list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) WorkList(ctx context.Context, in *InstitutionWorkListRequest, opts ...grpc.CallOption) (*InstitutionWorkListResponse, error) {
	out := new(InstitutionWorkListResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/work_list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) JoinInstitution(ctx context.Context, in *JoinInstitutionCourseRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/joinInstitution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) AddWork(ctx context.Context, in *InstitutionWorkRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/addWork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) WorkOrder(ctx context.Context, in *InstitutionWorkOrderRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/work_order", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) WorkOrderList(ctx context.Context, in *InstitutionWorkOrderRequest, opts ...grpc.CallOption) (*InstitutionWorkOrderResponse, error) {
	out := new(InstitutionWorkOrderResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/work_order_list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coachServiceClient) CancelCoach(ctx context.Context, in *CancelCoachRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.CoachService/cancelCoach", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoachServiceServer is the server API for CoachService service.
type CoachServiceServer interface {
	//检查通道连接
	GetInstitution(context.Context, *InstitutionRequest) (*InstitutionResponse, error)
	EditInstitution(context.Context, *EditInstitutionRequest) (*EditInstitutionResponse, error)
	EditInstitutionSchool(context.Context, *EditInstitutionSchoolRequest) (*EditInstitutionResponse, error)
	EditInstitutionCourse(context.Context, *EditInstitutionCourseRequest) (*EmptyResponse, error)
	SchoolList(context.Context, *InstitutionSchoolRequest) (*InstitutionSchoolResponse, error)
	CourseList(context.Context, *InstitutionCourseRequest) (*InstitutionCourseResponse, error)
	CoachList(context.Context, *CoachListRequest) (*CoachListResponse, error)
	WorkList(context.Context, *InstitutionWorkListRequest) (*InstitutionWorkListResponse, error)
	JoinInstitution(context.Context, *JoinInstitutionCourseRequest) (*EmptyResponse, error)
	AddWork(context.Context, *InstitutionWorkRequest) (*EmptyResponse, error)
	WorkOrder(context.Context, *InstitutionWorkOrderRequest) (*EmptyResponse, error)
	WorkOrderList(context.Context, *InstitutionWorkOrderRequest) (*InstitutionWorkOrderResponse, error)
	CancelCoach(context.Context, *CancelCoachRequest) (*EmptyResponse, error)
}

// UnimplementedCoachServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCoachServiceServer struct {
}

func (*UnimplementedCoachServiceServer) GetInstitution(ctx context.Context, req *InstitutionRequest) (*InstitutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstitution not implemented")
}
func (*UnimplementedCoachServiceServer) EditInstitution(ctx context.Context, req *EditInstitutionRequest) (*EditInstitutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditInstitution not implemented")
}
func (*UnimplementedCoachServiceServer) EditInstitutionSchool(ctx context.Context, req *EditInstitutionSchoolRequest) (*EditInstitutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditInstitutionSchool not implemented")
}
func (*UnimplementedCoachServiceServer) EditInstitutionCourse(ctx context.Context, req *EditInstitutionCourseRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditInstitutionCourse not implemented")
}
func (*UnimplementedCoachServiceServer) SchoolList(ctx context.Context, req *InstitutionSchoolRequest) (*InstitutionSchoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SchoolList not implemented")
}
func (*UnimplementedCoachServiceServer) CourseList(ctx context.Context, req *InstitutionCourseRequest) (*InstitutionCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CourseList not implemented")
}
func (*UnimplementedCoachServiceServer) CoachList(ctx context.Context, req *CoachListRequest) (*CoachListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoachList not implemented")
}
func (*UnimplementedCoachServiceServer) WorkList(ctx context.Context, req *InstitutionWorkListRequest) (*InstitutionWorkListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkList not implemented")
}
func (*UnimplementedCoachServiceServer) JoinInstitution(ctx context.Context, req *JoinInstitutionCourseRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinInstitution not implemented")
}
func (*UnimplementedCoachServiceServer) AddWork(ctx context.Context, req *InstitutionWorkRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWork not implemented")
}
func (*UnimplementedCoachServiceServer) WorkOrder(ctx context.Context, req *InstitutionWorkOrderRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkOrder not implemented")
}
func (*UnimplementedCoachServiceServer) WorkOrderList(ctx context.Context, req *InstitutionWorkOrderRequest) (*InstitutionWorkOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkOrderList not implemented")
}
func (*UnimplementedCoachServiceServer) CancelCoach(ctx context.Context, req *CancelCoachRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCoach not implemented")
}

func RegisterCoachServiceServer(s *grpc.Server, srv CoachServiceServer) {
	s.RegisterService(&_CoachService_serviceDesc, srv)
}

func _CoachService_GetInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).GetInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/GetInstitution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).GetInstitution(ctx, req.(*InstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_EditInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).EditInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/EditInstitution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).EditInstitution(ctx, req.(*EditInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_EditInstitutionSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditInstitutionSchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).EditInstitutionSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/EditInstitutionSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).EditInstitutionSchool(ctx, req.(*EditInstitutionSchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_EditInstitutionCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditInstitutionCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).EditInstitutionCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/EditInstitutionCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).EditInstitutionCourse(ctx, req.(*EditInstitutionCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_SchoolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstitutionSchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).SchoolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/SchoolList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).SchoolList(ctx, req.(*InstitutionSchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_CourseList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstitutionCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).CourseList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/CourseList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).CourseList(ctx, req.(*InstitutionCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_CoachList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoachListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).CoachList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/CoachList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).CoachList(ctx, req.(*CoachListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_WorkList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstitutionWorkListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).WorkList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/WorkList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).WorkList(ctx, req.(*InstitutionWorkListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_JoinInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinInstitutionCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).JoinInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/JoinInstitution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).JoinInstitution(ctx, req.(*JoinInstitutionCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_AddWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstitutionWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).AddWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/AddWork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).AddWork(ctx, req.(*InstitutionWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_WorkOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstitutionWorkOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).WorkOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/WorkOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).WorkOrder(ctx, req.(*InstitutionWorkOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_WorkOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstitutionWorkOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).WorkOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/WorkOrderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).WorkOrderList(ctx, req.(*InstitutionWorkOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoachService_CancelCoach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCoachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoachServiceServer).CancelCoach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.CoachService/CancelCoach",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoachServiceServer).CancelCoach(ctx, req.(*CancelCoachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CoachService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.CoachService",
	HandlerType: (*CoachServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getInstitution",
			Handler:    _CoachService_GetInstitution_Handler,
		},
		{
			MethodName: "editInstitution",
			Handler:    _CoachService_EditInstitution_Handler,
		},
		{
			MethodName: "editInstitutionSchool",
			Handler:    _CoachService_EditInstitutionSchool_Handler,
		},
		{
			MethodName: "editInstitutionCourse",
			Handler:    _CoachService_EditInstitutionCourse_Handler,
		},
		{
			MethodName: "school_list",
			Handler:    _CoachService_SchoolList_Handler,
		},
		{
			MethodName: "course_list",
			Handler:    _CoachService_CourseList_Handler,
		},
		{
			MethodName: "coach_list",
			Handler:    _CoachService_CoachList_Handler,
		},
		{
			MethodName: "work_list",
			Handler:    _CoachService_WorkList_Handler,
		},
		{
			MethodName: "joinInstitution",
			Handler:    _CoachService_JoinInstitution_Handler,
		},
		{
			MethodName: "addWork",
			Handler:    _CoachService_AddWork_Handler,
		},
		{
			MethodName: "work_order",
			Handler:    _CoachService_WorkOrder_Handler,
		},
		{
			MethodName: "work_order_list",
			Handler:    _CoachService_WorkOrderList_Handler,
		},
		{
			MethodName: "cancelCoach",
			Handler:    _CoachService_CancelCoach_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coach.proto",
}
