// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type TagData struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagData) Reset()         { *m = TagData{} }
func (m *TagData) String() string { return proto.CompactTextString(m) }
func (*TagData) ProtoMessage()    {}
func (*TagData) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *TagData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagData.Unmarshal(m, b)
}
func (m *TagData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagData.Marshal(b, m, deterministic)
}
func (m *TagData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagData.Merge(m, src)
}
func (m *TagData) XXX_Size() int {
	return xxx_messageInfo_TagData.Size(m)
}
func (m *TagData) XXX_DiscardUnknown() {
	xxx_messageInfo_TagData.DiscardUnknown(m)
}

var xxx_messageInfo_TagData proto.InternalMessageInfo

func (m *TagData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TagData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TagData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TagData) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

type GoodSpecificationsInfo struct {
	Id                   int64                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	List                 []*GoodSpecificationsValue `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	CategoryId           int64                      `protobuf:"varint,4,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GoodSpecificationsInfo) Reset()         { *m = GoodSpecificationsInfo{} }
func (m *GoodSpecificationsInfo) String() string { return proto.CompactTextString(m) }
func (*GoodSpecificationsInfo) ProtoMessage()    {}
func (*GoodSpecificationsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *GoodSpecificationsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodSpecificationsInfo.Unmarshal(m, b)
}
func (m *GoodSpecificationsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodSpecificationsInfo.Marshal(b, m, deterministic)
}
func (m *GoodSpecificationsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodSpecificationsInfo.Merge(m, src)
}
func (m *GoodSpecificationsInfo) XXX_Size() int {
	return xxx_messageInfo_GoodSpecificationsInfo.Size(m)
}
func (m *GoodSpecificationsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodSpecificationsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GoodSpecificationsInfo proto.InternalMessageInfo

func (m *GoodSpecificationsInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GoodSpecificationsInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GoodSpecificationsInfo) GetList() []*GoodSpecificationsValue {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GoodSpecificationsInfo) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type GoodSpecificationsValue struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsSelect             bool     `protobuf:"varint,3,opt,name=isSelect,proto3" json:"isSelect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodSpecificationsValue) Reset()         { *m = GoodSpecificationsValue{} }
func (m *GoodSpecificationsValue) String() string { return proto.CompactTextString(m) }
func (*GoodSpecificationsValue) ProtoMessage()    {}
func (*GoodSpecificationsValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *GoodSpecificationsValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodSpecificationsValue.Unmarshal(m, b)
}
func (m *GoodSpecificationsValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodSpecificationsValue.Marshal(b, m, deterministic)
}
func (m *GoodSpecificationsValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodSpecificationsValue.Merge(m, src)
}
func (m *GoodSpecificationsValue) XXX_Size() int {
	return xxx_messageInfo_GoodSpecificationsValue.Size(m)
}
func (m *GoodSpecificationsValue) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodSpecificationsValue.DiscardUnknown(m)
}

var xxx_messageInfo_GoodSpecificationsValue proto.InternalMessageInfo

func (m *GoodSpecificationsValue) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GoodSpecificationsValue) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *GoodSpecificationsValue) GetIsSelect() bool {
	if m != nil {
		return m.IsSelect
	}
	return false
}

type DeliveryData struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DefaultNum           int64    `protobuf:"varint,2,opt,name=default_num,json=defaultNum,proto3" json:"default_num,omitempty"`
	DefaultPrice         int64    `protobuf:"varint,3,opt,name=default_price,json=defaultPrice,proto3" json:"default_price,omitempty"`
	IncreaseNum          int64    `protobuf:"varint,4,opt,name=increase_num,json=increaseNum,proto3" json:"increase_num,omitempty"`
	IncreasePrice        int64    `protobuf:"varint,5,opt,name=increase_price,json=increasePrice,proto3" json:"increase_price,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Type                 int64    `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliveryData) Reset()         { *m = DeliveryData{} }
func (m *DeliveryData) String() string { return proto.CompactTextString(m) }
func (*DeliveryData) ProtoMessage()    {}
func (*DeliveryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5}
}

func (m *DeliveryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryData.Unmarshal(m, b)
}
func (m *DeliveryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryData.Marshal(b, m, deterministic)
}
func (m *DeliveryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryData.Merge(m, src)
}
func (m *DeliveryData) XXX_Size() int {
	return xxx_messageInfo_DeliveryData.Size(m)
}
func (m *DeliveryData) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryData.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryData proto.InternalMessageInfo

func (m *DeliveryData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeliveryData) GetDefaultNum() int64 {
	if m != nil {
		return m.DefaultNum
	}
	return 0
}

func (m *DeliveryData) GetDefaultPrice() int64 {
	if m != nil {
		return m.DefaultPrice
	}
	return 0
}

func (m *DeliveryData) GetIncreaseNum() int64 {
	if m != nil {
		return m.IncreaseNum
	}
	return 0
}

func (m *DeliveryData) GetIncreasePrice() int64 {
	if m != nil {
		return m.IncreasePrice
	}
	return 0
}

func (m *DeliveryData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeliveryData) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type Sku struct {
	SkuId                int64        `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SkuNumber            string       `protobuf:"bytes,2,opt,name=sku_number,json=skuNumber,proto3" json:"sku_number,omitempty"`
	SkuName              string       `protobuf:"bytes,3,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	Price                int64        `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	AgreementPrice       int64        `protobuf:"varint,5,opt,name=agreement_price,json=agreementPrice,proto3" json:"agreement_price,omitempty"`
	CostPrice            int64        `protobuf:"varint,6,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	MemberPrice          int64        `protobuf:"varint,7,opt,name=member_price,json=memberPrice,proto3" json:"member_price,omitempty"`
	Stock                int64        `protobuf:"varint,8,opt,name=stock,proto3" json:"stock,omitempty"`
	Sales                int64        `protobuf:"varint,9,opt,name=sales,proto3" json:"sales,omitempty"`
	Status               int64        `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Options              []*SkuOption `protobuf:"bytes,11,rep,name=options,proto3" json:"options,omitempty"`
	IsDel                bool         `protobuf:"varint,12,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Sku) Reset()         { *m = Sku{} }
func (m *Sku) String() string { return proto.CompactTextString(m) }
func (*Sku) ProtoMessage()    {}
func (*Sku) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6}
}

func (m *Sku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sku.Unmarshal(m, b)
}
func (m *Sku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sku.Marshal(b, m, deterministic)
}
func (m *Sku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sku.Merge(m, src)
}
func (m *Sku) XXX_Size() int {
	return xxx_messageInfo_Sku.Size(m)
}
func (m *Sku) XXX_DiscardUnknown() {
	xxx_messageInfo_Sku.DiscardUnknown(m)
}

var xxx_messageInfo_Sku proto.InternalMessageInfo

func (m *Sku) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *Sku) GetSkuNumber() string {
	if m != nil {
		return m.SkuNumber
	}
	return ""
}

func (m *Sku) GetSkuName() string {
	if m != nil {
		return m.SkuName
	}
	return ""
}

func (m *Sku) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Sku) GetAgreementPrice() int64 {
	if m != nil {
		return m.AgreementPrice
	}
	return 0
}

func (m *Sku) GetCostPrice() int64 {
	if m != nil {
		return m.CostPrice
	}
	return 0
}

func (m *Sku) GetMemberPrice() int64 {
	if m != nil {
		return m.MemberPrice
	}
	return 0
}

func (m *Sku) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *Sku) GetSales() int64 {
	if m != nil {
		return m.Sales
	}
	return 0
}

func (m *Sku) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Sku) GetOptions() []*SkuOption {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Sku) GetIsDel() bool {
	if m != nil {
		return m.IsDel
	}
	return false
}

type SkuOption struct {
	OptionId             int64    `protobuf:"varint,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	OptionValue          string   `protobuf:"bytes,2,opt,name=option_value,json=optionValue,proto3" json:"option_value,omitempty"`
	OptionValueId        int64    `protobuf:"varint,3,opt,name=option_value_id,json=optionValueId,proto3" json:"option_value_id,omitempty"`
	Uuid                 string   `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SpuId                int64    `protobuf:"varint,5,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkuOption) Reset()         { *m = SkuOption{} }
func (m *SkuOption) String() string { return proto.CompactTextString(m) }
func (*SkuOption) ProtoMessage()    {}
func (*SkuOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{7}
}

func (m *SkuOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkuOption.Unmarshal(m, b)
}
func (m *SkuOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkuOption.Marshal(b, m, deterministic)
}
func (m *SkuOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkuOption.Merge(m, src)
}
func (m *SkuOption) XXX_Size() int {
	return xxx_messageInfo_SkuOption.Size(m)
}
func (m *SkuOption) XXX_DiscardUnknown() {
	xxx_messageInfo_SkuOption.DiscardUnknown(m)
}

var xxx_messageInfo_SkuOption proto.InternalMessageInfo

func (m *SkuOption) GetOptionId() int64 {
	if m != nil {
		return m.OptionId
	}
	return 0
}

func (m *SkuOption) GetOptionValue() string {
	if m != nil {
		return m.OptionValue
	}
	return ""
}

func (m *SkuOption) GetOptionValueId() int64 {
	if m != nil {
		return m.OptionValueId
	}
	return 0
}

func (m *SkuOption) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SkuOption) GetSpuId() int64 {
	if m != nil {
		return m.SpuId
	}
	return 0
}

type PhotoInfo struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhotoInfo) Reset()         { *m = PhotoInfo{} }
func (m *PhotoInfo) String() string { return proto.CompactTextString(m) }
func (*PhotoInfo) ProtoMessage()    {}
func (*PhotoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{8}
}

func (m *PhotoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoInfo.Unmarshal(m, b)
}
func (m *PhotoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoInfo.Marshal(b, m, deterministic)
}
func (m *PhotoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoInfo.Merge(m, src)
}
func (m *PhotoInfo) XXX_Size() int {
	return xxx_messageInfo_PhotoInfo.Size(m)
}
func (m *PhotoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoInfo proto.InternalMessageInfo

func (m *PhotoInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PhotoInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Spu struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Normal               *SpuSku  `protobuf:"bytes,2,opt,name=normal,proto3" json:"normal,omitempty"`
	Member               *SpuSku  `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Photo                string   `protobuf:"bytes,5,opt,name=photo,proto3" json:"photo,omitempty"`
	Sales                int64    `protobuf:"varint,6,opt,name=sales,proto3" json:"sales,omitempty"`
	Stock                int64    `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	Status               int64    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	SaleStatus           bool     `protobuf:"varint,9,opt,name=sale_status,json=saleStatus,proto3" json:"sale_status,omitempty"`
	CreateTime           int64    `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ModifyTime           int64    `protobuf:"varint,11,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	BusinessId           int64    `protobuf:"varint,12,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	BrandName            string   `protobuf:"bytes,13,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	CategoryId           int64    `protobuf:"varint,14,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName         string   `protobuf:"bytes,15,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Spu) Reset()         { *m = Spu{} }
func (m *Spu) String() string { return proto.CompactTextString(m) }
func (*Spu) ProtoMessage()    {}
func (*Spu) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{9}
}

func (m *Spu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spu.Unmarshal(m, b)
}
func (m *Spu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spu.Marshal(b, m, deterministic)
}
func (m *Spu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spu.Merge(m, src)
}
func (m *Spu) XXX_Size() int {
	return xxx_messageInfo_Spu.Size(m)
}
func (m *Spu) XXX_DiscardUnknown() {
	xxx_messageInfo_Spu.DiscardUnknown(m)
}

var xxx_messageInfo_Spu proto.InternalMessageInfo

func (m *Spu) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Spu) GetNormal() *SpuSku {
	if m != nil {
		return m.Normal
	}
	return nil
}

func (m *Spu) GetMember() *SpuSku {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *Spu) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Spu) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *Spu) GetSales() int64 {
	if m != nil {
		return m.Sales
	}
	return 0
}

func (m *Spu) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *Spu) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Spu) GetSaleStatus() bool {
	if m != nil {
		return m.SaleStatus
	}
	return false
}

func (m *Spu) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Spu) GetModifyTime() int64 {
	if m != nil {
		return m.ModifyTime
	}
	return 0
}

func (m *Spu) GetBusinessId() int64 {
	if m != nil {
		return m.BusinessId
	}
	return 0
}

func (m *Spu) GetBrandName() string {
	if m != nil {
		return m.BrandName
	}
	return ""
}

func (m *Spu) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Spu) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

type SpuSku struct {
	SkuId                int64    `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	CostPrice            int64    `protobuf:"varint,3,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	MemberPrice          int64    `protobuf:"varint,4,opt,name=member_price,json=memberPrice,proto3" json:"member_price,omitempty"`
	AgreementPrice       int64    `protobuf:"varint,5,opt,name=agreement_price,json=agreementPrice,proto3" json:"agreement_price,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	Photo                string   `protobuf:"bytes,8,opt,name=photo,proto3" json:"photo,omitempty"`
	Num                  int64    `protobuf:"varint,9,opt,name=num,proto3" json:"num,omitempty"`
	SpuId                int64    `protobuf:"varint,10,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	SpuName              string   `protobuf:"bytes,11,opt,name=spu_name,json=spuName,proto3" json:"spu_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpuSku) Reset()         { *m = SpuSku{} }
func (m *SpuSku) String() string { return proto.CompactTextString(m) }
func (*SpuSku) ProtoMessage()    {}
func (*SpuSku) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{10}
}

func (m *SpuSku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpuSku.Unmarshal(m, b)
}
func (m *SpuSku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpuSku.Marshal(b, m, deterministic)
}
func (m *SpuSku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpuSku.Merge(m, src)
}
func (m *SpuSku) XXX_Size() int {
	return xxx_messageInfo_SpuSku.Size(m)
}
func (m *SpuSku) XXX_DiscardUnknown() {
	xxx_messageInfo_SpuSku.DiscardUnknown(m)
}

var xxx_messageInfo_SpuSku proto.InternalMessageInfo

func (m *SpuSku) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *SpuSku) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SpuSku) GetCostPrice() int64 {
	if m != nil {
		return m.CostPrice
	}
	return 0
}

func (m *SpuSku) GetMemberPrice() int64 {
	if m != nil {
		return m.MemberPrice
	}
	return 0
}

func (m *SpuSku) GetAgreementPrice() int64 {
	if m != nil {
		return m.AgreementPrice
	}
	return 0
}

func (m *SpuSku) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SpuSku) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SpuSku) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *SpuSku) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *SpuSku) GetSpuId() int64 {
	if m != nil {
		return m.SpuId
	}
	return 0
}

func (m *SpuSku) GetSpuName() string {
	if m != nil {
		return m.SpuName
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "app.EmptyRequest")
	proto.RegisterType((*EmptyResponse)(nil), "app.EmptyResponse")
	proto.RegisterType((*TagData)(nil), "app.TagData")
	proto.RegisterType((*GoodSpecificationsInfo)(nil), "app.good_specifications_info")
	proto.RegisterType((*GoodSpecificationsValue)(nil), "app.good_specifications_value")
	proto.RegisterType((*DeliveryData)(nil), "app.DeliveryData")
	proto.RegisterType((*Sku)(nil), "app.Sku")
	proto.RegisterType((*SkuOption)(nil), "app.SkuOption")
	proto.RegisterType((*PhotoInfo)(nil), "app.PhotoInfo")
	proto.RegisterType((*Spu)(nil), "app.Spu")
	proto.RegisterType((*SpuSku)(nil), "app.SpuSku")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 831 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4b, 0x6e, 0xe4, 0x36,
	0x10, 0x45, 0xb7, 0xfa, 0xa7, 0x52, 0x77, 0x7b, 0x40, 0x38, 0x81, 0x26, 0xc1, 0x7c, 0xa2, 0x41,
	0x12, 0xaf, 0x1c, 0xc0, 0xb9, 0x82, 0xb3, 0xe8, 0xcd, 0x64, 0xa0, 0x1e, 0x64, 0x2b, 0xd0, 0x12,
	0xed, 0x10, 0xfa, 0x90, 0x11, 0x49, 0x03, 0x7d, 0x8d, 0x1c, 0x20, 0xc8, 0x29, 0x72, 0x94, 0xac,
	0x72, 0x98, 0xa0, 0x8a, 0x94, 0x2c, 0x8f, 0x3d, 0x48, 0x76, 0xac, 0xc7, 0xa7, 0x62, 0x7d, 0x5e,
	0x95, 0x00, 0x2a, 0x6e, 0xf9, 0xa5, 0xee, 0x95, 0x55, 0x2c, 0xe2, 0x5a, 0x67, 0x7b, 0xd8, 0xfe,
	0xd4, 0x6a, 0x7b, 0xca, 0xc5, 0x6f, 0x4e, 0x18, 0x9b, 0x9d, 0xc1, 0x2e, 0xd8, 0x46, 0xab, 0xce,
	0x88, 0xac, 0x80, 0xf5, 0x47, 0x7e, 0x77, 0xcd, 0x2d, 0x67, 0x7b, 0x98, 0xcb, 0x2a, 0x9d, 0xbd,
	0x9d, 0x5d, 0x44, 0xf9, 0x5c, 0x56, 0xec, 0x1c, 0x96, 0x56, 0xda, 0x46, 0xa4, 0xf3, 0xb7, 0xb3,
	0x8b, 0x38, 0xf7, 0x06, 0x4b, 0x61, 0x5d, 0xaa, 0xce, 0x8a, 0xce, 0xa6, 0x11, 0xe1, 0x83, 0x89,
	0xfc, 0x52, 0xdd, 0x8b, 0x3e, 0x5d, 0x78, 0x3e, 0x19, 0xd9, 0xef, 0x33, 0x48, 0xef, 0x94, 0xaa,
	0x0a, 0xa3, 0x45, 0x29, 0x6f, 0x65, 0xc9, 0xad, 0x54, 0x9d, 0x29, 0x64, 0x77, 0xab, 0x9e, 0x3c,
	0xc9, 0x60, 0xd1, 0xf1, 0x76, 0x78, 0x91, 0xce, 0xec, 0x0a, 0x16, 0x8d, 0x34, 0xf8, 0x5a, 0x74,
	0x91, 0x5c, 0xbd, 0xbe, 0xe4, 0x5a, 0x5f, 0x3e, 0xe7, 0xf0, 0x9e, 0x37, 0x4e, 0xe4, 0xc4, 0x65,
	0xaf, 0x01, 0x4a, 0x6e, 0xc5, 0x9d, 0xea, 0x4f, 0x87, 0x8a, 0xe2, 0x89, 0xf2, 0x09, 0x92, 0x71,
	0x78, 0xf9, 0x59, 0x17, 0x4f, 0x82, 0x9a, 0x64, 0x3c, 0x7f, 0x9c, 0xf1, 0x57, 0xb0, 0x91, 0xe6,
	0x28, 0x1a, 0x51, 0xfa, 0x62, 0x6c, 0xf2, 0xd1, 0xce, 0xfe, 0x9e, 0xc1, 0xf6, 0x5a, 0x34, 0xf2,
	0x5e, 0xf4, 0xa7, 0x67, 0xcb, 0xfb, 0x06, 0x92, 0x4a, 0xdc, 0x72, 0xd7, 0xd8, 0xa2, 0x73, 0x2d,
	0xb9, 0x8e, 0x72, 0x08, 0xd0, 0x7b, 0xd7, 0xb2, 0x77, 0xb0, 0x1b, 0x08, 0xba, 0x97, 0xa5, 0xa0,
	0x27, 0xa2, 0x7c, 0x1b, 0xc0, 0x0f, 0x88, 0xb1, 0x6f, 0x60, 0x2b, 0xbb, 0xb2, 0x17, 0xdc, 0x08,
	0x72, 0xe3, 0x73, 0x4d, 0x06, 0x0c, 0xfd, 0x7c, 0x0b, 0xfb, 0x91, 0xe2, 0x1d, 0x2d, 0x89, 0xb4,
	0x1b, 0x50, 0xef, 0x69, 0xa8, 0xfd, 0x6a, 0x52, 0x7b, 0x06, 0x0b, 0x7b, 0xd2, 0x22, 0x5d, 0xd3,
	0x07, 0x74, 0xce, 0xfe, 0x99, 0x43, 0x74, 0xac, 0x1d, 0xfb, 0x02, 0x56, 0xa6, 0x76, 0xc5, 0x98,
	0xd3, 0xd2, 0xd4, 0xee, 0x50, 0xb1, 0x57, 0x00, 0x08, 0x77, 0xae, 0xbd, 0x11, 0x7d, 0x28, 0x58,
	0x6c, 0x6a, 0xf7, 0x9e, 0x00, 0xf6, 0x12, 0x36, 0x74, 0x8d, 0x2f, 0x05, 0xfd, 0xe0, 0x25, 0x3e,
	0x76, 0x0e, 0x4b, 0x1f, 0x9e, 0xcf, 0xc1, 0x1b, 0xec, 0x7b, 0x38, 0xe3, 0x77, 0xbd, 0x10, 0xad,
	0xe8, 0xec, 0xa3, 0xf0, 0xf7, 0x23, 0xec, 0xe3, 0x7f, 0x05, 0x50, 0x2a, 0x33, 0x70, 0x56, 0xc4,
	0x89, 0x11, 0x19, 0x0b, 0xd5, 0x0a, 0x0c, 0x21, 0x10, 0x7c, 0x4a, 0x89, 0xc7, 0x3c, 0xe5, 0x1c,
	0x96, 0xc6, 0xaa, 0xb2, 0x4e, 0x37, 0x21, 0x21, 0x34, 0x08, 0xe5, 0x8d, 0x30, 0x69, 0x1c, 0x50,
	0x34, 0xd8, 0x97, 0xb0, 0x32, 0x96, 0x5b, 0x67, 0x52, 0x20, 0x38, 0x58, 0xec, 0x02, 0xd6, 0x4a,
	0x93, 0x9a, 0xd2, 0x84, 0x04, 0xbb, 0x27, 0xc1, 0x1e, 0x6b, 0xf7, 0x33, 0xc1, 0xf9, 0x70, 0x8d,
	0xf5, 0x93, 0xa6, 0xa8, 0x44, 0x93, 0x6e, 0x49, 0x3a, 0x4b, 0x69, 0xae, 0x45, 0x93, 0xfd, 0x31,
	0x83, 0x78, 0x64, 0xb3, 0xaf, 0x21, 0xf6, 0xfc, 0x87, 0x3a, 0x6f, 0x3c, 0x70, 0xa8, 0x30, 0xa5,
	0x70, 0x49, 0xc2, 0x0d, 0xc5, 0x4e, 0x3c, 0xf6, 0x0b, 0x69, 0xf9, 0x3b, 0x38, 0x9b, 0x52, 0xd0,
	0x8b, 0x57, 0xd1, 0x6e, 0xc2, 0x3a, 0xd0, 0xe0, 0x39, 0x27, 0xab, 0x30, 0xba, 0x74, 0xa6, 0x06,
	0x6b, 0x6a, 0xf0, 0x32, 0x64, 0xae, 0xdd, 0xa1, 0xca, 0x7e, 0x80, 0xf8, 0xc3, 0xaf, 0xca, 0xaa,
	0x03, 0x0e, 0xf0, 0x0b, 0x88, 0x6a, 0x71, 0xa2, 0xc8, 0xe2, 0x1c, 0x8f, 0x88, 0xb8, 0xbe, 0x09,
	0xb1, 0xe0, 0x31, 0xfb, 0x2b, 0x82, 0xe8, 0xa8, 0xdd, 0x93, 0x01, 0x78, 0x07, 0xab, 0x4e, 0xf5,
	0x2d, 0xf7, 0xe4, 0xe4, 0x2a, 0xf1, 0x95, 0xd2, 0xee, 0x58, 0xbb, 0x3c, 0x5c, 0x21, 0xc9, 0xb7,
	0x88, 0xe2, 0xfe, 0x94, 0xe4, 0xaf, 0x46, 0xe9, 0x2e, 0x26, 0xd2, 0x45, 0x35, 0x61, 0x98, 0x14,
	0x7c, 0x9c, 0x7b, 0xe3, 0xa1, 0x99, 0xab, 0x69, 0x33, 0xc7, 0xc6, 0xaf, 0xa7, 0x8d, 0x7f, 0x68,
	0xf1, 0xe6, 0x51, 0x8b, 0xdf, 0x40, 0x82, 0x9f, 0x15, 0xe1, 0x32, 0xa6, 0xee, 0x01, 0x42, 0xc7,
	0x91, 0x80, 0x83, 0x65, 0x45, 0x61, 0x65, 0x2b, 0x82, 0x40, 0xc0, 0x43, 0x1f, 0x65, 0x2b, 0x90,
	0xd0, 0xaa, 0x4a, 0xde, 0x9e, 0x3c, 0x21, 0xf1, 0x04, 0x0f, 0x0d, 0x84, 0x1b, 0x67, 0x64, 0x27,
	0x8c, 0xc1, 0xfa, 0x6f, 0x3d, 0x61, 0x80, 0xfc, 0x94, 0xdd, 0xf4, 0xbc, 0xab, 0xfc, 0x20, 0xed,
	0xfc, 0x94, 0x11, 0x42, 0xa3, 0x84, 0x11, 0x84, 0x6d, 0x87, 0xdf, 0xef, 0x3f, 0x5d, 0x80, 0xb8,
	0x5b, 0x46, 0x02, 0xb9, 0x38, 0x23, 0x17, 0xdb, 0x01, 0x44, 0x2f, 0xd9, 0x9f, 0x73, 0x58, 0xf9,
	0x4a, 0x7f, 0x6e, 0xd8, 0xc7, 0x91, 0x9d, 0x4f, 0x47, 0xf6, 0xf1, 0x24, 0x46, 0xff, 0x35, 0x89,
	0x8b, 0xa7, 0x93, 0xf8, 0xbf, 0x87, 0xfe, 0xb9, 0xa5, 0x15, 0x34, 0xb9, 0x7e, 0xd0, 0xe4, 0xa8,
	0x85, 0xcd, 0x54, 0x0b, 0x2f, 0x20, 0xc2, 0x8d, 0xe9, 0xc7, 0x1a, 0x8f, 0x13, 0xc5, 0xc3, 0x44,
	0xf1, 0xb4, 0xb3, 0x74, 0xd8, 0x59, 0x49, 0xd8, 0x59, 0x9a, 0x76, 0xd6, 0xcd, 0x8a, 0xfe, 0xb5,
	0x3f, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x16, 0xdd, 0x17, 0x79, 0x07, 0x00, 0x00,
}
