// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qiniu_service.proto

package app

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadBytesReq struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadBytesReq) Reset()         { *m = UploadBytesReq{} }
func (m *UploadBytesReq) String() string { return proto.CompactTextString(m) }
func (*UploadBytesReq) ProtoMessage()    {}
func (*UploadBytesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a2cd21b502002ee, []int{0}
}

func (m *UploadBytesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadBytesReq.Unmarshal(m, b)
}
func (m *UploadBytesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadBytesReq.Marshal(b, m, deterministic)
}
func (m *UploadBytesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadBytesReq.Merge(m, src)
}
func (m *UploadBytesReq) XXX_Size() int {
	return xxx_messageInfo_UploadBytesReq.Size(m)
}
func (m *UploadBytesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadBytesReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadBytesReq proto.InternalMessageInfo

func (m *UploadBytesReq) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *UploadBytesReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UploadBytesReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadBytesRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadBytesRsp) Reset()         { *m = UploadBytesRsp{} }
func (m *UploadBytesRsp) String() string { return proto.CompactTextString(m) }
func (*UploadBytesRsp) ProtoMessage()    {}
func (*UploadBytesRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a2cd21b502002ee, []int{1}
}

func (m *UploadBytesRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadBytesRsp.Unmarshal(m, b)
}
func (m *UploadBytesRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadBytesRsp.Marshal(b, m, deterministic)
}
func (m *UploadBytesRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadBytesRsp.Merge(m, src)
}
func (m *UploadBytesRsp) XXX_Size() int {
	return xxx_messageInfo_UploadBytesRsp.Size(m)
}
func (m *UploadBytesRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadBytesRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadBytesRsp proto.InternalMessageInfo

type QiniuServiceRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	IsBase64             bool     `protobuf:"varint,2,opt,name=is_base64,json=isBase64,proto3" json:"is_base64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QiniuServiceRequest) Reset()         { *m = QiniuServiceRequest{} }
func (m *QiniuServiceRequest) String() string { return proto.CompactTextString(m) }
func (*QiniuServiceRequest) ProtoMessage()    {}
func (*QiniuServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a2cd21b502002ee, []int{2}
}

func (m *QiniuServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QiniuServiceRequest.Unmarshal(m, b)
}
func (m *QiniuServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QiniuServiceRequest.Marshal(b, m, deterministic)
}
func (m *QiniuServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QiniuServiceRequest.Merge(m, src)
}
func (m *QiniuServiceRequest) XXX_Size() int {
	return xxx_messageInfo_QiniuServiceRequest.Size(m)
}
func (m *QiniuServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QiniuServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QiniuServiceRequest proto.InternalMessageInfo

func (m *QiniuServiceRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *QiniuServiceRequest) GetIsBase64() bool {
	if m != nil {
		return m.IsBase64
	}
	return false
}

type QiniuServiceResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UploadHost           string   `protobuf:"bytes,2,opt,name=upload_host,json=uploadHost,proto3" json:"upload_host,omitempty"`
	Base64UploadHost     string   `protobuf:"bytes,3,opt,name=base64_upload_host,json=base64UploadHost,proto3" json:"base64_upload_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QiniuServiceResponse) Reset()         { *m = QiniuServiceResponse{} }
func (m *QiniuServiceResponse) String() string { return proto.CompactTextString(m) }
func (*QiniuServiceResponse) ProtoMessage()    {}
func (*QiniuServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a2cd21b502002ee, []int{3}
}

func (m *QiniuServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QiniuServiceResponse.Unmarshal(m, b)
}
func (m *QiniuServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QiniuServiceResponse.Marshal(b, m, deterministic)
}
func (m *QiniuServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QiniuServiceResponse.Merge(m, src)
}
func (m *QiniuServiceResponse) XXX_Size() int {
	return xxx_messageInfo_QiniuServiceResponse.Size(m)
}
func (m *QiniuServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QiniuServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QiniuServiceResponse proto.InternalMessageInfo

func (m *QiniuServiceResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *QiniuServiceResponse) GetUploadHost() string {
	if m != nil {
		return m.UploadHost
	}
	return ""
}

func (m *QiniuServiceResponse) GetBase64UploadHost() string {
	if m != nil {
		return m.Base64UploadHost
	}
	return ""
}

type GetVideoInfoRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Prefix               string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoInfoRequest) Reset()         { *m = GetVideoInfoRequest{} }
func (m *GetVideoInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetVideoInfoRequest) ProtoMessage()    {}
func (*GetVideoInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a2cd21b502002ee, []int{4}
}

func (m *GetVideoInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoInfoRequest.Unmarshal(m, b)
}
func (m *GetVideoInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetVideoInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoInfoRequest.Merge(m, src)
}
func (m *GetVideoInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetVideoInfoRequest.Size(m)
}
func (m *GetVideoInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoInfoRequest proto.InternalMessageInfo

func (m *GetVideoInfoRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetVideoInfoRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

type VideoInfoResponse struct {
	Cover                string   `protobuf:"bytes,1,opt,name=cover,proto3" json:"cover,omitempty"`
	CoverPrefix          string   `protobuf:"bytes,2,opt,name=cover_prefix,json=coverPrefix,proto3" json:"cover_prefix,omitempty"`
	Duration             int64    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoInfoResponse) Reset()         { *m = VideoInfoResponse{} }
func (m *VideoInfoResponse) String() string { return proto.CompactTextString(m) }
func (*VideoInfoResponse) ProtoMessage()    {}
func (*VideoInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a2cd21b502002ee, []int{5}
}

func (m *VideoInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoInfoResponse.Unmarshal(m, b)
}
func (m *VideoInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoInfoResponse.Marshal(b, m, deterministic)
}
func (m *VideoInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoInfoResponse.Merge(m, src)
}
func (m *VideoInfoResponse) XXX_Size() int {
	return xxx_messageInfo_VideoInfoResponse.Size(m)
}
func (m *VideoInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VideoInfoResponse proto.InternalMessageInfo

func (m *VideoInfoResponse) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *VideoInfoResponse) GetCoverPrefix() string {
	if m != nil {
		return m.CoverPrefix
	}
	return ""
}

func (m *VideoInfoResponse) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type WordInspectRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WordInspectRequest) Reset()         { *m = WordInspectRequest{} }
func (m *WordInspectRequest) String() string { return proto.CompactTextString(m) }
func (*WordInspectRequest) ProtoMessage()    {}
func (*WordInspectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a2cd21b502002ee, []int{6}
}

func (m *WordInspectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WordInspectRequest.Unmarshal(m, b)
}
func (m *WordInspectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WordInspectRequest.Marshal(b, m, deterministic)
}
func (m *WordInspectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WordInspectRequest.Merge(m, src)
}
func (m *WordInspectRequest) XXX_Size() int {
	return xxx_messageInfo_WordInspectRequest.Size(m)
}
func (m *WordInspectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WordInspectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WordInspectRequest proto.InternalMessageInfo

func (m *WordInspectRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type WordInspectResponse struct {
	Type                 int64    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WordInspectResponse) Reset()         { *m = WordInspectResponse{} }
func (m *WordInspectResponse) String() string { return proto.CompactTextString(m) }
func (*WordInspectResponse) ProtoMessage()    {}
func (*WordInspectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a2cd21b502002ee, []int{7}
}

func (m *WordInspectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WordInspectResponse.Unmarshal(m, b)
}
func (m *WordInspectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WordInspectResponse.Marshal(b, m, deterministic)
}
func (m *WordInspectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WordInspectResponse.Merge(m, src)
}
func (m *WordInspectResponse) XXX_Size() int {
	return xxx_messageInfo_WordInspectResponse.Size(m)
}
func (m *WordInspectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WordInspectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WordInspectResponse proto.InternalMessageInfo

func (m *WordInspectResponse) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*UploadBytesReq)(nil), "app.uploadBytesReq")
	proto.RegisterType((*UploadBytesRsp)(nil), "app.uploadBytesRsp")
	proto.RegisterType((*QiniuServiceRequest)(nil), "app.QiniuServiceRequest")
	proto.RegisterType((*QiniuServiceResponse)(nil), "app.QiniuServiceResponse")
	proto.RegisterType((*GetVideoInfoRequest)(nil), "app.GetVideoInfoRequest")
	proto.RegisterType((*VideoInfoResponse)(nil), "app.VideoInfoResponse")
	proto.RegisterType((*WordInspectRequest)(nil), "app.WordInspectRequest")
	proto.RegisterType((*WordInspectResponse)(nil), "app.WordInspectResponse")
}

func init() { proto.RegisterFile("qiniu_service.proto", fileDescriptor_4a2cd21b502002ee) }

var fileDescriptor_4a2cd21b502002ee = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x55, 0xea, 0x52, 0x92, 0x49, 0x84, 0xc2, 0xb8, 0x2a, 0xc6, 0x1c, 0x28, 0x7b, 0x2a, 0x12,
	0xca, 0x01, 0x10, 0x1c, 0x89, 0x7a, 0x81, 0x72, 0x40, 0x60, 0x04, 0x1c, 0x2d, 0xc7, 0x9e, 0xb6,
	0xab, 0x54, 0xbb, 0x1b, 0xef, 0xba, 0x10, 0xf1, 0x0d, 0xfc, 0x33, 0xca, 0xec, 0xba, 0x89, 0xe5,
	0xf4, 0x36, 0x6f, 0xe6, 0x79, 0xde, 0x9b, 0x99, 0x35, 0xc4, 0x2b, 0xa9, 0x64, 0x93, 0x5b, 0xaa,
	0x6f, 0x65, 0x49, 0x33, 0x53, 0x6b, 0xa7, 0x31, 0x2a, 0x8c, 0x11, 0x5f, 0xe0, 0x51, 0x63, 0x6e,
	0x74, 0x51, 0x9d, 0xaf, 0x1d, 0xd9, 0x8c, 0x56, 0x78, 0x02, 0x47, 0x8b, 0xa6, 0x5c, 0x92, 0x4b,
	0x06, 0xa7, 0x83, 0xb3, 0x51, 0x16, 0x10, 0x4e, 0x21, 0x5a, 0xd2, 0x3a, 0x39, 0xe0, 0xe4, 0x26,
	0x44, 0x84, 0xc3, 0xaa, 0x70, 0x45, 0x12, 0x9d, 0x0e, 0xce, 0x26, 0x19, 0xc7, 0x62, 0xda, 0xed,
	0x67, 0x8d, 0xf8, 0x0c, 0xf1, 0xb7, 0x8d, 0xfa, 0x77, 0x2f, 0x9e, 0xd1, 0xaa, 0x21, 0xeb, 0xee,
	0x95, 0x79, 0x06, 0x23, 0x69, 0xf3, 0x45, 0x61, 0xe9, 0xdd, 0x5b, 0x16, 0x1b, 0x66, 0x43, 0x69,
	0xcf, 0x19, 0x8b, 0xbf, 0x70, 0xdc, 0xed, 0x65, 0x8d, 0x56, 0x96, 0xf0, 0x18, 0x1e, 0x38, 0xbd,
	0x24, 0x15, 0x7a, 0x79, 0x80, 0xcf, 0x61, 0xec, 0xbd, 0xe4, 0xd7, 0xda, 0xba, 0xe0, 0x1c, 0x7c,
	0xea, 0x93, 0xb6, 0x0e, 0x5f, 0x01, 0x7a, 0xa1, 0x7c, 0x97, 0x17, 0x31, 0x6f, 0xea, 0x2b, 0x3f,
	0xee, 0xd8, 0xe2, 0x03, 0xc4, 0x1f, 0xc9, 0xfd, 0x94, 0x15, 0xe9, 0x0b, 0x75, 0xa9, 0xdb, 0x41,
	0xa6, 0x10, 0x35, 0xf5, 0x4d, 0x50, 0xde, 0x84, 0x9b, 0xd1, 0x4c, 0x4d, 0x97, 0xf2, 0x4f, 0x90,
	0x0c, 0x48, 0x5c, 0xc3, 0xe3, 0x9d, 0xaf, 0xb7, 0xd6, 0x4b, 0x7d, 0x4b, 0x75, 0x6b, 0x9d, 0x01,
	0xbe, 0x80, 0x09, 0x07, 0x79, 0xa7, 0xd1, 0x98, 0x73, 0x5f, 0x39, 0x85, 0x29, 0x0c, 0xab, 0xa6,
	0x2e, 0x9c, 0xd4, 0x8a, 0x2d, 0x47, 0xd9, 0x1d, 0x16, 0x33, 0xc0, 0x5f, 0xba, 0xae, 0x2e, 0x94,
	0x35, 0x54, 0xba, 0xd6, 0x69, 0x02, 0x0f, 0x4b, 0xad, 0x1c, 0xa9, 0x76, 0xe7, 0x2d, 0x14, 0x2f,
	0x21, 0xee, 0xf0, 0x83, 0x37, 0x84, 0x43, 0xb7, 0x36, 0xc4, 0xec, 0x28, 0xe3, 0xf8, 0xf5, 0xbf,
	0x03, 0x98, 0xec, 0xde, 0x00, 0xe7, 0x30, 0xba, 0x22, 0x97, 0xfb, 0x95, 0x27, 0xb3, 0xc2, 0x98,
	0xd9, 0x9e, 0x7b, 0xa7, 0x4f, 0xf7, 0x54, 0x82, 0xcc, 0xfb, 0xf6, 0x4e, 0xfc, 0x66, 0x30, 0x66,
	0x66, 0xf7, 0x55, 0xa6, 0xfd, 0xa4, 0x35, 0x38, 0x87, 0xc9, 0xd5, 0xce, 0x45, 0x82, 0xfa, 0x9e,
	0x23, 0xa5, 0x27, 0x5c, 0xe9, 0x6f, 0x7f, 0x0e, 0xe3, 0xdf, 0xdb, 0xc1, 0xf1, 0x09, 0xd3, 0xfa,
	0xab, 0x4b, 0x93, 0x7e, 0xc1, 0x77, 0x58, 0x1c, 0xf1, 0xcf, 0xf4, 0xe6, 0x7f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa2, 0x00, 0xd3, 0x3b, 0x63, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QiniuServiceClient is the client API for QiniuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QiniuServiceClient interface {
	//检查通道连接
	GetToken(ctx context.Context, in *QiniuServiceRequest, opts ...grpc.CallOption) (*QiniuServiceResponse, error)
	UploadBytes(ctx context.Context, in *UploadBytesReq, opts ...grpc.CallOption) (*UploadBytesRsp, error)
	GetVideoInfo(ctx context.Context, in *GetVideoInfoRequest, opts ...grpc.CallOption) (*VideoInfoResponse, error)
	WordInspect(ctx context.Context, in *WordInspectRequest, opts ...grpc.CallOption) (*WordInspectResponse, error)
}

type qiniuServiceClient struct {
	cc *grpc.ClientConn
}

func NewQiniuServiceClient(cc *grpc.ClientConn) QiniuServiceClient {
	return &qiniuServiceClient{cc}
}

func (c *qiniuServiceClient) GetToken(ctx context.Context, in *QiniuServiceRequest, opts ...grpc.CallOption) (*QiniuServiceResponse, error) {
	out := new(QiniuServiceResponse)
	err := c.cc.Invoke(ctx, "/app.QiniuService/get_token", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qiniuServiceClient) UploadBytes(ctx context.Context, in *UploadBytesReq, opts ...grpc.CallOption) (*UploadBytesRsp, error) {
	out := new(UploadBytesRsp)
	err := c.cc.Invoke(ctx, "/app.QiniuService/uploadBytes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qiniuServiceClient) GetVideoInfo(ctx context.Context, in *GetVideoInfoRequest, opts ...grpc.CallOption) (*VideoInfoResponse, error) {
	out := new(VideoInfoResponse)
	err := c.cc.Invoke(ctx, "/app.QiniuService/getVideoInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qiniuServiceClient) WordInspect(ctx context.Context, in *WordInspectRequest, opts ...grpc.CallOption) (*WordInspectResponse, error) {
	out := new(WordInspectResponse)
	err := c.cc.Invoke(ctx, "/app.QiniuService/wordInspect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QiniuServiceServer is the server API for QiniuService service.
type QiniuServiceServer interface {
	//检查通道连接
	GetToken(context.Context, *QiniuServiceRequest) (*QiniuServiceResponse, error)
	UploadBytes(context.Context, *UploadBytesReq) (*UploadBytesRsp, error)
	GetVideoInfo(context.Context, *GetVideoInfoRequest) (*VideoInfoResponse, error)
	WordInspect(context.Context, *WordInspectRequest) (*WordInspectResponse, error)
}

// UnimplementedQiniuServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQiniuServiceServer struct {
}

func (*UnimplementedQiniuServiceServer) GetToken(ctx context.Context, req *QiniuServiceRequest) (*QiniuServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (*UnimplementedQiniuServiceServer) UploadBytes(ctx context.Context, req *UploadBytesReq) (*UploadBytesRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBytes not implemented")
}
func (*UnimplementedQiniuServiceServer) GetVideoInfo(ctx context.Context, req *GetVideoInfoRequest) (*VideoInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoInfo not implemented")
}
func (*UnimplementedQiniuServiceServer) WordInspect(ctx context.Context, req *WordInspectRequest) (*WordInspectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WordInspect not implemented")
}

func RegisterQiniuServiceServer(s *grpc.Server, srv QiniuServiceServer) {
	s.RegisterService(&_QiniuService_serviceDesc, srv)
}

func _QiniuService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QiniuServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiniuServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.QiniuService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiniuServiceServer).GetToken(ctx, req.(*QiniuServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QiniuService_UploadBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBytesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiniuServiceServer).UploadBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.QiniuService/UploadBytes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiniuServiceServer).UploadBytes(ctx, req.(*UploadBytesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QiniuService_GetVideoInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiniuServiceServer).GetVideoInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.QiniuService/GetVideoInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiniuServiceServer).GetVideoInfo(ctx, req.(*GetVideoInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QiniuService_WordInspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordInspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiniuServiceServer).WordInspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.QiniuService/WordInspect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiniuServiceServer).WordInspect(ctx, req.(*WordInspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QiniuService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.QiniuService",
	HandlerType: (*QiniuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_token",
			Handler:    _QiniuService_GetToken_Handler,
		},
		{
			MethodName: "uploadBytes",
			Handler:    _QiniuService_UploadBytes_Handler,
		},
		{
			MethodName: "getVideoInfo",
			Handler:    _QiniuService_GetVideoInfo_Handler,
		},
		{
			MethodName: "wordInspect",
			Handler:    _QiniuService_WordInspect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qiniu_service.proto",
}
