// Code generated by protoc-gen-go. DO NOT EDIT.
// source: school.proto

package app

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddSchoolRequest struct {
	SchoolId             int64    `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSchoolRequest) Reset()         { *m = AddSchoolRequest{} }
func (m *AddSchoolRequest) String() string { return proto.CompactTextString(m) }
func (*AddSchoolRequest) ProtoMessage()    {}
func (*AddSchoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{0}
}

func (m *AddSchoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSchoolRequest.Unmarshal(m, b)
}
func (m *AddSchoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSchoolRequest.Marshal(b, m, deterministic)
}
func (m *AddSchoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSchoolRequest.Merge(m, src)
}
func (m *AddSchoolRequest) XXX_Size() int {
	return xxx_messageInfo_AddSchoolRequest.Size(m)
}
func (m *AddSchoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSchoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSchoolRequest proto.InternalMessageInfo

func (m *AddSchoolRequest) GetSchoolId() int64 {
	if m != nil {
		return m.SchoolId
	}
	return 0
}

func (m *AddSchoolRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type SchoolRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchoolRequest) Reset()         { *m = SchoolRequest{} }
func (m *SchoolRequest) String() string { return proto.CompactTextString(m) }
func (*SchoolRequest) ProtoMessage()    {}
func (*SchoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{1}
}

func (m *SchoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchoolRequest.Unmarshal(m, b)
}
func (m *SchoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchoolRequest.Marshal(b, m, deterministic)
}
func (m *SchoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchoolRequest.Merge(m, src)
}
func (m *SchoolRequest) XXX_Size() int {
	return xxx_messageInfo_SchoolRequest.Size(m)
}
func (m *SchoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchoolRequest proto.InternalMessageInfo

func (m *SchoolRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SchoolRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SchoolResponse struct {
	List                 []*SchoolData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total                int64         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SchoolResponse) Reset()         { *m = SchoolResponse{} }
func (m *SchoolResponse) String() string { return proto.CompactTextString(m) }
func (*SchoolResponse) ProtoMessage()    {}
func (*SchoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{2}
}

func (m *SchoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchoolResponse.Unmarshal(m, b)
}
func (m *SchoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchoolResponse.Marshal(b, m, deterministic)
}
func (m *SchoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchoolResponse.Merge(m, src)
}
func (m *SchoolResponse) XXX_Size() int {
	return xxx_messageInfo_SchoolResponse.Size(m)
}
func (m *SchoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchoolResponse proto.InternalMessageInfo

func (m *SchoolResponse) GetList() []*SchoolData {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SchoolResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type SchoolData struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	TypeId               int64    `protobuf:"varint,6,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	TypeName             string   `protobuf:"bytes,7,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Address              string   `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchoolData) Reset()         { *m = SchoolData{} }
func (m *SchoolData) String() string { return proto.CompactTextString(m) }
func (*SchoolData) ProtoMessage()    {}
func (*SchoolData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{3}
}

func (m *SchoolData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchoolData.Unmarshal(m, b)
}
func (m *SchoolData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchoolData.Marshal(b, m, deterministic)
}
func (m *SchoolData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchoolData.Merge(m, src)
}
func (m *SchoolData) XXX_Size() int {
	return xxx_messageInfo_SchoolData.Size(m)
}
func (m *SchoolData) XXX_DiscardUnknown() {
	xxx_messageInfo_SchoolData.DiscardUnknown(m)
}

var xxx_messageInfo_SchoolData proto.InternalMessageInfo

func (m *SchoolData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SchoolData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchoolData) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *SchoolData) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *SchoolData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SchoolData) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *SchoolData) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *SchoolData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AddSchoolResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSchoolResponse) Reset()         { *m = AddSchoolResponse{} }
func (m *AddSchoolResponse) String() string { return proto.CompactTextString(m) }
func (*AddSchoolResponse) ProtoMessage()    {}
func (*AddSchoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{4}
}

func (m *AddSchoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSchoolResponse.Unmarshal(m, b)
}
func (m *AddSchoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSchoolResponse.Marshal(b, m, deterministic)
}
func (m *AddSchoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSchoolResponse.Merge(m, src)
}
func (m *AddSchoolResponse) XXX_Size() int {
	return xxx_messageInfo_AddSchoolResponse.Size(m)
}
func (m *AddSchoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSchoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSchoolResponse proto.InternalMessageInfo

func (m *AddSchoolResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ScanRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{5}
}

func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (m *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(m, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ScanResponse struct {
	School               *SchoolData `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	Class                *Class      `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{6}
}

func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetSchool() *SchoolData {
	if m != nil {
		return m.School
	}
	return nil
}

func (m *ScanResponse) GetClass() *Class {
	if m != nil {
		return m.Class
	}
	return nil
}

type GradeTypeResponse struct {
	List                 []*GradeTypeInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GradeTypeResponse) Reset()         { *m = GradeTypeResponse{} }
func (m *GradeTypeResponse) String() string { return proto.CompactTextString(m) }
func (*GradeTypeResponse) ProtoMessage()    {}
func (*GradeTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{7}
}

func (m *GradeTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GradeTypeResponse.Unmarshal(m, b)
}
func (m *GradeTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GradeTypeResponse.Marshal(b, m, deterministic)
}
func (m *GradeTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GradeTypeResponse.Merge(m, src)
}
func (m *GradeTypeResponse) XXX_Size() int {
	return xxx_messageInfo_GradeTypeResponse.Size(m)
}
func (m *GradeTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GradeTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GradeTypeResponse proto.InternalMessageInfo

func (m *GradeTypeResponse) GetList() []*GradeTypeInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type GradeTypeInfo struct {
	TypeId               int64        `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Type                 string       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	List                 []*GradeInfo `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GradeTypeInfo) Reset()         { *m = GradeTypeInfo{} }
func (m *GradeTypeInfo) String() string { return proto.CompactTextString(m) }
func (*GradeTypeInfo) ProtoMessage()    {}
func (*GradeTypeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{8}
}

func (m *GradeTypeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GradeTypeInfo.Unmarshal(m, b)
}
func (m *GradeTypeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GradeTypeInfo.Marshal(b, m, deterministic)
}
func (m *GradeTypeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GradeTypeInfo.Merge(m, src)
}
func (m *GradeTypeInfo) XXX_Size() int {
	return xxx_messageInfo_GradeTypeInfo.Size(m)
}
func (m *GradeTypeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GradeTypeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GradeTypeInfo proto.InternalMessageInfo

func (m *GradeTypeInfo) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *GradeTypeInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GradeTypeInfo) GetList() []*GradeInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type GradeInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GradeInfo) Reset()         { *m = GradeInfo{} }
func (m *GradeInfo) String() string { return proto.CompactTextString(m) }
func (*GradeInfo) ProtoMessage()    {}
func (*GradeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{9}
}

func (m *GradeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GradeInfo.Unmarshal(m, b)
}
func (m *GradeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GradeInfo.Marshal(b, m, deterministic)
}
func (m *GradeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GradeInfo.Merge(m, src)
}
func (m *GradeInfo) XXX_Size() int {
	return xxx_messageInfo_GradeInfo.Size(m)
}
func (m *GradeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GradeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GradeInfo proto.InternalMessageInfo

func (m *GradeInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GradeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateClassInfoRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SchoolId             int64    `protobuf:"varint,2,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	GradeId              int64    `protobuf:"varint,3,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	Name                 []string `protobuf:"bytes,4,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClassInfoRequest) Reset()         { *m = CreateClassInfoRequest{} }
func (m *CreateClassInfoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClassInfoRequest) ProtoMessage()    {}
func (*CreateClassInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{10}
}

func (m *CreateClassInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClassInfoRequest.Unmarshal(m, b)
}
func (m *CreateClassInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClassInfoRequest.Marshal(b, m, deterministic)
}
func (m *CreateClassInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClassInfoRequest.Merge(m, src)
}
func (m *CreateClassInfoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClassInfoRequest.Size(m)
}
func (m *CreateClassInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClassInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClassInfoRequest proto.InternalMessageInfo

func (m *CreateClassInfoRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CreateClassInfoRequest) GetSchoolId() int64 {
	if m != nil {
		return m.SchoolId
	}
	return 0
}

func (m *CreateClassInfoRequest) GetGradeId() int64 {
	if m != nil {
		return m.GradeId
	}
	return 0
}

func (m *CreateClassInfoRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type CreateClassRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ClassInfoId          int64    `protobuf:"varint,2,opt,name=class_info_id,json=classInfoId,proto3" json:"class_info_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClassRequest) Reset()         { *m = CreateClassRequest{} }
func (m *CreateClassRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClassRequest) ProtoMessage()    {}
func (*CreateClassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{11}
}

func (m *CreateClassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClassRequest.Unmarshal(m, b)
}
func (m *CreateClassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClassRequest.Marshal(b, m, deterministic)
}
func (m *CreateClassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClassRequest.Merge(m, src)
}
func (m *CreateClassRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClassRequest.Size(m)
}
func (m *CreateClassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClassRequest proto.InternalMessageInfo

func (m *CreateClassRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CreateClassRequest) GetClassInfoId() int64 {
	if m != nil {
		return m.ClassInfoId
	}
	return 0
}

type JoinClassRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ClassId              int64    `protobuf:"varint,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Type                 int64    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinClassRequest) Reset()         { *m = JoinClassRequest{} }
func (m *JoinClassRequest) String() string { return proto.CompactTextString(m) }
func (*JoinClassRequest) ProtoMessage()    {}
func (*JoinClassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{12}
}

func (m *JoinClassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClassRequest.Unmarshal(m, b)
}
func (m *JoinClassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClassRequest.Marshal(b, m, deterministic)
}
func (m *JoinClassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClassRequest.Merge(m, src)
}
func (m *JoinClassRequest) XXX_Size() int {
	return xxx_messageInfo_JoinClassRequest.Size(m)
}
func (m *JoinClassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClassRequest proto.InternalMessageInfo

func (m *JoinClassRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *JoinClassRequest) GetClassId() int64 {
	if m != nil {
		return m.ClassId
	}
	return 0
}

func (m *JoinClassRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type GradeRequest struct {
	SchoolId             int64    `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GradeRequest) Reset()         { *m = GradeRequest{} }
func (m *GradeRequest) String() string { return proto.CompactTextString(m) }
func (*GradeRequest) ProtoMessage()    {}
func (*GradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{13}
}

func (m *GradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GradeRequest.Unmarshal(m, b)
}
func (m *GradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GradeRequest.Marshal(b, m, deterministic)
}
func (m *GradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GradeRequest.Merge(m, src)
}
func (m *GradeRequest) XXX_Size() int {
	return xxx_messageInfo_GradeRequest.Size(m)
}
func (m *GradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GradeRequest proto.InternalMessageInfo

func (m *GradeRequest) GetSchoolId() int64 {
	if m != nil {
		return m.SchoolId
	}
	return 0
}

type QuitClassRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ClassId              int64    `protobuf:"varint,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	QuitUid              int64    `protobuf:"varint,3,opt,name=quit_uid,json=quitUid,proto3" json:"quit_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitClassRequest) Reset()         { *m = QuitClassRequest{} }
func (m *QuitClassRequest) String() string { return proto.CompactTextString(m) }
func (*QuitClassRequest) ProtoMessage()    {}
func (*QuitClassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{14}
}

func (m *QuitClassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitClassRequest.Unmarshal(m, b)
}
func (m *QuitClassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitClassRequest.Marshal(b, m, deterministic)
}
func (m *QuitClassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitClassRequest.Merge(m, src)
}
func (m *QuitClassRequest) XXX_Size() int {
	return xxx_messageInfo_QuitClassRequest.Size(m)
}
func (m *QuitClassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitClassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuitClassRequest proto.InternalMessageInfo

func (m *QuitClassRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *QuitClassRequest) GetClassId() int64 {
	if m != nil {
		return m.ClassId
	}
	return 0
}

func (m *QuitClassRequest) GetQuitUid() int64 {
	if m != nil {
		return m.QuitUid
	}
	return 0
}

type ClassRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Status               int64    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Id                   int64    `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	Grade                int64    `protobuf:"varint,6,opt,name=grade,proto3" json:"grade,omitempty"`
	School               int64    `protobuf:"varint,7,opt,name=school,proto3" json:"school,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClassRequest) Reset()         { *m = ClassRequest{} }
func (m *ClassRequest) String() string { return proto.CompactTextString(m) }
func (*ClassRequest) ProtoMessage()    {}
func (*ClassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{15}
}

func (m *ClassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassRequest.Unmarshal(m, b)
}
func (m *ClassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassRequest.Marshal(b, m, deterministic)
}
func (m *ClassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassRequest.Merge(m, src)
}
func (m *ClassRequest) XXX_Size() int {
	return xxx_messageInfo_ClassRequest.Size(m)
}
func (m *ClassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClassRequest proto.InternalMessageInfo

func (m *ClassRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ClassRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ClassRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ClassRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ClassRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ClassRequest) GetGrade() int64 {
	if m != nil {
		return m.Grade
	}
	return 0
}

func (m *ClassRequest) GetSchool() int64 {
	if m != nil {
		return m.School
	}
	return 0
}

type ClassInfoRequest struct {
	SchoolId             int64    `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	GradeId              int64    `protobuf:"varint,2,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClassInfoRequest) Reset()         { *m = ClassInfoRequest{} }
func (m *ClassInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ClassInfoRequest) ProtoMessage()    {}
func (*ClassInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{16}
}

func (m *ClassInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassInfoRequest.Unmarshal(m, b)
}
func (m *ClassInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassInfoRequest.Marshal(b, m, deterministic)
}
func (m *ClassInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassInfoRequest.Merge(m, src)
}
func (m *ClassInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ClassInfoRequest.Size(m)
}
func (m *ClassInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClassInfoRequest proto.InternalMessageInfo

func (m *ClassInfoRequest) GetSchoolId() int64 {
	if m != nil {
		return m.SchoolId
	}
	return 0
}

func (m *ClassInfoRequest) GetGradeId() int64 {
	if m != nil {
		return m.GradeId
	}
	return 0
}

type ClassResponse struct {
	List                 []*Class `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClassResponse) Reset()         { *m = ClassResponse{} }
func (m *ClassResponse) String() string { return proto.CompactTextString(m) }
func (*ClassResponse) ProtoMessage()    {}
func (*ClassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{17}
}

func (m *ClassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassResponse.Unmarshal(m, b)
}
func (m *ClassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassResponse.Marshal(b, m, deterministic)
}
func (m *ClassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassResponse.Merge(m, src)
}
func (m *ClassResponse) XXX_Size() int {
	return xxx_messageInfo_ClassResponse.Size(m)
}
func (m *ClassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClassResponse proto.InternalMessageInfo

func (m *ClassResponse) GetList() []*Class {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ClassResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Class struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Grade                string   `protobuf:"bytes,2,opt,name=grade,proto3" json:"grade,omitempty"`
	GradeId              int64    `protobuf:"varint,3,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	SchoolType           string   `protobuf:"bytes,4,opt,name=school_type,json=schoolType,proto3" json:"school_type,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Uid                  int64    `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Number               int64    `protobuf:"varint,8,opt,name=number,proto3" json:"number,omitempty"`
	Tag                  string   `protobuf:"bytes,9,opt,name=tag,proto3" json:"tag,omitempty"`
	Code                 string   `protobuf:"bytes,10,opt,name=code,proto3" json:"code,omitempty"`
	AdminList            []int64  `protobuf:"varint,11,rep,packed,name=admin_list,json=adminList,proto3" json:"admin_list,omitempty"`
	StudentList          []int64  `protobuf:"varint,12,rep,packed,name=student_list,json=studentList,proto3" json:"student_list,omitempty"`
	CourseId             int64    `protobuf:"varint,13,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Progress             float64  `protobuf:"fixed64,14,opt,name=progress,proto3" json:"progress,omitempty"`
	ChapterIndex         int64    `protobuf:"varint,15,opt,name=chapter_index,json=chapterIndex,proto3" json:"chapter_index,omitempty"`
	VideoIndex           int64    `protobuf:"varint,16,opt,name=video_index,json=videoIndex,proto3" json:"video_index,omitempty"`
	VideoId              int64    `protobuf:"varint,17,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	SchoolName           string   `protobuf:"bytes,18,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`
	SchoolIcon           string   `protobuf:"bytes,19,opt,name=school_icon,json=schoolIcon,proto3" json:"school_icon,omitempty"`
	CreateBy             int64    `protobuf:"varint,20,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Class) Reset()         { *m = Class{} }
func (m *Class) String() string { return proto.CompactTextString(m) }
func (*Class) ProtoMessage()    {}
func (*Class) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{18}
}

func (m *Class) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Class.Unmarshal(m, b)
}
func (m *Class) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Class.Marshal(b, m, deterministic)
}
func (m *Class) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Class.Merge(m, src)
}
func (m *Class) XXX_Size() int {
	return xxx_messageInfo_Class.Size(m)
}
func (m *Class) XXX_DiscardUnknown() {
	xxx_messageInfo_Class.DiscardUnknown(m)
}

var xxx_messageInfo_Class proto.InternalMessageInfo

func (m *Class) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Class) GetGrade() string {
	if m != nil {
		return m.Grade
	}
	return ""
}

func (m *Class) GetGradeId() int64 {
	if m != nil {
		return m.GradeId
	}
	return 0
}

func (m *Class) GetSchoolType() string {
	if m != nil {
		return m.SchoolType
	}
	return ""
}

func (m *Class) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Class) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Class) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Class) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Class) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Class) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Class) GetAdminList() []int64 {
	if m != nil {
		return m.AdminList
	}
	return nil
}

func (m *Class) GetStudentList() []int64 {
	if m != nil {
		return m.StudentList
	}
	return nil
}

func (m *Class) GetCourseId() int64 {
	if m != nil {
		return m.CourseId
	}
	return 0
}

func (m *Class) GetProgress() float64 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *Class) GetChapterIndex() int64 {
	if m != nil {
		return m.ChapterIndex
	}
	return 0
}

func (m *Class) GetVideoIndex() int64 {
	if m != nil {
		return m.VideoIndex
	}
	return 0
}

func (m *Class) GetVideoId() int64 {
	if m != nil {
		return m.VideoId
	}
	return 0
}

func (m *Class) GetSchoolName() string {
	if m != nil {
		return m.SchoolName
	}
	return ""
}

func (m *Class) GetSchoolIcon() string {
	if m != nil {
		return m.SchoolIcon
	}
	return ""
}

func (m *Class) GetCreateBy() int64 {
	if m != nil {
		return m.CreateBy
	}
	return 0
}

type QuitClassResponse struct {
	StudentList          []int64  `protobuf:"varint,1,rep,packed,name=student_list,json=studentList,proto3" json:"student_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitClassResponse) Reset()         { *m = QuitClassResponse{} }
func (m *QuitClassResponse) String() string { return proto.CompactTextString(m) }
func (*QuitClassResponse) ProtoMessage()    {}
func (*QuitClassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{19}
}

func (m *QuitClassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitClassResponse.Unmarshal(m, b)
}
func (m *QuitClassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitClassResponse.Marshal(b, m, deterministic)
}
func (m *QuitClassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitClassResponse.Merge(m, src)
}
func (m *QuitClassResponse) XXX_Size() int {
	return xxx_messageInfo_QuitClassResponse.Size(m)
}
func (m *QuitClassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitClassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitClassResponse proto.InternalMessageInfo

func (m *QuitClassResponse) GetStudentList() []int64 {
	if m != nil {
		return m.StudentList
	}
	return nil
}

type AddCourseRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CourseId             int64    `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	ClassId              int64    `protobuf:"varint,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCourseRequest) Reset()         { *m = AddCourseRequest{} }
func (m *AddCourseRequest) String() string { return proto.CompactTextString(m) }
func (*AddCourseRequest) ProtoMessage()    {}
func (*AddCourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{20}
}

func (m *AddCourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCourseRequest.Unmarshal(m, b)
}
func (m *AddCourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCourseRequest.Marshal(b, m, deterministic)
}
func (m *AddCourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCourseRequest.Merge(m, src)
}
func (m *AddCourseRequest) XXX_Size() int {
	return xxx_messageInfo_AddCourseRequest.Size(m)
}
func (m *AddCourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCourseRequest proto.InternalMessageInfo

func (m *AddCourseRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AddCourseRequest) GetCourseId() int64 {
	if m != nil {
		return m.CourseId
	}
	return 0
}

func (m *AddCourseRequest) GetClassId() int64 {
	if m != nil {
		return m.ClassId
	}
	return 0
}

type ClassDetailRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClassDetailRequest) Reset()         { *m = ClassDetailRequest{} }
func (m *ClassDetailRequest) String() string { return proto.CompactTextString(m) }
func (*ClassDetailRequest) ProtoMessage()    {}
func (*ClassDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{21}
}

func (m *ClassDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassDetailRequest.Unmarshal(m, b)
}
func (m *ClassDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassDetailRequest.Marshal(b, m, deterministic)
}
func (m *ClassDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassDetailRequest.Merge(m, src)
}
func (m *ClassDetailRequest) XXX_Size() int {
	return xxx_messageInfo_ClassDetailRequest.Size(m)
}
func (m *ClassDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClassDetailRequest proto.InternalMessageInfo

func (m *ClassDetailRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ClassDetailRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type EditCourseProgressRequest struct {
	VideoId              int64    `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ClassId              int64    `protobuf:"varint,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Uid                  int64    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditCourseProgressRequest) Reset()         { *m = EditCourseProgressRequest{} }
func (m *EditCourseProgressRequest) String() string { return proto.CompactTextString(m) }
func (*EditCourseProgressRequest) ProtoMessage()    {}
func (*EditCourseProgressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{22}
}

func (m *EditCourseProgressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditCourseProgressRequest.Unmarshal(m, b)
}
func (m *EditCourseProgressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditCourseProgressRequest.Marshal(b, m, deterministic)
}
func (m *EditCourseProgressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditCourseProgressRequest.Merge(m, src)
}
func (m *EditCourseProgressRequest) XXX_Size() int {
	return xxx_messageInfo_EditCourseProgressRequest.Size(m)
}
func (m *EditCourseProgressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditCourseProgressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditCourseProgressRequest proto.InternalMessageInfo

func (m *EditCourseProgressRequest) GetVideoId() int64 {
	if m != nil {
		return m.VideoId
	}
	return 0
}

func (m *EditCourseProgressRequest) GetClassId() int64 {
	if m != nil {
		return m.ClassId
	}
	return 0
}

func (m *EditCourseProgressRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type SchoolTypeData struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Grade                []*GradeInfo `protobuf:"bytes,3,rep,name=grade,proto3" json:"grade,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SchoolTypeData) Reset()         { *m = SchoolTypeData{} }
func (m *SchoolTypeData) String() string { return proto.CompactTextString(m) }
func (*SchoolTypeData) ProtoMessage()    {}
func (*SchoolTypeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{23}
}

func (m *SchoolTypeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchoolTypeData.Unmarshal(m, b)
}
func (m *SchoolTypeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchoolTypeData.Marshal(b, m, deterministic)
}
func (m *SchoolTypeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchoolTypeData.Merge(m, src)
}
func (m *SchoolTypeData) XXX_Size() int {
	return xxx_messageInfo_SchoolTypeData.Size(m)
}
func (m *SchoolTypeData) XXX_DiscardUnknown() {
	xxx_messageInfo_SchoolTypeData.DiscardUnknown(m)
}

var xxx_messageInfo_SchoolTypeData proto.InternalMessageInfo

func (m *SchoolTypeData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SchoolTypeData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchoolTypeData) GetGrade() []*GradeInfo {
	if m != nil {
		return m.Grade
	}
	return nil
}

type SchoolTypeResponse struct {
	List                 []*SchoolTypeData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SchoolTypeResponse) Reset()         { *m = SchoolTypeResponse{} }
func (m *SchoolTypeResponse) String() string { return proto.CompactTextString(m) }
func (*SchoolTypeResponse) ProtoMessage()    {}
func (*SchoolTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{24}
}

func (m *SchoolTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchoolTypeResponse.Unmarshal(m, b)
}
func (m *SchoolTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchoolTypeResponse.Marshal(b, m, deterministic)
}
func (m *SchoolTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchoolTypeResponse.Merge(m, src)
}
func (m *SchoolTypeResponse) XXX_Size() int {
	return xxx_messageInfo_SchoolTypeResponse.Size(m)
}
func (m *SchoolTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchoolTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchoolTypeResponse proto.InternalMessageInfo

func (m *SchoolTypeResponse) GetList() []*SchoolTypeData {
	if m != nil {
		return m.List
	}
	return nil
}

type TeacherUserRequest struct {
	Type                 int64    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	SchoolId             int64    `protobuf:"varint,2,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	GradeId              int64    `protobuf:"varint,3,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	ClassId              int64    `protobuf:"varint,4,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeacherUserRequest) Reset()         { *m = TeacherUserRequest{} }
func (m *TeacherUserRequest) String() string { return proto.CompactTextString(m) }
func (*TeacherUserRequest) ProtoMessage()    {}
func (*TeacherUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{25}
}

func (m *TeacherUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeacherUserRequest.Unmarshal(m, b)
}
func (m *TeacherUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeacherUserRequest.Marshal(b, m, deterministic)
}
func (m *TeacherUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeacherUserRequest.Merge(m, src)
}
func (m *TeacherUserRequest) XXX_Size() int {
	return xxx_messageInfo_TeacherUserRequest.Size(m)
}
func (m *TeacherUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeacherUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeacherUserRequest proto.InternalMessageInfo

func (m *TeacherUserRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *TeacherUserRequest) GetSchoolId() int64 {
	if m != nil {
		return m.SchoolId
	}
	return 0
}

func (m *TeacherUserRequest) GetGradeId() int64 {
	if m != nil {
		return m.GradeId
	}
	return 0
}

func (m *TeacherUserRequest) GetClassId() int64 {
	if m != nil {
		return m.ClassId
	}
	return 0
}

type TeacherUserResponse struct {
	List                 []int64  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeacherUserResponse) Reset()         { *m = TeacherUserResponse{} }
func (m *TeacherUserResponse) String() string { return proto.CompactTextString(m) }
func (*TeacherUserResponse) ProtoMessage()    {}
func (*TeacherUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{26}
}

func (m *TeacherUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeacherUserResponse.Unmarshal(m, b)
}
func (m *TeacherUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeacherUserResponse.Marshal(b, m, deterministic)
}
func (m *TeacherUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeacherUserResponse.Merge(m, src)
}
func (m *TeacherUserResponse) XXX_Size() int {
	return xxx_messageInfo_TeacherUserResponse.Size(m)
}
func (m *TeacherUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TeacherUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TeacherUserResponse proto.InternalMessageInfo

func (m *TeacherUserResponse) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type CancelSchoolRequest struct {
	List                 []int64  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelSchoolRequest) Reset()         { *m = CancelSchoolRequest{} }
func (m *CancelSchoolRequest) String() string { return proto.CompactTextString(m) }
func (*CancelSchoolRequest) ProtoMessage()    {}
func (*CancelSchoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{27}
}

func (m *CancelSchoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelSchoolRequest.Unmarshal(m, b)
}
func (m *CancelSchoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelSchoolRequest.Marshal(b, m, deterministic)
}
func (m *CancelSchoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelSchoolRequest.Merge(m, src)
}
func (m *CancelSchoolRequest) XXX_Size() int {
	return xxx_messageInfo_CancelSchoolRequest.Size(m)
}
func (m *CancelSchoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelSchoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelSchoolRequest proto.InternalMessageInfo

func (m *CancelSchoolRequest) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*AddSchoolRequest)(nil), "app.AddSchoolRequest")
	proto.RegisterType((*SchoolRequest)(nil), "app.SchoolRequest")
	proto.RegisterType((*SchoolResponse)(nil), "app.SchoolResponse")
	proto.RegisterType((*SchoolData)(nil), "app.SchoolData")
	proto.RegisterType((*AddSchoolResponse)(nil), "app.AddSchoolResponse")
	proto.RegisterType((*ScanRequest)(nil), "app.ScanRequest")
	proto.RegisterType((*ScanResponse)(nil), "app.ScanResponse")
	proto.RegisterType((*GradeTypeResponse)(nil), "app.GradeTypeResponse")
	proto.RegisterType((*GradeTypeInfo)(nil), "app.GradeTypeInfo")
	proto.RegisterType((*GradeInfo)(nil), "app.GradeInfo")
	proto.RegisterType((*CreateClassInfoRequest)(nil), "app.CreateClassInfoRequest")
	proto.RegisterType((*CreateClassRequest)(nil), "app.CreateClassRequest")
	proto.RegisterType((*JoinClassRequest)(nil), "app.JoinClassRequest")
	proto.RegisterType((*GradeRequest)(nil), "app.GradeRequest")
	proto.RegisterType((*QuitClassRequest)(nil), "app.QuitClassRequest")
	proto.RegisterType((*ClassRequest)(nil), "app.ClassRequest")
	proto.RegisterType((*ClassInfoRequest)(nil), "app.ClassInfoRequest")
	proto.RegisterType((*ClassResponse)(nil), "app.ClassResponse")
	proto.RegisterType((*Class)(nil), "app.Class")
	proto.RegisterType((*QuitClassResponse)(nil), "app.QuitClassResponse")
	proto.RegisterType((*AddCourseRequest)(nil), "app.AddCourseRequest")
	proto.RegisterType((*ClassDetailRequest)(nil), "app.ClassDetailRequest")
	proto.RegisterType((*EditCourseProgressRequest)(nil), "app.EditCourseProgressRequest")
	proto.RegisterType((*SchoolTypeData)(nil), "app.SchoolTypeData")
	proto.RegisterType((*SchoolTypeResponse)(nil), "app.SchoolTypeResponse")
	proto.RegisterType((*TeacherUserRequest)(nil), "app.TeacherUserRequest")
	proto.RegisterType((*TeacherUserResponse)(nil), "app.TeacherUserResponse")
	proto.RegisterType((*CancelSchoolRequest)(nil), "app.CancelSchoolRequest")
}

func init() { proto.RegisterFile("school.proto", fileDescriptor_fdb068902851add0) }

var fileDescriptor_fdb068902851add0 = []byte{
	// 1301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xed, 0x6e, 0xdb, 0x36,
	0x17, 0x86, 0x2c, 0x7f, 0x1e, 0xdb, 0xa9, 0xcd, 0xb4, 0xa9, 0xe2, 0xe2, 0x6d, 0xfd, 0x2a, 0xc3,
	0x9a, 0xa2, 0x40, 0x86, 0xa5, 0x58, 0x86, 0xa1, 0x68, 0x81, 0x36, 0x09, 0x36, 0x67, 0x43, 0xb1,
	0x39, 0xe9, 0x8f, 0x15, 0x03, 0x3c, 0x45, 0x64, 0x13, 0x0e, 0xb6, 0xa4, 0x4a, 0x74, 0x30, 0x6f,
	0xf7, 0xb2, 0xff, 0xbb, 0x87, 0x5d, 0xcd, 0xae, 0x64, 0xe0, 0x21, 0x25, 0x51, 0xb2, 0xe3, 0xa4,
	0xfd, 0x27, 0x3e, 0x3c, 0x1f, 0xe4, 0x73, 0x3e, 0x78, 0x04, 0x9d, 0xc4, 0xbf, 0x0c, 0xc3, 0xe9,
	0x5e, 0x14, 0x87, 0x22, 0x24, 0xb6, 0x17, 0x45, 0x03, 0xa0, 0x9e, 0xf0, 0x14, 0xe0, 0xbe, 0x82,
	0xde, 0x2b, 0x4a, 0x4f, 0x51, 0x66, 0xcc, 0x3e, 0xcc, 0x59, 0x22, 0xc8, 0x03, 0x68, 0x29, 0xa5,
	0x09, 0xa7, 0x8e, 0x35, 0xb4, 0x76, 0xed, 0x71, 0x53, 0x01, 0x23, 0x4a, 0x7a, 0x60, 0xcf, 0x39,
	0x75, 0x2a, 0x08, 0xcb, 0x4f, 0xf7, 0x4b, 0xe8, 0x16, 0xf5, 0xb5, 0x88, 0x95, 0x89, 0x90, 0x0d,
	0xa8, 0x64, 0x3a, 0x15, 0x4e, 0xdd, 0xef, 0x61, 0x23, 0x55, 0x49, 0xa2, 0x30, 0x48, 0x18, 0xd9,
	0x81, 0xea, 0x94, 0x27, 0xc2, 0xb1, 0x86, 0xf6, 0x6e, 0x7b, 0xff, 0xce, 0x9e, 0x17, 0x45, 0x7b,
	0x4a, 0xe4, 0xc8, 0x13, 0xde, 0x18, 0x37, 0xc9, 0x5d, 0xa8, 0x89, 0x50, 0x78, 0x53, 0x6d, 0x49,
	0x2d, 0xdc, 0x7f, 0x2c, 0x80, 0x5c, 0x54, 0xfb, 0xb2, 0x52, 0x5f, 0x84, 0x40, 0x35, 0xf0, 0x66,
	0x0c, 0x75, 0x5a, 0x63, 0xfc, 0x96, 0x18, 0xf7, 0xc3, 0xc0, 0xb1, 0x15, 0x26, 0xbf, 0x25, 0x46,
	0x59, 0xe2, 0x3b, 0x55, 0x85, 0xc9, 0x6f, 0x89, 0xf9, 0x21, 0x65, 0x4e, 0x4d, 0x61, 0xf2, 0x9b,
	0xdc, 0x87, 0x86, 0x58, 0x44, 0x4c, 0x72, 0x53, 0x47, 0x27, 0x75, 0xb9, 0x1c, 0x51, 0x49, 0x1b,
	0x6e, 0xa0, 0xb7, 0x06, 0x6a, 0x34, 0x25, 0xf0, 0x46, 0x7a, 0x74, 0xa0, 0xe1, 0x51, 0x1a, 0xb3,
	0x24, 0x71, 0x9a, 0xb8, 0x95, 0x2e, 0xdd, 0x1d, 0xe8, 0x1b, 0x11, 0xd0, 0x74, 0x94, 0x2e, 0xe1,
	0x3e, 0x86, 0xf6, 0xa9, 0xef, 0x05, 0x29, 0xc3, 0x0e, 0x34, 0xfc, 0x30, 0x10, 0x2c, 0x10, 0x28,
	0xd3, 0x1a, 0xa7, 0x4b, 0xf7, 0x67, 0xe8, 0x28, 0x41, 0x6d, 0xe8, 0x31, 0xd4, 0x55, 0xe8, 0x50,
	0x70, 0x05, 0xb3, 0x7a, 0x9b, 0x0c, 0xa1, 0xe6, 0x4f, 0xbd, 0x24, 0x41, 0x9e, 0xda, 0xfb, 0x80,
	0x72, 0x87, 0x12, 0x19, 0xab, 0x0d, 0xf7, 0x39, 0xf4, 0xbf, 0x8d, 0x3d, 0xca, 0xce, 0x16, 0x11,
	0xcb, 0xec, 0x7f, 0x5e, 0x88, 0x1b, 0x41, 0xad, 0x4c, 0x6a, 0x14, 0xbc, 0x0f, 0x55, 0xe8, 0xdc,
	0x5f, 0xa1, 0x5b, 0x80, 0x4d, 0x1a, 0xad, 0x02, 0x8d, 0x04, 0xaa, 0xf2, 0x2b, 0x8d, 0x97, 0xfc,
	0x26, 0xae, 0xf6, 0x62, 0xa3, 0x97, 0x8d, 0xdc, 0x8b, 0xe1, 0xe1, 0x0b, 0x68, 0x65, 0xd0, 0x6d,
	0x92, 0xc0, 0xbd, 0x82, 0xad, 0xc3, 0x98, 0x79, 0x82, 0xe1, 0x2d, 0xd1, 0xd2, 0xb5, 0x09, 0x5c,
	0x28, 0x89, 0x4a, 0xa9, 0x24, 0xb6, 0xa1, 0x79, 0x21, 0x3d, 0xcb, 0x3d, 0x1b, 0xf7, 0x1a, 0xb8,
	0x1e, 0xe5, 0x7e, 0xab, 0x43, 0x3b, 0xf3, 0x7b, 0x02, 0xc4, 0xf0, 0x7b, 0xbd, 0x4f, 0x17, 0xba,
	0x48, 0xfc, 0x84, 0x07, 0xef, 0xc3, 0xdc, 0x6f, 0xdb, 0x4f, 0x8f, 0x3b, 0xa2, 0xee, 0x29, 0xf4,
	0x4e, 0x42, 0x1e, 0xdc, 0x60, 0x69, 0x1b, 0x9a, 0xda, 0x52, 0x6a, 0xa4, 0xa1, 0x8c, 0xe4, 0x6c,
	0xab, 0x73, 0xe3, 0xb7, 0xfb, 0x14, 0x3a, 0xc8, 0xe4, 0x6d, 0xfa, 0x81, 0xfb, 0x0e, 0x7a, 0x3f,
	0xcd, 0xb9, 0xf8, 0xf4, 0x13, 0x6c, 0x43, 0xf3, 0xc3, 0x9c, 0x8b, 0xc9, 0x3c, 0x67, 0x4f, 0xae,
	0xdf, 0x72, 0xea, 0xfe, 0x65, 0x41, 0xe7, 0x06, 0xc3, 0x04, 0xaa, 0x91, 0x77, 0xc1, 0xb4, 0x51,
	0xfc, 0x96, 0x58, 0xc2, 0xff, 0xc8, 0xee, 0x24, 0xbf, 0xc9, 0x16, 0xd4, 0x13, 0xe1, 0x89, 0x79,
	0x82, 0xf5, 0x6d, 0x8f, 0xf5, 0x4a, 0x27, 0x4a, 0x2d, 0x4b, 0x94, 0xbb, 0x50, 0xc3, 0xd8, 0xe9,
	0xda, 0x56, 0x0b, 0xd4, 0x56, 0x55, 0xd4, 0xd0, 0xda, 0xb8, 0x72, 0x4f, 0xa0, 0xb7, 0x94, 0x3c,
	0x6b, 0xbb, 0xa7, 0x99, 0x2a, 0x95, 0x42, 0xaa, 0xb8, 0xc7, 0xd0, 0xd5, 0x77, 0xd5, 0xa5, 0xf5,
	0xb0, 0x50, 0x5a, 0x66, 0x41, 0xae, 0xeb, 0x86, 0x7f, 0x57, 0xa1, 0x86, 0x52, 0x4b, 0x35, 0x90,
	0x5d, 0x4d, 0x15, 0x81, 0xbe, 0xda, 0x9a, 0xe4, 0x7d, 0x04, 0x6d, 0x7d, 0x13, 0x4c, 0x11, 0xd5,
	0x18, 0x41, 0x41, 0xb2, 0x8e, 0xb3, 0xec, 0xae, 0x19, 0xad, 0xf5, 0x11, 0xb4, 0x7d, 0xcc, 0xee,
	0x89, 0xe0, 0xb3, 0x94, 0x46, 0x50, 0xd0, 0x19, 0x9f, 0xb1, 0x34, 0x86, 0x8d, 0x3c, 0x86, 0x5b,
	0x50, 0x0f, 0xe6, 0xb3, 0x73, 0x16, 0x63, 0x6b, 0xb4, 0xc7, 0x7a, 0x25, 0x25, 0x85, 0x77, 0xe1,
	0xb4, 0xd0, 0xba, 0xfc, 0xcc, 0xfa, 0x31, 0x18, 0xfd, 0xf8, 0x7f, 0x00, 0x1e, 0x9d, 0xf1, 0x60,
	0x82, 0x64, 0xb5, 0x87, 0xf6, 0xae, 0x3d, 0x6e, 0x21, 0xf2, 0x83, 0x64, 0xe9, 0xff, 0xd0, 0x49,
	0xc4, 0x9c, 0xb2, 0x40, 0x28, 0x81, 0x0e, 0x0a, 0xb4, 0x35, 0x86, 0x22, 0x0f, 0xa0, 0xe5, 0x87,
	0xf3, 0x38, 0x41, 0x0e, 0xba, 0x2a, 0x62, 0x0a, 0x18, 0x51, 0x32, 0x80, 0x66, 0x14, 0x87, 0x17,
	0xd8, 0xb9, 0x37, 0x86, 0xd6, 0xae, 0x35, 0xce, 0xd6, 0x64, 0x07, 0xba, 0xfe, 0xa5, 0x17, 0x09,
	0x16, 0x4f, 0x78, 0x40, 0xd9, 0xef, 0xce, 0x1d, 0x54, 0xee, 0x68, 0x70, 0x24, 0x31, 0x49, 0xc8,
	0x15, 0xa7, 0x2c, 0xd4, 0x22, 0x3d, 0x45, 0x08, 0x42, 0x4a, 0x60, 0x1b, 0x9a, 0x5a, 0x80, 0x3a,
	0x7d, 0x15, 0x01, 0xb5, 0x6b, 0x46, 0x00, 0x79, 0x26, 0x66, 0x04, 0xde, 0x68, 0xb6, 0xd3, 0x64,
	0x93, 0xef, 0xd9, 0xa6, 0x29, 0x30, 0x92, 0xaf, 0x9a, 0xbc, 0x9b, 0x0a, 0xc7, 0xf9, 0xc2, 0xb9,
	0xab, 0xef, 0x86, 0xc0, 0xeb, 0x85, 0x7b, 0x00, 0x7d, 0xa3, 0x76, 0x75, 0xda, 0x95, 0x09, 0xb3,
	0x96, 0x08, 0x73, 0x7f, 0xc1, 0xa1, 0xe1, 0x10, 0x29, 0x5a, 0xdb, 0x33, 0x73, 0x5a, 0x2b, 0x25,
	0x5a, 0xcd, 0x86, 0x60, 0x17, 0x1a, 0x82, 0x7b, 0x00, 0x04, 0x4f, 0x74, 0xc4, 0x84, 0xc7, 0xb3,
	0xa1, 0xa2, 0x9c, 0xcd, 0xcb, 0x73, 0x88, 0x0f, 0xdb, 0xc7, 0x94, 0x0b, 0x75, 0xac, 0x1f, 0x75,
	0x8c, 0x52, 0x75, 0x93, 0x64, 0xab, 0x48, 0xf2, 0x9a, 0xde, 0xa4, 0x9d, 0xd8, 0xb9, 0x93, 0x77,
	0xe9, 0xe4, 0x22, 0x0b, 0xe0, 0xd6, 0xf3, 0xc6, 0x67, 0x69, 0xe9, 0xad, 0x7e, 0xc0, 0xd4, 0xa6,
	0xfb, 0x02, 0x48, 0x6e, 0xdb, 0x78, 0xc1, 0xcd, 0x36, 0xb0, 0x69, 0xbc, 0xdf, 0xe9, 0x11, 0xf4,
	0x03, 0xf8, 0x27, 0x90, 0x33, 0xe6, 0xf9, 0x97, 0x2c, 0x7e, 0x9b, 0xb0, 0x38, 0xbd, 0x78, 0xda,
	0xe0, 0xad, 0xbc, 0xc1, 0x7f, 0xf2, 0x6b, 0x66, 0x32, 0x55, 0x2d, 0x06, 0xed, 0x09, 0x6c, 0x16,
	0x9c, 0xeb, 0xc3, 0x13, 0xe3, 0xf0, 0xb6, 0x3e, 0xe7, 0x13, 0xd8, 0x3c, 0xf4, 0x02, 0x9f, 0x4d,
	0x8b, 0x53, 0xe3, 0x0a, 0xd1, 0xfd, 0x7f, 0x5b, 0xe9, 0x6c, 0x79, 0xca, 0xe2, 0x2b, 0xee, 0x33,
	0x72, 0x90, 0x25, 0x3c, 0xf6, 0x40, 0x62, 0xd0, 0xa1, 0x0d, 0x0d, 0x36, 0x0b, 0x98, 0x3e, 0xc8,
	0x4b, 0xe8, 0x19, 0xbd, 0x4c, 0x29, 0xf7, 0x51, 0xf0, 0x78, 0x16, 0x89, 0x45, 0xaa, 0x7b, 0xbf,
	0x44, 0x6f, 0xa6, 0xff, 0x15, 0x00, 0xa3, 0x5c, 0xa8, 0x1d, 0x52, 0x9e, 0xa2, 0x06, 0x5b, 0x08,
	0x2c, 0xcf, 0x71, 0x07, 0xd0, 0xf2, 0x52, 0x90, 0xdc, 0x2b, 0x0b, 0x29, 0x9f, 0xc4, 0x3c, 0x86,
	0xd6, 0xfb, 0x1a, 0x40, 0x3e, 0x82, 0x1f, 0xaf, 0xf8, 0x0c, 0x9a, 0xb3, 0x85, 0x56, 0xbb, 0x35,
	0x39, 0x4f, 0xa1, 0x9a, 0xf8, 0x5e, 0x40, 0x7a, 0x7a, 0x33, 0x1b, 0x34, 0x07, 0x7d, 0x03, 0xc9,
	0x8f, 0xa6, 0xf2, 0xc3, 0xe0, 0xd0, 0x1c, 0x17, 0x34, 0x17, 0xcb, 0xa3, 0xe2, 0x11, 0xf4, 0x75,
	0x2b, 0xca, 0xc7, 0x1a, 0xf2, 0x40, 0x3d, 0x6b, 0x2b, 0xe7, 0xb0, 0x95, 0x17, 0x7c, 0x0e, 0x1d,
	0xd3, 0x0a, 0xb9, 0x5f, 0x36, 0x70, 0x03, 0xad, 0xbf, 0x85, 0x3c, 0xd0, 0xaa, 0x8a, 0xd6, 0xf2,
	0xfc, 0xb4, 0x2e, 0x1e, 0x05, 0xc5, 0xf2, 0xd8, 0xb3, 0x52, 0xf1, 0x35, 0xf4, 0x29, 0x4f, 0x92,
	0x70, 0x3a, 0x17, 0x3c, 0x0c, 0xd6, 0xeb, 0x6f, 0x95, 0xe1, 0x2c, 0xa6, 0xa0, 0x18, 0x33, 0x18,
	0x5f, 0xe1, 0xb8, 0xac, 0xd4, 0x51, 0x4a, 0x14, 0xdb, 0x68, 0xca, 0xd3, 0x52, 0x63, 0x1d, 0x18,
	0x83, 0x85, 0xbc, 0xa6, 0x11, 0x9b, 0x7b, 0xf9, 0xce, 0x72, 0x54, 0x8a, 0xde, 0x54, 0x9e, 0xab,
	0xd6, 0x9b, 0xa7, 0x6b, 0xe1, 0x85, 0x58, 0x49, 0xcf, 0x37, 0xd0, 0x89, 0xd9, 0x2c, 0xbc, 0x62,
	0x1f, 0xaf, 0xfa, 0x1d, 0x10, 0xb6, 0xd4, 0xee, 0xc9, 0x43, 0x25, 0x79, 0xdd, 0x3b, 0xb0, 0xd2,
	0xd2, 0x4b, 0x68, 0xcd, 0x13, 0x16, 0x2b, 0x7a, 0x15, 0x4f, 0xcb, 0x8d, 0x74, 0xe0, 0x2c, 0x6f,
	0x68, 0xfd, 0x17, 0xd0, 0xf5, 0xb1, 0xa1, 0x4d, 0xf4, 0xbf, 0x94, 0x12, 0x5d, 0xd1, 0xe4, 0x56,
	0xb9, 0x3f, 0xaf, 0xe3, 0x9f, 0xf8, 0xb3, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x96, 0x8d,
	0x50, 0xaa, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchoolServiceClient is the client API for SchoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchoolServiceClient interface {
	SchoolList(ctx context.Context, in *SchoolRequest, opts ...grpc.CallOption) (*SchoolResponse, error)
	SchoolTypeList(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SchoolTypeResponse, error)
	EditSchool(ctx context.Context, in *SchoolData, opts ...grpc.CallOption) (*AddSchoolResponse, error)
	AddSchool(ctx context.Context, in *AddSchoolRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	QuitSchool(ctx context.Context, in *AddSchoolRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	MySchool(ctx context.Context, in *SchoolRequest, opts ...grpc.CallOption) (*SchoolResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	GradeList(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeTypeResponse, error)
	CreateClassInfo(ctx context.Context, in *CreateClassInfoRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	CreateClass(ctx context.Context, in *CreateClassRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	JoinClass(ctx context.Context, in *JoinClassRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	QuitClass(ctx context.Context, in *QuitClassRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	DissolutionClass(ctx context.Context, in *QuitClassRequest, opts ...grpc.CallOption) (*QuitClassResponse, error)
	ClassList(ctx context.Context, in *ClassRequest, opts ...grpc.CallOption) (*ClassResponse, error)
	ClassDetail(ctx context.Context, in *ClassDetailRequest, opts ...grpc.CallOption) (*Class, error)
	ClassInfo(ctx context.Context, in *ClassInfoRequest, opts ...grpc.CallOption) (*ClassResponse, error)
	AddCourse(ctx context.Context, in *AddCourseRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	RemoveCourse(ctx context.Context, in *AddCourseRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	EditCourseProgress(ctx context.Context, in *EditCourseProgressRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	UserList(ctx context.Context, in *TeacherUserRequest, opts ...grpc.CallOption) (*TeacherUserResponse, error)
	CancelSchool(ctx context.Context, in *CancelSchoolRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type schoolServiceClient struct {
	cc *grpc.ClientConn
}

func NewSchoolServiceClient(cc *grpc.ClientConn) SchoolServiceClient {
	return &schoolServiceClient{cc}
}

func (c *schoolServiceClient) SchoolList(ctx context.Context, in *SchoolRequest, opts ...grpc.CallOption) (*SchoolResponse, error) {
	out := new(SchoolResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/school_list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) SchoolTypeList(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SchoolTypeResponse, error) {
	out := new(SchoolTypeResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/school_type_list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) EditSchool(ctx context.Context, in *SchoolData, opts ...grpc.CallOption) (*AddSchoolResponse, error) {
	out := new(AddSchoolResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/editSchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) AddSchool(ctx context.Context, in *AddSchoolRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/addSchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) QuitSchool(ctx context.Context, in *AddSchoolRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/quitSchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) MySchool(ctx context.Context, in *SchoolRequest, opts ...grpc.CallOption) (*SchoolResponse, error) {
	out := new(SchoolResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/mySchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) GradeList(ctx context.Context, in *GradeRequest, opts ...grpc.CallOption) (*GradeTypeResponse, error) {
	out := new(GradeTypeResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/grade_list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) CreateClassInfo(ctx context.Context, in *CreateClassInfoRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/create_class_info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) CreateClass(ctx context.Context, in *CreateClassRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/create_class", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) JoinClass(ctx context.Context, in *JoinClassRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/join_class", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) QuitClass(ctx context.Context, in *QuitClassRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/quit_class", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) DissolutionClass(ctx context.Context, in *QuitClassRequest, opts ...grpc.CallOption) (*QuitClassResponse, error) {
	out := new(QuitClassResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/dissolution_class", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) ClassList(ctx context.Context, in *ClassRequest, opts ...grpc.CallOption) (*ClassResponse, error) {
	out := new(ClassResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/class_list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) ClassDetail(ctx context.Context, in *ClassDetailRequest, opts ...grpc.CallOption) (*Class, error) {
	out := new(Class)
	err := c.cc.Invoke(ctx, "/app.SchoolService/class_detail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) ClassInfo(ctx context.Context, in *ClassInfoRequest, opts ...grpc.CallOption) (*ClassResponse, error) {
	out := new(ClassResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/class_info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) AddCourse(ctx context.Context, in *AddCourseRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/addCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) RemoveCourse(ctx context.Context, in *AddCourseRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/removeCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) EditCourseProgress(ctx context.Context, in *EditCourseProgressRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/editCourseProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) UserList(ctx context.Context, in *TeacherUserRequest, opts ...grpc.CallOption) (*TeacherUserResponse, error) {
	out := new(TeacherUserResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/user_list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) CancelSchool(ctx context.Context, in *CancelSchoolRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.SchoolService/cancel_school", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchoolServiceServer is the server API for SchoolService service.
type SchoolServiceServer interface {
	SchoolList(context.Context, *SchoolRequest) (*SchoolResponse, error)
	SchoolTypeList(context.Context, *EmptyRequest) (*SchoolTypeResponse, error)
	EditSchool(context.Context, *SchoolData) (*AddSchoolResponse, error)
	AddSchool(context.Context, *AddSchoolRequest) (*EmptyResponse, error)
	QuitSchool(context.Context, *AddSchoolRequest) (*EmptyResponse, error)
	MySchool(context.Context, *SchoolRequest) (*SchoolResponse, error)
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	GradeList(context.Context, *GradeRequest) (*GradeTypeResponse, error)
	CreateClassInfo(context.Context, *CreateClassInfoRequest) (*EmptyResponse, error)
	CreateClass(context.Context, *CreateClassRequest) (*EmptyResponse, error)
	JoinClass(context.Context, *JoinClassRequest) (*EmptyResponse, error)
	QuitClass(context.Context, *QuitClassRequest) (*EmptyResponse, error)
	DissolutionClass(context.Context, *QuitClassRequest) (*QuitClassResponse, error)
	ClassList(context.Context, *ClassRequest) (*ClassResponse, error)
	ClassDetail(context.Context, *ClassDetailRequest) (*Class, error)
	ClassInfo(context.Context, *ClassInfoRequest) (*ClassResponse, error)
	AddCourse(context.Context, *AddCourseRequest) (*EmptyResponse, error)
	RemoveCourse(context.Context, *AddCourseRequest) (*EmptyResponse, error)
	EditCourseProgress(context.Context, *EditCourseProgressRequest) (*EmptyResponse, error)
	UserList(context.Context, *TeacherUserRequest) (*TeacherUserResponse, error)
	CancelSchool(context.Context, *CancelSchoolRequest) (*EmptyResponse, error)
}

// UnimplementedSchoolServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSchoolServiceServer struct {
}

func (*UnimplementedSchoolServiceServer) SchoolList(ctx context.Context, req *SchoolRequest) (*SchoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SchoolList not implemented")
}
func (*UnimplementedSchoolServiceServer) SchoolTypeList(ctx context.Context, req *EmptyRequest) (*SchoolTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SchoolTypeList not implemented")
}
func (*UnimplementedSchoolServiceServer) EditSchool(ctx context.Context, req *SchoolData) (*AddSchoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditSchool not implemented")
}
func (*UnimplementedSchoolServiceServer) AddSchool(ctx context.Context, req *AddSchoolRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSchool not implemented")
}
func (*UnimplementedSchoolServiceServer) QuitSchool(ctx context.Context, req *AddSchoolRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitSchool not implemented")
}
func (*UnimplementedSchoolServiceServer) MySchool(ctx context.Context, req *SchoolRequest) (*SchoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MySchool not implemented")
}
func (*UnimplementedSchoolServiceServer) Scan(ctx context.Context, req *ScanRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (*UnimplementedSchoolServiceServer) GradeList(ctx context.Context, req *GradeRequest) (*GradeTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GradeList not implemented")
}
func (*UnimplementedSchoolServiceServer) CreateClassInfo(ctx context.Context, req *CreateClassInfoRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClassInfo not implemented")
}
func (*UnimplementedSchoolServiceServer) CreateClass(ctx context.Context, req *CreateClassRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClass not implemented")
}
func (*UnimplementedSchoolServiceServer) JoinClass(ctx context.Context, req *JoinClassRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinClass not implemented")
}
func (*UnimplementedSchoolServiceServer) QuitClass(ctx context.Context, req *QuitClassRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitClass not implemented")
}
func (*UnimplementedSchoolServiceServer) DissolutionClass(ctx context.Context, req *QuitClassRequest) (*QuitClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DissolutionClass not implemented")
}
func (*UnimplementedSchoolServiceServer) ClassList(ctx context.Context, req *ClassRequest) (*ClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassList not implemented")
}
func (*UnimplementedSchoolServiceServer) ClassDetail(ctx context.Context, req *ClassDetailRequest) (*Class, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassDetail not implemented")
}
func (*UnimplementedSchoolServiceServer) ClassInfo(ctx context.Context, req *ClassInfoRequest) (*ClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassInfo not implemented")
}
func (*UnimplementedSchoolServiceServer) AddCourse(ctx context.Context, req *AddCourseRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCourse not implemented")
}
func (*UnimplementedSchoolServiceServer) RemoveCourse(ctx context.Context, req *AddCourseRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCourse not implemented")
}
func (*UnimplementedSchoolServiceServer) EditCourseProgress(ctx context.Context, req *EditCourseProgressRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditCourseProgress not implemented")
}
func (*UnimplementedSchoolServiceServer) UserList(ctx context.Context, req *TeacherUserRequest) (*TeacherUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserList not implemented")
}
func (*UnimplementedSchoolServiceServer) CancelSchool(ctx context.Context, req *CancelSchoolRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelSchool not implemented")
}

func RegisterSchoolServiceServer(s *grpc.Server, srv SchoolServiceServer) {
	s.RegisterService(&_SchoolService_serviceDesc, srv)
}

func _SchoolService_SchoolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).SchoolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/SchoolList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).SchoolList(ctx, req.(*SchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_SchoolTypeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).SchoolTypeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/SchoolTypeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).SchoolTypeList(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_EditSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchoolData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).EditSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/EditSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).EditSchool(ctx, req.(*SchoolData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_AddSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).AddSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/AddSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).AddSchool(ctx, req.(*AddSchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_QuitSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).QuitSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/QuitSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).QuitSchool(ctx, req.(*AddSchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_MySchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).MySchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/MySchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).MySchool(ctx, req.(*SchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_GradeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).GradeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/GradeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).GradeList(ctx, req.(*GradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_CreateClassInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClassInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).CreateClassInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/CreateClassInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).CreateClassInfo(ctx, req.(*CreateClassInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_CreateClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).CreateClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/CreateClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).CreateClass(ctx, req.(*CreateClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_JoinClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).JoinClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/JoinClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).JoinClass(ctx, req.(*JoinClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_QuitClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).QuitClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/QuitClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).QuitClass(ctx, req.(*QuitClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_DissolutionClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).DissolutionClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/DissolutionClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).DissolutionClass(ctx, req.(*QuitClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_ClassList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).ClassList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/ClassList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).ClassList(ctx, req.(*ClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_ClassDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).ClassDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/ClassDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).ClassDetail(ctx, req.(*ClassDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_ClassInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).ClassInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/ClassInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).ClassInfo(ctx, req.(*ClassInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_AddCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).AddCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/AddCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).AddCourse(ctx, req.(*AddCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_RemoveCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).RemoveCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/RemoveCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).RemoveCourse(ctx, req.(*AddCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_EditCourseProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCourseProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).EditCourseProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/EditCourseProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).EditCourseProgress(ctx, req.(*EditCourseProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeacherUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/UserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).UserList(ctx, req.(*TeacherUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_CancelSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelSchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).CancelSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.SchoolService/CancelSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).CancelSchool(ctx, req.(*CancelSchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchoolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.SchoolService",
	HandlerType: (*SchoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "school_list",
			Handler:    _SchoolService_SchoolList_Handler,
		},
		{
			MethodName: "school_type_list",
			Handler:    _SchoolService_SchoolTypeList_Handler,
		},
		{
			MethodName: "editSchool",
			Handler:    _SchoolService_EditSchool_Handler,
		},
		{
			MethodName: "addSchool",
			Handler:    _SchoolService_AddSchool_Handler,
		},
		{
			MethodName: "quitSchool",
			Handler:    _SchoolService_QuitSchool_Handler,
		},
		{
			MethodName: "mySchool",
			Handler:    _SchoolService_MySchool_Handler,
		},
		{
			MethodName: "scan",
			Handler:    _SchoolService_Scan_Handler,
		},
		{
			MethodName: "grade_list",
			Handler:    _SchoolService_GradeList_Handler,
		},
		{
			MethodName: "create_class_info",
			Handler:    _SchoolService_CreateClassInfo_Handler,
		},
		{
			MethodName: "create_class",
			Handler:    _SchoolService_CreateClass_Handler,
		},
		{
			MethodName: "join_class",
			Handler:    _SchoolService_JoinClass_Handler,
		},
		{
			MethodName: "quit_class",
			Handler:    _SchoolService_QuitClass_Handler,
		},
		{
			MethodName: "dissolution_class",
			Handler:    _SchoolService_DissolutionClass_Handler,
		},
		{
			MethodName: "class_list",
			Handler:    _SchoolService_ClassList_Handler,
		},
		{
			MethodName: "class_detail",
			Handler:    _SchoolService_ClassDetail_Handler,
		},
		{
			MethodName: "class_info",
			Handler:    _SchoolService_ClassInfo_Handler,
		},
		{
			MethodName: "addCourse",
			Handler:    _SchoolService_AddCourse_Handler,
		},
		{
			MethodName: "removeCourse",
			Handler:    _SchoolService_RemoveCourse_Handler,
		},
		{
			MethodName: "editCourseProgress",
			Handler:    _SchoolService_EditCourseProgress_Handler,
		},
		{
			MethodName: "user_list",
			Handler:    _SchoolService_UserList_Handler,
		},
		{
			MethodName: "cancel_school",
			Handler:    _SchoolService_CancelSchool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "school.proto",
}
