// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_service.proto

package app

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Type                 int64    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	OuthType             int64    `protobuf:"varint,5,opt,name=outh_type,json=outhType,proto3" json:"outh_type,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Pass                 string   `protobuf:"bytes,7,opt,name=pass,proto3" json:"pass,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Head                 string   `protobuf:"bytes,9,opt,name=head,proto3" json:"head,omitempty"`
	IsMiniPrograms       bool     `protobuf:"varint,10,opt,name=isMiniPrograms,proto3" json:"isMiniPrograms,omitempty"`
	Device               string   `protobuf:"bytes,11,opt,name=device,proto3" json:"device,omitempty"`
	Uid                  int64    `protobuf:"varint,12,opt,name=uid,proto3" json:"uid,omitempty"`
	Sign                 string   `protobuf:"bytes,13,opt,name=sign,proto3" json:"sign,omitempty"`
	JToken               string   `protobuf:"bytes,14,opt,name=j_token,json=jToken,proto3" json:"j_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *LoginRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *LoginRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *LoginRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LoginRequest) GetOuthType() int64 {
	if m != nil {
		return m.OuthType
	}
	return 0
}

func (m *LoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginRequest) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRequest) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *LoginRequest) GetIsMiniPrograms() bool {
	if m != nil {
		return m.IsMiniPrograms
	}
	return false
}

func (m *LoginRequest) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *LoginRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *LoginRequest) GetJToken() string {
	if m != nil {
		return m.JToken
	}
	return ""
}

type UserDataResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Head                 string   `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Sex                  int64    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Uid                  int64    `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	OpenId               string   `protobuf:"bytes,6,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	No                   string   `protobuf:"bytes,7,opt,name=no,proto3" json:"no,omitempty"`
	InviteCode           string   `protobuf:"bytes,8,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	Identity             int64    `protobuf:"varint,9,opt,name=identity,proto3" json:"identity,omitempty"`
	Sign                 string   `protobuf:"bytes,10,opt,name=sign,proto3" json:"sign,omitempty"`
	Province             string   `protobuf:"bytes,11,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	District             string   `protobuf:"bytes,13,opt,name=district,proto3" json:"district,omitempty"`
	HaveWx               bool     `protobuf:"varint,14,opt,name=haveWx,proto3" json:"haveWx,omitempty"`
	HavePass             bool     `protobuf:"varint,15,opt,name=havePass,proto3" json:"havePass,omitempty"`
	IsNew                bool     `protobuf:"varint,16,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	CancelStatus         bool     `protobuf:"varint,17,opt,name=cancelStatus,proto3" json:"cancelStatus,omitempty"`
	CancelTime           int64    `protobuf:"varint,18,opt,name=cancel_time,json=cancelTime,proto3" json:"cancel_time,omitempty"`
	LoginType            int64    `protobuf:"varint,19,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"`
	Address              string   `protobuf:"bytes,20,opt,name=address,proto3" json:"address,omitempty"`
	Age                  int64    `protobuf:"varint,21,opt,name=age,proto3" json:"age,omitempty"`
	RegistrationId       string   `protobuf:"bytes,22,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	LoginTime            int64    `protobuf:"varint,23,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDataResponse) Reset()         { *m = UserDataResponse{} }
func (m *UserDataResponse) String() string { return proto.CompactTextString(m) }
func (*UserDataResponse) ProtoMessage()    {}
func (*UserDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{1}
}

func (m *UserDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDataResponse.Unmarshal(m, b)
}
func (m *UserDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDataResponse.Marshal(b, m, deterministic)
}
func (m *UserDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDataResponse.Merge(m, src)
}
func (m *UserDataResponse) XXX_Size() int {
	return xxx_messageInfo_UserDataResponse.Size(m)
}
func (m *UserDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserDataResponse proto.InternalMessageInfo

func (m *UserDataResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserDataResponse) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *UserDataResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserDataResponse) GetSex() int64 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserDataResponse) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserDataResponse) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *UserDataResponse) GetNo() string {
	if m != nil {
		return m.No
	}
	return ""
}

func (m *UserDataResponse) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

func (m *UserDataResponse) GetIdentity() int64 {
	if m != nil {
		return m.Identity
	}
	return 0
}

func (m *UserDataResponse) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *UserDataResponse) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *UserDataResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *UserDataResponse) GetDistrict() string {
	if m != nil {
		return m.District
	}
	return ""
}

func (m *UserDataResponse) GetHaveWx() bool {
	if m != nil {
		return m.HaveWx
	}
	return false
}

func (m *UserDataResponse) GetHavePass() bool {
	if m != nil {
		return m.HavePass
	}
	return false
}

func (m *UserDataResponse) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

func (m *UserDataResponse) GetCancelStatus() bool {
	if m != nil {
		return m.CancelStatus
	}
	return false
}

func (m *UserDataResponse) GetCancelTime() int64 {
	if m != nil {
		return m.CancelTime
	}
	return 0
}

func (m *UserDataResponse) GetLoginType() int64 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

func (m *UserDataResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserDataResponse) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserDataResponse) GetRegistrationId() string {
	if m != nil {
		return m.RegistrationId
	}
	return ""
}

func (m *UserDataResponse) GetLoginTime() int64 {
	if m != nil {
		return m.LoginTime
	}
	return 0
}

type UpdateUserRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Pass                 string   `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	Uid                  int64    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Type                 int64    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	IdentityType         int64    `protobuf:"varint,5,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	NewPass              string   `protobuf:"bytes,6,opt,name=new_pass,json=newPass,proto3" json:"new_pass,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Sign                 string   `protobuf:"bytes,8,opt,name=sign,proto3" json:"sign,omitempty"`
	Sex                  int64    `protobuf:"varint,9,opt,name=sex,proto3" json:"sex,omitempty"`
	District             string   `protobuf:"bytes,10,opt,name=district,proto3" json:"district,omitempty"`
	Head                 string   `protobuf:"bytes,11,opt,name=head,proto3" json:"head,omitempty"`
	Age                  int64    `protobuf:"varint,12,opt,name=age,proto3" json:"age,omitempty"`
	RegistrationId       string   `protobuf:"bytes,13,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	UidList              []int64  `protobuf:"varint,14,rep,packed,name=uid_list,json=uidList,proto3" json:"uid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{2}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateUserRequest) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

func (m *UpdateUserRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UpdateUserRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *UpdateUserRequest) GetIdentityType() int64 {
	if m != nil {
		return m.IdentityType
	}
	return 0
}

func (m *UpdateUserRequest) GetNewPass() string {
	if m != nil {
		return m.NewPass
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *UpdateUserRequest) GetSex() int64 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UpdateUserRequest) GetDistrict() string {
	if m != nil {
		return m.District
	}
	return ""
}

func (m *UpdateUserRequest) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *UpdateUserRequest) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UpdateUserRequest) GetRegistrationId() string {
	if m != nil {
		return m.RegistrationId
	}
	return ""
}

func (m *UpdateUserRequest) GetUidList() []int64 {
	if m != nil {
		return m.UidList
	}
	return nil
}

type PhoneCheckRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Device               string   `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneCheckRequest) Reset()         { *m = PhoneCheckRequest{} }
func (m *PhoneCheckRequest) String() string { return proto.CompactTextString(m) }
func (*PhoneCheckRequest) ProtoMessage()    {}
func (*PhoneCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{3}
}

func (m *PhoneCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneCheckRequest.Unmarshal(m, b)
}
func (m *PhoneCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneCheckRequest.Marshal(b, m, deterministic)
}
func (m *PhoneCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneCheckRequest.Merge(m, src)
}
func (m *PhoneCheckRequest) XXX_Size() int {
	return xxx_messageInfo_PhoneCheckRequest.Size(m)
}
func (m *PhoneCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneCheckRequest proto.InternalMessageInfo

func (m *PhoneCheckRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PhoneCheckRequest) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

type PhoneCheckResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneCheckResponse) Reset()         { *m = PhoneCheckResponse{} }
func (m *PhoneCheckResponse) String() string { return proto.CompactTextString(m) }
func (*PhoneCheckResponse) ProtoMessage()    {}
func (*PhoneCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{4}
}

func (m *PhoneCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneCheckResponse.Unmarshal(m, b)
}
func (m *PhoneCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneCheckResponse.Marshal(b, m, deterministic)
}
func (m *PhoneCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneCheckResponse.Merge(m, src)
}
func (m *PhoneCheckResponse) XXX_Size() int {
	return xxx_messageInfo_PhoneCheckResponse.Size(m)
}
func (m *PhoneCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneCheckResponse proto.InternalMessageInfo

func (m *PhoneCheckResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type AddressRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int64    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressRequest) Reset()         { *m = AddressRequest{} }
func (m *AddressRequest) String() string { return proto.CompactTextString(m) }
func (*AddressRequest) ProtoMessage()    {}
func (*AddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{5}
}

func (m *AddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressRequest.Unmarshal(m, b)
}
func (m *AddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressRequest.Marshal(b, m, deterministic)
}
func (m *AddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressRequest.Merge(m, src)
}
func (m *AddressRequest) XXX_Size() int {
	return xxx_messageInfo_AddressRequest.Size(m)
}
func (m *AddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddressRequest proto.InternalMessageInfo

func (m *AddressRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddressRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type AddressResponse struct {
	List                 []*AddressData `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressResponse) Reset()         { *m = AddressResponse{} }
func (m *AddressResponse) String() string { return proto.CompactTextString(m) }
func (*AddressResponse) ProtoMessage()    {}
func (*AddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{6}
}

func (m *AddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressResponse.Unmarshal(m, b)
}
func (m *AddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressResponse.Marshal(b, m, deterministic)
}
func (m *AddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressResponse.Merge(m, src)
}
func (m *AddressResponse) XXX_Size() int {
	return xxx_messageInfo_AddressResponse.Size(m)
}
func (m *AddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddressResponse proto.InternalMessageInfo

func (m *AddressResponse) GetList() []*AddressData {
	if m != nil {
		return m.List
	}
	return nil
}

type AddressData struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid                  int64          `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	First                string         `protobuf:"bytes,4,opt,name=first,proto3" json:"first,omitempty"`
	Letter               string         `protobuf:"bytes,5,opt,name=letter,proto3" json:"letter,omitempty"`
	List                 []*AddressData `protobuf:"bytes,6,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddressData) Reset()         { *m = AddressData{} }
func (m *AddressData) String() string { return proto.CompactTextString(m) }
func (*AddressData) ProtoMessage()    {}
func (*AddressData) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{7}
}

func (m *AddressData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressData.Unmarshal(m, b)
}
func (m *AddressData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressData.Marshal(b, m, deterministic)
}
func (m *AddressData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressData.Merge(m, src)
}
func (m *AddressData) XXX_Size() int {
	return xxx_messageInfo_AddressData.Size(m)
}
func (m *AddressData) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressData.DiscardUnknown(m)
}

var xxx_messageInfo_AddressData proto.InternalMessageInfo

func (m *AddressData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddressData) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *AddressData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddressData) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *AddressData) GetLetter() string {
	if m != nil {
		return m.Letter
	}
	return ""
}

func (m *AddressData) GetList() []*AddressData {
	if m != nil {
		return m.List
	}
	return nil
}

type ModifyOuthRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	OuthType             int64    `protobuf:"varint,4,opt,name=outh_type,json=outhType,proto3" json:"outh_type,omitempty"`
	Uid                  int64    `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	IsUnbind             bool     `protobuf:"varint,6,opt,name=isUnbind,proto3" json:"isUnbind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyOuthRequest) Reset()         { *m = ModifyOuthRequest{} }
func (m *ModifyOuthRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyOuthRequest) ProtoMessage()    {}
func (*ModifyOuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{8}
}

func (m *ModifyOuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyOuthRequest.Unmarshal(m, b)
}
func (m *ModifyOuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyOuthRequest.Marshal(b, m, deterministic)
}
func (m *ModifyOuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyOuthRequest.Merge(m, src)
}
func (m *ModifyOuthRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyOuthRequest.Size(m)
}
func (m *ModifyOuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyOuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyOuthRequest proto.InternalMessageInfo

func (m *ModifyOuthRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ModifyOuthRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *ModifyOuthRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ModifyOuthRequest) GetOuthType() int64 {
	if m != nil {
		return m.OuthType
	}
	return 0
}

func (m *ModifyOuthRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ModifyOuthRequest) GetIsUnbind() bool {
	if m != nil {
		return m.IsUnbind
	}
	return false
}

type GetUserListRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Status               int64    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	IdList               []int64  `protobuf:"varint,4,rep,packed,name=idList,proto3" json:"idList,omitempty"`
	CancelType           int64    `protobuf:"varint,5,opt,name=cancel_type,json=cancelType,proto3" json:"cancel_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserListRequest) Reset()         { *m = GetUserListRequest{} }
func (m *GetUserListRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserListRequest) ProtoMessage()    {}
func (*GetUserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{9}
}

func (m *GetUserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListRequest.Unmarshal(m, b)
}
func (m *GetUserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListRequest.Marshal(b, m, deterministic)
}
func (m *GetUserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListRequest.Merge(m, src)
}
func (m *GetUserListRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserListRequest.Size(m)
}
func (m *GetUserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListRequest proto.InternalMessageInfo

func (m *GetUserListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUserListRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetUserListRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetUserListRequest) GetIdList() []int64 {
	if m != nil {
		return m.IdList
	}
	return nil
}

func (m *GetUserListRequest) GetCancelType() int64 {
	if m != nil {
		return m.CancelType
	}
	return 0
}

type GetUserListResponse struct {
	List                 []*UserDataResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total                int64               `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetUserListResponse) Reset()         { *m = GetUserListResponse{} }
func (m *GetUserListResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserListResponse) ProtoMessage()    {}
func (*GetUserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{10}
}

func (m *GetUserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListResponse.Unmarshal(m, b)
}
func (m *GetUserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListResponse.Marshal(b, m, deterministic)
}
func (m *GetUserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListResponse.Merge(m, src)
}
func (m *GetUserListResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserListResponse.Size(m)
}
func (m *GetUserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListResponse proto.InternalMessageInfo

func (m *GetUserListResponse) GetList() []*UserDataResponse {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetUserListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CancelRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelRequest) Reset()         { *m = CancelRequest{} }
func (m *CancelRequest) String() string { return proto.CompactTextString(m) }
func (*CancelRequest) ProtoMessage()    {}
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{11}
}

func (m *CancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRequest.Unmarshal(m, b)
}
func (m *CancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRequest.Marshal(b, m, deterministic)
}
func (m *CancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRequest.Merge(m, src)
}
func (m *CancelRequest) XXX_Size() int {
	return xxx_messageInfo_CancelRequest.Size(m)
}
func (m *CancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRequest proto.InternalMessageInfo

func (m *CancelRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type EnterCancelRequest struct {
	List                 []int64  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterCancelRequest) Reset()         { *m = EnterCancelRequest{} }
func (m *EnterCancelRequest) String() string { return proto.CompactTextString(m) }
func (*EnterCancelRequest) ProtoMessage()    {}
func (*EnterCancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{12}
}

func (m *EnterCancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterCancelRequest.Unmarshal(m, b)
}
func (m *EnterCancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterCancelRequest.Marshal(b, m, deterministic)
}
func (m *EnterCancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterCancelRequest.Merge(m, src)
}
func (m *EnterCancelRequest) XXX_Size() int {
	return xxx_messageInfo_EnterCancelRequest.Size(m)
}
func (m *EnterCancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterCancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnterCancelRequest proto.InternalMessageInfo

func (m *EnterCancelRequest) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type FindUserFromQueryRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	No                   bool     `protobuf:"varint,2,opt,name=no,proto3" json:"no,omitempty"`
	Phone                bool     `protobuf:"varint,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                 bool     `protobuf:"varint,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserFromQueryRequest) Reset()         { *m = FindUserFromQueryRequest{} }
func (m *FindUserFromQueryRequest) String() string { return proto.CompactTextString(m) }
func (*FindUserFromQueryRequest) ProtoMessage()    {}
func (*FindUserFromQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{13}
}

func (m *FindUserFromQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserFromQueryRequest.Unmarshal(m, b)
}
func (m *FindUserFromQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserFromQueryRequest.Marshal(b, m, deterministic)
}
func (m *FindUserFromQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserFromQueryRequest.Merge(m, src)
}
func (m *FindUserFromQueryRequest) XXX_Size() int {
	return xxx_messageInfo_FindUserFromQueryRequest.Size(m)
}
func (m *FindUserFromQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserFromQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserFromQueryRequest proto.InternalMessageInfo

func (m *FindUserFromQueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *FindUserFromQueryRequest) GetNo() bool {
	if m != nil {
		return m.No
	}
	return false
}

func (m *FindUserFromQueryRequest) GetPhone() bool {
	if m != nil {
		return m.Phone
	}
	return false
}

func (m *FindUserFromQueryRequest) GetName() bool {
	if m != nil {
		return m.Name
	}
	return false
}

type FindUserFromQueryResponse struct {
	List                 []int64  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUserFromQueryResponse) Reset()         { *m = FindUserFromQueryResponse{} }
func (m *FindUserFromQueryResponse) String() string { return proto.CompactTextString(m) }
func (*FindUserFromQueryResponse) ProtoMessage()    {}
func (*FindUserFromQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{14}
}

func (m *FindUserFromQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUserFromQueryResponse.Unmarshal(m, b)
}
func (m *FindUserFromQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUserFromQueryResponse.Marshal(b, m, deterministic)
}
func (m *FindUserFromQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUserFromQueryResponse.Merge(m, src)
}
func (m *FindUserFromQueryResponse) XXX_Size() int {
	return xxx_messageInfo_FindUserFromQueryResponse.Size(m)
}
func (m *FindUserFromQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUserFromQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindUserFromQueryResponse proto.InternalMessageInfo

func (m *FindUserFromQueryResponse) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type BatchModifyRequest struct {
	List                 []int64  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	Type                 int64    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchModifyRequest) Reset()         { *m = BatchModifyRequest{} }
func (m *BatchModifyRequest) String() string { return proto.CompactTextString(m) }
func (*BatchModifyRequest) ProtoMessage()    {}
func (*BatchModifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{15}
}

func (m *BatchModifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchModifyRequest.Unmarshal(m, b)
}
func (m *BatchModifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchModifyRequest.Marshal(b, m, deterministic)
}
func (m *BatchModifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchModifyRequest.Merge(m, src)
}
func (m *BatchModifyRequest) XXX_Size() int {
	return xxx_messageInfo_BatchModifyRequest.Size(m)
}
func (m *BatchModifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchModifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchModifyRequest proto.InternalMessageInfo

func (m *BatchModifyRequest) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *BatchModifyRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "app.LoginRequest")
	proto.RegisterType((*UserDataResponse)(nil), "app.UserDataResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "app.UpdateUserRequest")
	proto.RegisterType((*PhoneCheckRequest)(nil), "app.PhoneCheckRequest")
	proto.RegisterType((*PhoneCheckResponse)(nil), "app.PhoneCheckResponse")
	proto.RegisterType((*AddressRequest)(nil), "app.AddressRequest")
	proto.RegisterType((*AddressResponse)(nil), "app.AddressResponse")
	proto.RegisterType((*AddressData)(nil), "app.AddressData")
	proto.RegisterType((*ModifyOuthRequest)(nil), "app.ModifyOuthRequest")
	proto.RegisterType((*GetUserListRequest)(nil), "app.GetUserListRequest")
	proto.RegisterType((*GetUserListResponse)(nil), "app.GetUserListResponse")
	proto.RegisterType((*CancelRequest)(nil), "app.cancelRequest")
	proto.RegisterType((*EnterCancelRequest)(nil), "app.enterCancelRequest")
	proto.RegisterType((*FindUserFromQueryRequest)(nil), "app.findUserFromQueryRequest")
	proto.RegisterType((*FindUserFromQueryResponse)(nil), "app.findUserFromQueryResponse")
	proto.RegisterType((*BatchModifyRequest)(nil), "app.BatchModifyRequest")
}

func init() { proto.RegisterFile("user_service.proto", fileDescriptor_292f630cd9eb4c90) }

var fileDescriptor_292f630cd9eb4c90 = []byte{
	// 1202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6f, 0xe3, 0x44,
	0x10, 0x97, 0xed, 0x7c, 0x38, 0x93, 0x34, 0x4d, 0xf7, 0xfa, 0xe1, 0x06, 0x1d, 0x14, 0x83, 0x20,
	0x48, 0xa8, 0xc0, 0x71, 0x12, 0x88, 0x2f, 0x71, 0x94, 0x0f, 0x55, 0xba, 0x83, 0xe2, 0x6b, 0xe1,
	0x31, 0x72, 0xe3, 0x6d, 0xb2, 0xbd, 0xc4, 0xf6, 0x79, 0x37, 0xed, 0x95, 0xff, 0x81, 0x67, 0x9e,
	0x91, 0xf8, 0x8f, 0x78, 0xe6, 0x89, 0x7f, 0x04, 0xcd, 0xec, 0xda, 0xd9, 0x34, 0x69, 0x25, 0xde,
	0x76, 0x66, 0xbd, 0xf3, 0xf1, 0x9b, 0xdf, 0xcc, 0x18, 0xd8, 0x5c, 0xf2, 0x62, 0x28, 0x79, 0x71,
	0x25, 0x46, 0xfc, 0x30, 0x2f, 0x32, 0x95, 0x31, 0x2f, 0xce, 0xf3, 0x3e, 0x24, 0xb1, 0x8a, 0xb5,
	0x22, 0xfc, 0xdb, 0x85, 0xce, 0xd3, 0x6c, 0x2c, 0xd2, 0x88, 0xbf, 0x9c, 0x73, 0xa9, 0x18, 0x83,
	0x9a, 0xba, 0xc9, 0x79, 0xe0, 0x1c, 0x38, 0x03, 0x2f, 0xa2, 0x33, 0xdb, 0x81, 0x46, 0x9c, 0xe7,
	0x43, 0x91, 0x04, 0xee, 0x81, 0x33, 0x68, 0x45, 0xf5, 0x38, 0xcf, 0x8f, 0x13, 0xb6, 0x0b, 0x0d,
	0xc9, 0x47, 0x05, 0x57, 0x81, 0x47, 0x6a, 0x23, 0xa1, 0x89, 0x51, 0x96, 0xf0, 0xa0, 0x46, 0x5a,
	0x3a, 0xb3, 0xd7, 0xa0, 0x95, 0xcd, 0xd5, 0x64, 0x48, 0xb6, 0xeb, 0x64, 0xdb, 0x47, 0xc5, 0x29,
	0xda, 0xdf, 0x86, 0x7a, 0x3e, 0xc9, 0x52, 0x1e, 0x34, 0xb4, 0x79, 0x12, 0xd0, 0x4c, 0x1e, 0x4b,
	0x19, 0x34, 0xb5, 0x19, 0x3c, 0xa3, 0x2e, 0x8d, 0x67, 0x3c, 0xf0, 0xb5, 0x0e, 0xcf, 0xa8, 0x9b,
	0xf0, 0x38, 0x09, 0x5a, 0x5a, 0x87, 0x67, 0xf6, 0x0e, 0x74, 0x85, 0x7c, 0x26, 0x52, 0x71, 0x52,
	0x64, 0xe3, 0x22, 0x9e, 0xc9, 0x00, 0x0e, 0x9c, 0x81, 0x1f, 0xdd, 0xd2, 0x62, 0x0a, 0x09, 0x47,
	0x7c, 0x82, 0xb6, 0x4e, 0x41, 0x4b, 0xac, 0x07, 0xde, 0x5c, 0x24, 0x41, 0x87, 0x02, 0xc5, 0x23,
	0x7a, 0x91, 0x62, 0x9c, 0x06, 0x1b, 0xda, 0x0b, 0x9e, 0xd9, 0x1e, 0x34, 0x2f, 0x87, 0x2a, 0x7b,
	0xc1, 0xd3, 0xa0, 0xab, 0x9f, 0x5f, 0x9e, 0xa2, 0x14, 0xfe, 0x53, 0x83, 0xde, 0x99, 0xe4, 0xc5,
	0xb7, 0xb1, 0x8a, 0x23, 0x2e, 0xf3, 0x2c, 0x95, 0xbc, 0x8a, 0xdd, 0x59, 0x13, 0xbb, 0x6b, 0xc5,
	0x5e, 0xa1, 0xe1, 0xd9, 0x68, 0xf4, 0xc0, 0x93, 0xfc, 0x15, 0x61, 0xea, 0x45, 0x78, 0x2c, 0x63,
	0xac, 0x2f, 0x62, 0xdc, 0x83, 0x66, 0x96, 0xf3, 0x14, 0x0b, 0xa5, 0x91, 0x6c, 0xa0, 0x78, 0x9c,
	0xb0, 0x2e, 0xb8, 0x69, 0x66, 0x80, 0x74, 0xd3, 0x8c, 0xbd, 0x01, 0x6d, 0x91, 0x5e, 0x09, 0xc5,
	0x87, 0x54, 0x28, 0x8d, 0x26, 0x68, 0xd5, 0x11, 0x96, 0xab, 0x0f, 0xbe, 0x48, 0x78, 0xaa, 0x84,
	0xba, 0x21, 0x5c, 0xbd, 0xa8, 0x92, 0x2b, 0x24, 0xc0, 0x42, 0xa2, 0x0f, 0x7e, 0x5e, 0x64, 0x57,
	0x22, 0xad, 0x90, 0xac, 0x64, 0xa2, 0x03, 0xda, 0xe9, 0x18, 0x3a, 0xa0, 0x8d, 0x3e, 0xf8, 0x89,
	0x90, 0xaa, 0x10, 0x23, 0x65, 0x10, 0xad, 0x64, 0xac, 0xc9, 0x24, 0xbe, 0xe2, 0xbf, 0xbe, 0x22,
	0x50, 0xfd, 0xc8, 0x48, 0xf8, 0x06, 0x4f, 0x27, 0xc8, 0x89, 0x4d, 0xba, 0xa9, 0x64, 0x64, 0xa8,
	0x90, 0xc3, 0x94, 0x5f, 0x07, 0x3d, 0xba, 0xa9, 0x0b, 0xf9, 0x23, 0xbf, 0x66, 0x21, 0x74, 0x46,
	0x71, 0x3a, 0xe2, 0xd3, 0xe7, 0x2a, 0x56, 0x73, 0x19, 0x6c, 0xd1, 0xe5, 0x92, 0x0e, 0xb1, 0xd0,
	0xf2, 0x50, 0x89, 0x19, 0x0f, 0x18, 0x65, 0x0b, 0x5a, 0x75, 0x2a, 0x66, 0x9c, 0x3d, 0x04, 0x98,
	0x62, 0x87, 0x68, 0xee, 0x3e, 0xa0, 0xfb, 0x16, 0x69, 0x88, 0xbc, 0x01, 0x34, 0xe3, 0x24, 0x29,
	0xb8, 0x94, 0xc1, 0x36, 0x65, 0x52, 0x8a, 0x58, 0xa0, 0x78, 0xcc, 0x83, 0x1d, 0x5d, 0xa0, 0x78,
	0xcc, 0xd9, 0xbb, 0xb0, 0x59, 0xf0, 0x31, 0x26, 0x1a, 0x2b, 0x91, 0x51, 0xa1, 0x76, 0xe9, 0x4d,
	0xd7, 0x56, 0x1f, 0x27, 0x96, 0x4f, 0x8c, 0x69, 0xcf, 0xf6, 0x29, 0x66, 0x3c, 0xfc, 0xd7, 0x85,
	0xad, 0xb3, 0x3c, 0x89, 0x15, 0x47, 0x96, 0x95, 0xad, 0x5b, 0x11, 0xc7, 0x59, 0xd7, 0x46, 0xae,
	0xd5, 0x46, 0x86, 0x3a, 0xde, 0x12, 0xbd, 0x29, 0xbd, 0x9a, 0xd5, 0xf6, 0x6f, 0xc1, 0x46, 0x59,
	0x74, 0xbb, 0x6f, 0x3b, 0xa5, 0x92, 0xd2, 0xdf, 0x07, 0x3f, 0xe5, 0xd7, 0x43, 0x72, 0xa1, 0x49,
	0xd7, 0x4c, 0xf9, 0xf5, 0x89, 0xdd, 0xac, 0xcd, 0x65, 0xc2, 0x13, 0x79, 0x7c, 0x8b, 0x3c, 0x86,
	0xda, 0xad, 0x05, 0xb5, 0x6d, 0x7a, 0xc0, 0x2d, 0x7a, 0x94, 0x2d, 0xd3, 0xb6, 0x5a, 0xc6, 0x20,
	0xdd, 0xb9, 0x17, 0xe9, 0x8d, 0xb5, 0x48, 0xef, 0x83, 0x3f, 0x17, 0xc9, 0x70, 0x2a, 0xa4, 0x0a,
	0xba, 0x07, 0xde, 0xc0, 0x8b, 0x9a, 0x73, 0x91, 0x3c, 0x15, 0x52, 0x85, 0x4f, 0x60, 0xeb, 0x04,
	0x21, 0x3c, 0x9a, 0xf0, 0xd1, 0x8b, 0xfb, 0x41, 0x5e, 0xcc, 0x11, 0xd7, 0x9e, 0x23, 0xe1, 0xfb,
	0xc0, 0x6c, 0x13, 0x66, 0x12, 0xec, 0x42, 0xa3, 0xe0, 0x72, 0x3e, 0x55, 0x66, 0xca, 0x1a, 0x29,
	0x7c, 0x0c, 0xdd, 0x27, 0x9a, 0x3b, 0xa5, 0xb7, 0x2e, 0xb8, 0x22, 0x31, 0x5f, 0xb9, 0x56, 0x99,
	0xdc, 0x45, 0x99, 0xc2, 0x4f, 0x60, 0xb3, 0x7a, 0x65, 0x1c, 0xbc, 0x0d, 0x35, 0x4a, 0xc8, 0x39,
	0xf0, 0x06, 0xed, 0x47, 0xbd, 0xc3, 0x38, 0xcf, 0x0f, 0xcd, 0x37, 0x34, 0x92, 0xe8, 0x36, 0xfc,
	0xc3, 0x81, 0xb6, 0xa5, 0x5d, 0x71, 0xd6, 0x03, 0x2f, 0x37, 0x33, 0xdf, 0x8b, 0xf0, 0x58, 0x55,
	0xd4, 0xb3, 0x2a, 0xba, 0x0d, 0xf5, 0x0b, 0x51, 0x48, 0x65, 0xc6, 0xbd, 0x16, 0x30, 0xc5, 0x29,
	0x57, 0x8a, 0x17, 0x44, 0x9a, 0x56, 0x64, 0xa4, 0x2a, 0xb2, 0xc6, 0xbd, 0x91, 0xfd, 0xe9, 0xc0,
	0xd6, 0xb3, 0x2c, 0x11, 0x17, 0x37, 0x3f, 0xcd, 0xd5, 0xa4, 0x04, 0x63, 0xb1, 0x86, 0x9c, 0xf5,
	0x6b, 0xc8, 0x5d, 0xbb, 0x86, 0xbc, 0xbb, 0xd6, 0x50, 0xed, 0xd6, 0x1a, 0x5a, 0x1d, 0xa8, 0x38,
	0x06, 0xe5, 0x59, 0x7a, 0x2e, 0x52, 0x3d, 0x51, 0xfd, 0xa8, 0x92, 0xc3, 0xdf, 0x1d, 0x60, 0x3f,
	0x70, 0x85, 0x0d, 0x88, 0x6c, 0xb1, 0xf6, 0x67, 0x8e, 0x5c, 0x34, 0xfb, 0x13, 0xcf, 0x9a, 0xf4,
	0xbf, 0x55, 0x55, 0xc3, 0x33, 0x45, 0xad, 0x87, 0x92, 0xee, 0x42, 0x23, 0xa1, 0x5e, 0xd3, 0x2f,
	0xa8, 0x11, 0x1b, 0x8d, 0x64, 0x8f, 0xa9, 0x45, 0x2b, 0x96, 0x63, 0x0a, 0x69, 0xf0, 0x0b, 0x3c,
	0x58, 0x0a, 0xc7, 0x50, 0xe1, 0xbd, 0x25, 0x2a, 0xec, 0x10, 0xe0, 0xb7, 0x57, 0x93, 0x46, 0x1d,
	0x2b, 0xa9, 0x32, 0x15, 0x4f, 0x4d, 0x9c, 0x5a, 0x08, 0xdf, 0x84, 0x0d, 0xed, 0xa5, 0xcc, 0xd0,
	0xc0, 0xe4, 0x54, 0x30, 0x85, 0x03, 0x60, 0x3c, 0x55, 0xbc, 0x38, 0x5a, 0xfa, 0x8e, 0x59, 0x9e,
	0x3d, 0x53, 0xd8, 0x4b, 0x08, 0x2e, 0x44, 0x9a, 0x60, 0x00, 0xdf, 0x17, 0xd9, 0xec, 0xe7, 0x39,
	0x2f, 0x6e, 0xac, 0xce, 0x7a, 0x89, 0x72, 0x59, 0x5d, 0x12, 0xcc, 0xea, 0x72, 0x09, 0x7c, 0x5c,
	0x5d, 0x4b, 0xdb, 0xd1, 0xb7, 0x86, 0x1c, 0x11, 0xb3, 0x46, 0x4a, 0x3a, 0x87, 0x1f, 0xc0, 0xfe,
	0x1a, 0x5f, 0x8b, 0x65, 0xbc, 0x12, 0xdc, 0x17, 0xc0, 0xbe, 0x89, 0xd5, 0x68, 0xa2, 0x99, 0x77,
	0x4f, 0x1a, 0xeb, 0xda, 0xf0, 0xd1, 0x5f, 0x75, 0x68, 0xa3, 0xaf, 0xe7, 0xfa, 0x87, 0x8b, 0x7d,
	0x04, 0x75, 0x1a, 0xd8, 0x6c, 0x8b, 0x30, 0xb7, 0x7f, 0xb2, 0xfa, 0xeb, 0xcb, 0xc0, 0x1e, 0x83,
	0xaf, 0xa7, 0x13, 0x2f, 0xfe, 0xc7, 0xab, 0xcf, 0x01, 0xe6, 0xd5, 0x2e, 0x60, 0xbb, 0xfa, 0xa3,
	0xdb, 0xcb, 0xe1, 0xae, 0xc7, 0x5f, 0xc1, 0xe6, 0xf9, 0x22, 0x67, 0x6a, 0x83, 0x3d, 0xfa, 0x72,
	0x15, 0x89, 0x3e, 0xa3, 0x8b, 0xef, 0x66, 0xb9, 0xba, 0xb1, 0x42, 0xae, 0xd6, 0xdd, 0x03, 0xbb,
	0x99, 0xcb, 0x37, 0xdb, 0xcb, 0x4a, 0xf3, 0xea, 0x4b, 0x80, 0xbc, 0x1a, 0x8b, 0x26, 0xe4, 0x95,
	0x51, 0xdb, 0xdf, 0x5b, 0xd1, 0x9b, 0xe7, 0x9f, 0x02, 0xcc, 0xaa, 0xe9, 0x60, 0x9e, 0xaf, 0x8c,
	0x8b, 0xb5, 0xe1, 0x7e, 0x0d, 0xed, 0xf1, 0xa2, 0x49, 0x4c, 0xaa, 0xab, 0x5d, 0xdc, 0x0f, 0x56,
	0x2f, 0x8c, 0x85, 0x0f, 0xa1, 0xa1, 0xdb, 0x81, 0x69, 0xfb, 0x4b, 0xbd, 0xb1, 0xd6, 0xe7, 0x67,
	0xd0, 0xb6, 0xba, 0xc3, 0xf8, 0x5c, 0xed, 0x97, 0xb5, 0x6f, 0x4f, 0x60, 0x13, 0x39, 0x7c, 0x9c,
	0x54, 0x0c, 0x66, 0x0f, 0xe9, 0xb3, 0xbb, 0xba, 0xa8, 0xff, 0xfa, 0x5d, 0xd7, 0xda, 0xe2, 0x79,
	0x83, 0xfe, 0xfb, 0x3f, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xad, 0xe0, 0x93, 0xcf, 0x1e, 0x0c,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	//检查通道连接
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserDataResponse, error)
	Register(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserDataResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserDataResponse, error)
	BatchModifyType(ctx context.Context, in *BatchModifyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Address(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressResponse, error)
	PhoneCheck(ctx context.Context, in *PhoneCheckRequest, opts ...grpc.CallOption) (*PhoneCheckResponse, error)
	ModifyOuth(ctx context.Context, in *ModifyOuthRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetUserList(ctx context.Context, in *GetUserListRequest, opts ...grpc.CallOption) (*GetUserListResponse, error)
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	EnterCancel(ctx context.Context, in *EnterCancelRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	FindIdFromQuery(ctx context.Context, in *FindUserFromQueryRequest, opts ...grpc.CallOption) (*FindUserFromQueryResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserDataResponse, error) {
	out := new(UserDataResponse)
	err := c.cc.Invoke(ctx, "/app.UserService/login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Register(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserDataResponse, error) {
	out := new(UserDataResponse)
	err := c.cc.Invoke(ctx, "/app.UserService/register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserDataResponse, error) {
	out := new(UserDataResponse)
	err := c.cc.Invoke(ctx, "/app.UserService/updateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) BatchModifyType(ctx context.Context, in *BatchModifyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.UserService/batchModifyType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Address(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressResponse, error) {
	out := new(AddressResponse)
	err := c.cc.Invoke(ctx, "/app.UserService/address", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PhoneCheck(ctx context.Context, in *PhoneCheckRequest, opts ...grpc.CallOption) (*PhoneCheckResponse, error) {
	out := new(PhoneCheckResponse)
	err := c.cc.Invoke(ctx, "/app.UserService/phoneCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ModifyOuth(ctx context.Context, in *ModifyOuthRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.UserService/modifyOuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserList(ctx context.Context, in *GetUserListRequest, opts ...grpc.CallOption) (*GetUserListResponse, error) {
	out := new(GetUserListResponse)
	err := c.cc.Invoke(ctx, "/app.UserService/getUserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.UserService/cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) EnterCancel(ctx context.Context, in *EnterCancelRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/app.UserService/enterCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FindIdFromQuery(ctx context.Context, in *FindUserFromQueryRequest, opts ...grpc.CallOption) (*FindUserFromQueryResponse, error) {
	out := new(FindUserFromQueryResponse)
	err := c.cc.Invoke(ctx, "/app.UserService/findIdFromQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	//检查通道连接
	Login(context.Context, *LoginRequest) (*UserDataResponse, error)
	Register(context.Context, *LoginRequest) (*UserDataResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UserDataResponse, error)
	BatchModifyType(context.Context, *BatchModifyRequest) (*EmptyResponse, error)
	Address(context.Context, *AddressRequest) (*AddressResponse, error)
	PhoneCheck(context.Context, *PhoneCheckRequest) (*PhoneCheckResponse, error)
	ModifyOuth(context.Context, *ModifyOuthRequest) (*EmptyResponse, error)
	GetUserList(context.Context, *GetUserListRequest) (*GetUserListResponse, error)
	Cancel(context.Context, *CancelRequest) (*EmptyResponse, error)
	EnterCancel(context.Context, *EnterCancelRequest) (*EmptyResponse, error)
	FindIdFromQuery(context.Context, *FindUserFromQueryRequest) (*FindUserFromQueryResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *LoginRequest) (*UserDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServiceServer) Register(ctx context.Context, req *LoginRequest) (*UserDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UserDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) BatchModifyType(ctx context.Context, req *BatchModifyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchModifyType not implemented")
}
func (*UnimplementedUserServiceServer) Address(ctx context.Context, req *AddressRequest) (*AddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Address not implemented")
}
func (*UnimplementedUserServiceServer) PhoneCheck(ctx context.Context, req *PhoneCheckRequest) (*PhoneCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PhoneCheck not implemented")
}
func (*UnimplementedUserServiceServer) ModifyOuth(ctx context.Context, req *ModifyOuthRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyOuth not implemented")
}
func (*UnimplementedUserServiceServer) GetUserList(ctx context.Context, req *GetUserListRequest) (*GetUserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserList not implemented")
}
func (*UnimplementedUserServiceServer) Cancel(ctx context.Context, req *CancelRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (*UnimplementedUserServiceServer) EnterCancel(ctx context.Context, req *EnterCancelRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnterCancel not implemented")
}
func (*UnimplementedUserServiceServer) FindIdFromQuery(ctx context.Context, req *FindUserFromQueryRequest) (*FindUserFromQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindIdFromQuery not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_BatchModifyType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).BatchModifyType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserService/BatchModifyType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).BatchModifyType(ctx, req.(*BatchModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Address_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Address(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserService/Address",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Address(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PhoneCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PhoneCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserService/PhoneCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PhoneCheck(ctx, req.(*PhoneCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ModifyOuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyOuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ModifyOuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserService/ModifyOuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ModifyOuth(ctx, req.(*ModifyOuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserService/GetUserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserList(ctx, req.(*GetUserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserService/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_EnterCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).EnterCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserService/EnterCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).EnterCancel(ctx, req.(*EnterCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FindIdFromQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUserFromQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindIdFromQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.UserService/FindIdFromQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindIdFromQuery(ctx, req.(*FindUserFromQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "updateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "batchModifyType",
			Handler:    _UserService_BatchModifyType_Handler,
		},
		{
			MethodName: "address",
			Handler:    _UserService_Address_Handler,
		},
		{
			MethodName: "phoneCheck",
			Handler:    _UserService_PhoneCheck_Handler,
		},
		{
			MethodName: "modifyOuth",
			Handler:    _UserService_ModifyOuth_Handler,
		},
		{
			MethodName: "getUserList",
			Handler:    _UserService_GetUserList_Handler,
		},
		{
			MethodName: "cancel",
			Handler:    _UserService_Cancel_Handler,
		},
		{
			MethodName: "enterCancel",
			Handler:    _UserService_EnterCancel_Handler,
		},
		{
			MethodName: "findIdFromQuery",
			Handler:    _UserService_FindIdFromQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_service.proto",
}
